/*
 * CEKF - VM supporting amb
 * Copyright (C) 2022-2026  Bill Hails
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * Abstract Syntax Tree (AST) structures generated by the parser. As this is
 * close to the surface of the language, it is quite complicated. The complexity
 * is reduced downstream by conversion to simple lambda form. Generated from
 * src/ast.yaml by tools/generate.py
 */

#include "ast.h"
#include "ast_pp.h"
#include "bigint.h"
#include "memory.h"
#include "symbol.h"
#include "symbols.h"
#include "utils.h"
#include "utils_helper.h"

#include "ast_ns.h"

#ifdef DEBUG_AST_NS
#include "debugging_on.h"
#else
#include "debugging_off.h"
#endif

typedef struct VisitorContext {
    AstNameSpaceArray *nameSpaces;
    SymbolMap *replacements;
} VisitorContext;

static AstNest *nsAstNest(AstNest *, VisitorContext);
static AstNameSpaceImpl *nsAstNameSpaceImpl(AstNameSpaceImpl *, int,
                                            VisitorContext);
static AstDefinitions *nsAstDefinitions(AstDefinitions *, VisitorContext);
static AstDefine *nsAstDefine(AstDefine *, VisitorContext);
static AstMultiDefine *nsAstMultiDefine(AstMultiDefine *, VisitorContext);
static AstSymbolList *nsAstSymbolList(AstSymbolList *, VisitorContext);
static AstAlias *nsAstAlias(AstAlias *, VisitorContext);
static AstExprAlias *nsAstExprAlias(AstExprAlias *, VisitorContext);
static AstAnnotatedSymbol *nsAstAnnotatedSymbol(AstAnnotatedSymbol *,
                                                VisitorContext);
static AstDefLazy *nsAstDefLazy(AstDefLazy *, VisitorContext);
static AstTypeDef *nsAstTypeDef(AstTypeDef *, VisitorContext);
static AstTypeSig *nsAstTypeSig(AstTypeSig *, VisitorContext);
static AstTypeSymbols *nsAstTypeSymbols(AstTypeSymbols *, VisitorContext);
static AstTypeBody *nsAstTypeBody(AstTypeBody *, VisitorContext);
static AstTypeConstructor *nsAstTypeConstructor(AstTypeConstructor *,
                                                VisitorContext);
static AstTypeFunction *nsAstTypeFunction(AstTypeFunction *, VisitorContext);
static AstTypeList *nsAstTypeList(AstTypeList *, VisitorContext);
static AstTypeMap *nsAstTypeMap(AstTypeMap *, VisitorContext);
static AstType *nsAstType(AstType *, VisitorContext);
static AstCompositeFunction *nsAstCompositeFunction(AstCompositeFunction *,
                                                    VisitorContext);
static AstFunction *nsAstFunction(AstFunction *, VisitorContext);
static AstFargList *nsAstFargList(AstFargList *, VisitorContext);
static AstTaggedArgList *nsAstTaggedArgList(AstTaggedArgList *, VisitorContext);
static AstAltArgs *nsAstAltArgs(AstAltArgs *, VisitorContext);
static AstAltFunction *nsAstAltFunction(AstAltFunction *, VisitorContext);
static AstUnpack *nsAstUnpack(AstUnpack *, VisitorContext);
static AstUnpackStruct *nsAstUnpackStruct(AstUnpackStruct *, VisitorContext);
static AstNamedArg *nsAstNamedArg(AstNamedArg *, VisitorContext);
static AstFunCall *nsAstFunCall(AstFunCall *, VisitorContext);
static AstExpressions *nsAstExpressions(AstExpressions *, VisitorContext);
static HashSymbol *nsAstLookUpSymbol(AstLookUpSymbol *, VisitorContext);
static AstExpression *nsAstLookUp(AstLookUp *, VisitorContext);
static AstIff *nsAstIff(AstIff *, VisitorContext);
static AstPrint *nsAstPrint(AstPrint *, VisitorContext);
static AstTypeOf *nsAstTypeOf(AstTypeOf *, VisitorContext);
static AstStruct *nsAstStruct(AstStruct *, VisitorContext);
static AstTaggedExpressions *nsAstTaggedExpressions(AstTaggedExpressions *,
                                                    VisitorContext);
static AstTypeConstructorArgs *
nsAstTypeConstructorArgs(AstTypeConstructorArgs *, VisitorContext);
static AstLookUpOrSymbol *nsAstLookUpOrSymbol(AstLookUpOrSymbol *,
                                              VisitorContext);
static AstSyntaxDecl *nsAstSyntaxDecl(AstSyntaxDecl *, VisitorContext);
static AstSyntaxAlternatives *nsAstSyntaxAlternatives(AstSyntaxAlternatives *,
                                                      VisitorContext);
static AstSyntaxAlternative *nsAstSyntaxAlternative(AstSyntaxAlternative *,
                                                    VisitorContext);
static AstSyntaxTemplate *nsAstSyntaxTemplate(AstSyntaxTemplate *,
                                              VisitorContext);
static AstSyntaxTemplateDefinitions *
nsAstSyntaxTemplateDefinitions(AstSyntaxTemplateDefinitions *, VisitorContext);
static AstSyntaxTemplateDefinition *
nsAstSyntaxTemplateDefinition(AstSyntaxTemplateDefinition *, VisitorContext);
static AstSyntaxTemplateNameRef *
nsAstSyntaxTemplateNameRef(AstSyntaxTemplateNameRef *, VisitorContext);
static AstSyntaxTemplateBinder *
nsAstSyntaxTemplateBinder(AstSyntaxTemplateBinder *, VisitorContext);
static AstSyntaxTemplateBinders *
nsAstSyntaxTemplateBinders(AstSyntaxTemplateBinders *, VisitorContext);
static AstSyntaxTemplateExpr *nsAstSyntaxTemplateExpr(AstSyntaxTemplateExpr *,
                                                      VisitorContext);
static AstSyntaxTemplateExprs *
nsAstSyntaxTemplateExprs(AstSyntaxTemplateExprs *, VisitorContext);
static AstSyntaxTemplateNest *nsAstSyntaxTemplateNest(AstSyntaxTemplateNest *,
                                                      VisitorContext);
static AstSyntaxTemplateFunction *
nsAstSyntaxTemplateFunction(AstSyntaxTemplateFunction *, VisitorContext);
static AstSyntaxTemplateAltFunction *
nsAstSyntaxTemplateAltFunction(AstSyntaxTemplateAltFunction *, VisitorContext);
static AstSyntaxTemplateAltArgs *
nsAstSyntaxTemplateAltArgs(AstSyntaxTemplateAltArgs *, VisitorContext);
static AstSyntaxTemplateFarg *nsAstSyntaxTemplateFarg(AstSyntaxTemplateFarg *,
                                                      VisitorContext);
static AstSyntaxTemplateFargList *
nsAstSyntaxTemplateFargList(AstSyntaxTemplateFargList *, VisitorContext);
static AstSyntaxTemplateTaggedArgs *
nsAstSyntaxTemplateTaggedArgs(AstSyntaxTemplateTaggedArgs *, VisitorContext);
static AstSyntaxTemplateTaggedExpressions *
nsAstSyntaxTemplateTaggedExpressions(AstSyntaxTemplateTaggedExpressions *,
                                     VisitorContext);
static AstSyntaxBinding *nsAstSyntaxBinding(AstSyntaxBinding *, VisitorContext);
static AstSyntaxBindings *nsAstSyntaxBindings(AstSyntaxBindings *,
                                              VisitorContext);
static AstExprSyntaxUse *nsAstExprSyntaxUse(AstExprSyntaxUse *, VisitorContext);
static AstDefSyntaxUse *nsAstDefSyntaxUse(AstDefSyntaxUse *, VisitorContext);
static AstDefinition *nsAstDefinition(AstDefinition *, VisitorContext);
static AstTypeClause *nsAstTypeClause(AstTypeClause *, VisitorContext);
static AstFarg *nsAstFarg(AstFarg *, VisitorContext);
static AstExpression *nsAstExpression(AstExpression *, VisitorContext);
static AstNameSpaceArray *nsAstNameSpaceArray(AstNameSpaceArray *,
                                              VisitorContext);
static SymbolMap *ensureNameSpaceReplacements(AstNameSpaceArray *nameSpaces,
                                              int nsId);
static HashSymbol *nsSymbol(HashSymbol *, VisitorContext);

/////////////////////////////////////
// The main rewrite tool for lookups
/////////////////////////////////////

static HashSymbol *generateQualifiedSymbol(HashSymbol *unqualified,
                                           FileId *id) {
    SCharVec *buf = newSCharVec(128 + strlen(unqualified->name));
    int save = PROTECT(buf);
    sprintf(buf->entries, "#%lu#%lu#%s", id->stIno, id->stDev,
            unqualified->name);
    HashSymbol *qualified = newSymbol(buf->entries);
    UNPROTECT(save);
    return qualified;
}

///////////////////////
// Populate SymbolMaps
///////////////////////

static void populateReplacementsFromAlias(AstAlias *alias, FileId *id,
                                          VisitorContext context) {
    HashSymbol *replacement = generateQualifiedSymbol(alias->name, id);
    setSymbolMap(context.replacements, alias->name, replacement);
}

static void populateReplacementsFromDefine(AstDefine *define, FileId *id,
                                           VisitorContext context) {
    HashSymbol *replacement = generateQualifiedSymbol(define->symbol, id);
    setSymbolMap(context.replacements, define->symbol, replacement);
}

static void populateReplacementsFromLazy(AstDefLazy *lazy, FileId *id,
                                         VisitorContext context) {
    HashSymbol *replacement = generateQualifiedSymbol(lazy->name, id);
    setSymbolMap(context.replacements, lazy->name, replacement);
}

static void populateReplacementsFromSymbolList(AstSymbolList *list, FileId *id,
                                               VisitorContext context) {
    if (list == NULL)
        return;
    populateReplacementsFromSymbolList(list->next, id, context);
    static HashSymbol *wildCard = NULL;
    if (wildCard == NULL)
        wildCard = newSymbol("_");
    if (list->symbol != wildCard) {
        HashSymbol *replacement = generateQualifiedSymbol(list->symbol, id);
        setSymbolMap(context.replacements, list->symbol, replacement);
    }
}

static void populateReplacementsFromMulti(AstMultiDefine *multi, FileId *id,
                                          VisitorContext context) {
    populateReplacementsFromSymbolList(multi->symbols, id, context);
}

static void populateReplacementsFromTypeSig(AstTypeSig *typeSig, FileId *id,
                                            VisitorContext context) {
    HashSymbol *replacement = generateQualifiedSymbol(typeSig->symbol, id);
    setSymbolMap(context.replacements, typeSig->symbol, replacement);
}

static void
populateReplacementsFromTypeConstructor(AstTypeConstructor *typeConstructor,
                                        FileId *id, VisitorContext context) {
    HashSymbol *replacement =
        generateQualifiedSymbol(typeConstructor->symbol, id);
    setSymbolMap(context.replacements, typeConstructor->symbol, replacement);
}

static void populateReplacementsFromTypeBody(AstTypeBody *typeBody, FileId *id,
                                             VisitorContext context) {
    if (typeBody == NULL)
        return;
    populateReplacementsFromTypeBody(typeBody->next, id, context);
    populateReplacementsFromTypeConstructor(typeBody->typeConstructor, id,
                                            context);
}

static void populateReplacementsFromTypeDef(AstTypeDef *typeDef, FileId *id,
                                            VisitorContext context) {
    populateReplacementsFromTypeSig(typeDef->typeSig, id, context);
    populateReplacementsFromTypeBody(typeDef->typeBody, id, context);
}

static void populateReplacementsFromDefinitions(AstDefinitions *definitions,
                                                FileId *id,
                                                VisitorContext context) {
    if (definitions == NULL)
        return;
    populateReplacementsFromDefinitions(definitions->next, id, context);
    AstDefinition *def = definitions->definition;
    switch (def->type) {
    case AST_DEFINITION_TYPE_ALIAS:
        populateReplacementsFromAlias(getAstDefinition_Alias(def), id, context);
        break;
    case AST_DEFINITION_TYPE_BLANK:
    case AST_DEFINITION_TYPE_BUILTINSSLOT:
        break;
    case AST_DEFINITION_TYPE_DEFINE:
        populateReplacementsFromDefine(getAstDefinition_Define(def), id,
                                       context);
        break;
    case AST_DEFINITION_TYPE_LAZY:
        populateReplacementsFromLazy(getAstDefinition_Lazy(def), id, context);
        break;
    case AST_DEFINITION_TYPE_MULTI:
        populateReplacementsFromMulti(getAstDefinition_Multi(def), id, context);
        break;
    case AST_DEFINITION_TYPE_TYPEDEF:
        populateReplacementsFromTypeDef(getAstDefinition_TypeDef(def), id,
                                        context);
        break;
    case AST_DEFINITION_TYPE_SYNTAXDECL:
    case AST_DEFINITION_TYPE_SYNTAXUSE:
        break;
    default:
        cant_happen("unrecognized %s", astDefinitionTypeName(def->type));
    }
}

///////////////////////////////////////////
// currentFile definition and assertion
// rewriting helpers
///////////////////////////////////////////

// Builds: fn currentFile() { "fileName" }
// as a zero-arg function returning an AST cons-list of characters,
// prepended to `next`. Using a function ensures lambda conversion
// places it in the letrec (not let-star), preventing beta inlining.
static AstDefinitions *makeCurrentFileDefinition(const char *fileName,
                                                 ParserInfo PI,
                                                 AstDefinitions *next) {
    AstExpression *nil = newAstExpression_Symbol(PI, nilSymbol());
    int save = PROTECT(nil);
    AstFunCall *strList = newAstFunCall(PI, nil, NULL);
    PROTECT(strList);

    for (int i = strlen(fileName) - 1; i >= 0; i--) {
        AstExpression *character = newAstExpression_Character(PI, fileName[i]);
        int save2 = PROTECT(character);
        AstExpression *cons = newAstExpression_Symbol(PI, consSymbol());
        PROTECT(cons);
        AstExpression *tail = newAstExpression_FunCall(PI, strList);
        PROTECT(tail);
        AstExpressions *rhs = newAstExpressions(PI, tail, NULL);
        PROTECT(rhs);
        AstExpressions *args = newAstExpressions(PI, character, rhs);
        PROTECT(args);
        strList = newAstFunCall(PI, cons, args);
        REPLACE_PROTECT(save, strList);
        UNPROTECT(save2);
    }

    AstExpression *stringExpr = newAstExpression_FunCall(PI, strList);
    PROTECT(stringExpr);

    // Wrap in a zero-arg function: fn () { "..." }
    AstExpressions *bodyExpr = newAstExpressions(PI, stringExpr, NULL);
    PROTECT(bodyExpr);
    AstNest *nest = newAstNest(PI, NULL, bodyExpr);
    PROTECT(nest);
    AstFunction *func = newAstFunction(PI, NULL, nest);
    PROTECT(func);
    AstCompositeFunction *comp = newAstCompositeFunction(PI, func, NULL);
    PROTECT(comp);
    AstExpression *funExpr = newAstExpression_Fun(PI, comp);
    PROTECT(funExpr);

    AstDefinition *definition =
        makeAstDefinition_Define(PI, currentFileSymbol(), funExpr);
    PROTECT(definition);

    AstDefinitions *result = newAstDefinitions(PI, definition, next);
    UNPROTECT(save);
    return result;
}

// Rewrites: assert(condition)
// to:       __assert__(lineNo, currentFile, condition)
// where currentFile is looked up via the namespace symbol map.
static AstExpression *rewriteAssertionToCall(AstExpression *condition,
                                             VisitorContext context) {
    ParserInfo PI = CPI(condition);

    // lineNo argument
    MaybeBigInt *num = fakeBigInt(PI.lineNo, false);
    int save = PROTECT(num);
    AstExpression *lineNoExpr = newAstExpression_Number(PI, num);
    PROTECT(lineNoExpr);

    // currentFile() call (namespace-qualified, zero-arg function)
    HashSymbol *fileVar = nsSymbol(currentFileSymbol(), context);
    AstExpression *fileSymExpr = newAstExpression_Symbol(PI, fileVar);
    PROTECT(fileSymExpr);
    AstFunCall *fileCall = newAstFunCall(PI, fileSymExpr, NULL);
    PROTECT(fileCall);
    AstExpression *fileExpr = newAstExpression_FunCall(PI, fileCall);
    PROTECT(fileExpr);

    // build args: (lineNo, currentFile(), condition)
    AstExpressions *arg3 = newAstExpressions(PI, condition, NULL);
    PROTECT(arg3);
    AstExpressions *arg2 = newAstExpressions(PI, fileExpr, arg3);
    PROTECT(arg2);
    AstExpressions *args = newAstExpressions(PI, lineNoExpr, arg2);
    PROTECT(args);

    // callee: __assert__
    AstExpression *callee = newAstExpression_Symbol(PI, assertSymbol());
    PROTECT(callee);

    // function call
    AstFunCall *funCall = newAstFunCall(PI, callee, args);
    PROTECT(funCall);

    AstExpression *result = newAstExpression_FunCall(PI, funCall);
    UNPROTECT(save);
    return result;
}

/////////////////////////////////////////
// Switch to Appropriate NS Replacements
/////////////////////////////////////////

static VisitorContext getNsReplacements(VisitorContext context, int nsId) {
#ifdef SAFETY_CHECKS
    if (nsId < 0 || ((Index)nsId) >= context.nameSpaces->size) {
        cant_happen("invalid namespace id %d", nsId);
    }
    if (context.nameSpaces->entries[nsId] == NULL) {
        cant_happen("namespace id %d has not been visited yet [1]", nsId);
    }
#endif
    // CBV
    context.replacements =
        ensureNameSpaceReplacements(context.nameSpaces, nsId);
    return context;
}

static SymbolMap *ensureNameSpaceReplacements(AstNameSpaceArray *nameSpaces,
                                              int nsId) {
#ifdef SAFETY_CHECKS
    if (nsId < 0 || ((Index)nsId) >= nameSpaces->size) {
        cant_happen("invalid namespace id %d", nsId);
    }
    if (nameSpaces->entries[nsId] == NULL) {
        cant_happen("namespace id %d has not been parsed", nsId);
    }
#endif
    AstNameSpaceImpl *impl = nameSpaces->entries[nsId];
    if (impl->replacements != NULL) {
        return impl->replacements;
    }

    SymbolMap *replacements = newSymbolMap();
    int save = PROTECT(replacements);
    VisitorContext context = {.nameSpaces = nameSpaces,
                              .replacements = replacements};
    AstDefinitions *defs = impl->definitions;
    if (defs != NULL) {
        defs = makeCurrentFileDefinition(impl->id->fileName->entries, CPI(impl),
                                         impl->definitions);
        PROTECT(defs);
    }
    populateReplacementsFromDefinitions(defs, impl->id, context);
    impl->replacements = replacements;
    UNPROTECT(save);
    return replacements;
}

///////////////////////
// Merging Definitions
///////////////////////

// builds a new preamble with the contents of the namespace appended
// as normal definitions.
static AstDefinitions *
mergeNameSpaceToPreamble(AstDefinitions *preamble,
                         AstNameSpaceImpl *nameSpaceImpl) {
    if (preamble == NULL) {
        return nameSpaceImpl->definitions;
    } else {
        AstDefinitions *rest =
            mergeNameSpaceToPreamble(preamble->next, nameSpaceImpl);
        int save = PROTECT(rest);
        AstDefinitions *this =
            newAstDefinitions(CPI(preamble), preamble->definition, rest);
        UNPROTECT(save);
        return this;
    }
}

// append all namespaces to (and as part of) the preamble
static AstDefinitions *
mergeNameSpacesToPreamble(AstDefinitions *preamble,
                          AstNameSpaceArray *nameSpaces) {
    int save = PROTECT(preamble);
    for (Index i = 0; i < nameSpaces->size; i++) {
        AstNameSpaceImpl *nsImpl = nameSpaces->entries[i];
        preamble = mergeNameSpaceToPreamble(preamble, nsImpl);
        REPLACE_PROTECT(save, preamble);
    }
    UNPROTECT(save);
    return preamble;
}

////////////////////////////
// Visitor implementations
////////////////////////////

/**
 * Public API and main control.
 *
 * 1. Parse each namespace in dependency order, collecting a map
 *    from symbol to fully qualified replacement for each definition
 *    in the namespace as well as replacing lookups with previously
 *    collected qualified symbols from previous namespaces.
 * 2. Parse the body replacing lookups with qualified symbols.
 * 3. Append namespaces to the preamble as normal definitions.
 * 4. Return a new AstProg with the new preamble, new body and an
 *    empty namespace array.
 */
AstProg *nsAstProg(AstProg *node) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstProg);
    SymbolMap *replacements = newSymbolMap();
    int save = PROTECT(replacements);
    VisitorContext context = {.nameSpaces = node->nameSpaces,
                              .replacements = replacements};
    // namespaces
    AstNameSpaceArray *new_nameSpaces =
        nsAstNameSpaceArray(node->nameSpaces, context);
    PROTECT(new_nameSpaces);
    // body
    AstExpressions *new_body = nsAstExpressions(node->body, context);
    PROTECT(new_body);
    // merge namespace definitions into the preamble
    AstDefinitions *new_preamble =
        mergeNameSpacesToPreamble(node->preamble, new_nameSpaces);
    PROTECT(new_preamble);
    // always prepend currentFile (tree shaking removes it if unused)
    new_preamble =
        makeCurrentFileDefinition(CPI(node).fileName, CPI(node), new_preamble);
    PROTECT(new_preamble);
    new_nameSpaces = newAstNameSpaceArray();
    PROTECT(new_nameSpaces);
    AstProg *result =
        newAstProg(CPI(node), new_preamble, new_nameSpaces, new_body);
    UNPROTECT(save);
    LEAVE(nsAstProg);
    return result;
}

AstExpression *nsAstExpressionForNameSpace(AstExpression *node,
                                           AstNameSpaceArray *nameSpaces,
                                           int nsId) {
    if (node == NULL || nameSpaces == NULL || nsId < 0) {
        return node;
    }
    VisitorContext context = {
        .nameSpaces = nameSpaces,
        .replacements = ensureNameSpaceReplacements(nameSpaces, nsId)};
    return nsAstExpression(node, context);
}

AstSyntaxDecl *nsAstSyntaxDeclForNameSpace(AstSyntaxDecl *node,
                                           AstNameSpaceArray *nameSpaces,
                                           int nsId) {
    if (node == NULL || nameSpaces == NULL || nsId < 0) {
        return node;
    }
    VisitorContext context = {
        .nameSpaces = nameSpaces,
        .replacements = ensureNameSpaceReplacements(nameSpaces, nsId)};
    return nsAstSyntaxDecl(node, context);
}

static AstNest *nsAstNest(AstNest *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstNest);
    bool changed = false;
    AstDefinitions *new_definitions =
        nsAstDefinitions(node->definitions, context);
    int save = PROTECT(new_definitions);
    changed = changed || (new_definitions != node->definitions);
    AstExpressions *new_expressions =
        nsAstExpressions(node->expressions, context);
    PROTECT(new_expressions);
    changed = changed || (new_expressions != node->expressions);
    AstNest *result = node;
    if (changed) {
        result = newAstNest(CPI(node), new_definitions, new_expressions);
    }
    UNPROTECT(save);
    LEAVE(nsAstNest);
    return result;
}

static AstNameSpaceImpl *nsAstNameSpaceImpl(AstNameSpaceImpl *node, int nsId,
                                            VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstNameSpaceImpl);
    bool changed = false;
    context.replacements = newSymbolMap();
    int save = PROTECT(context.replacements);
    context.nameSpaces->entries[nsId]->replacements = context.replacements;
    AstDefinitions *defs = node->definitions;
    if (defs != NULL) {
        // Prepend currentFile definition so it enters the qualified symbol map
        defs = makeCurrentFileDefinition(node->id->fileName->entries, CPI(node),
                                         node->definitions);
        PROTECT(defs);
    }
    populateReplacementsFromDefinitions(defs, node->id, context);
    AstDefinitions *new_definitions = nsAstDefinitions(defs, context);
    PROTECT(new_definitions);
    changed = changed || (new_definitions != defs);
    AstNameSpaceImpl *result = node;
    if (changed) {
        result = newAstNameSpaceImpl(CPI(node), node->id, new_definitions);
    }
    result->replacements = context.replacements;
    UNPROTECT(save);
    LEAVE(nsAstNameSpaceImpl);
    return result;
}

// definitions at the top-level of a namespace should have their
// symbols replaced.
static AstDefinitions *nsAstDefinitions(AstDefinitions *node,
                                        VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstDefinitions);
    bool changed = false;
    AstDefinition *new_definition = nsAstDefinition(node->definition, context);
    int save = PROTECT(new_definition);
    changed = changed || (new_definition != node->definition);
    AstDefinitions *new_next = nsAstDefinitions(node->next, context);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);
    AstDefinitions *result = node;
    if (changed) {
        result = newAstDefinitions(CPI(node), new_definition, new_next);
    }
    UNPROTECT(save);
    LEAVE(nsAstDefinitions);
    return result;
}

static AstDefine *nsAstDefine(AstDefine *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstDefine);
    bool changed = false;
    AstExpression *new_expression = nsAstExpression(node->expression, context);
    int save = PROTECT(new_expression);
    changed = changed || (new_expression != node->expression);
    HashSymbol *new_symbol = nsSymbol(node->symbol, context);
    changed = changed || (new_symbol != node->symbol);
    AstDefine *result = node;
    if (changed) {
        result = newAstDefine(CPI(node), new_symbol, new_expression);
    }
    UNPROTECT(save);
    LEAVE(nsAstDefine);
    return result;
}

static AstMultiDefine *nsAstMultiDefine(AstMultiDefine *node,
                                        VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstMultiDefine);
    bool changed = false;
    AstSymbolList *new_symbols = nsAstSymbolList(node->symbols, context);
    int save = PROTECT(new_symbols);
    changed = changed || (new_symbols != node->symbols);
    AstExpression *new_expression = nsAstExpression(node->expression, context);
    PROTECT(new_expression);
    changed = changed || (new_expression != node->expression);
    AstMultiDefine *result = node;
    if (changed) {
        result = newAstMultiDefine(CPI(node), new_symbols, new_expression);
    }
    UNPROTECT(save);
    LEAVE(nsAstMultiDefine);
    return result;
}

static AstSymbolList *nsAstSymbolList(AstSymbolList *node,
                                      VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSymbolList);
    bool changed = false;
    AstSymbolList *new_next = nsAstSymbolList(node->next, context);
    int save = PROTECT(new_next);
    changed = changed || (new_next != node->next);
    HashSymbol *new_symbol = nsSymbol(node->symbol, context);
    changed = changed || (new_symbol != node->symbol);
    AstSymbolList *result = node;
    if (changed) {
        result = newAstSymbolList(CPI(node), new_symbol, new_next);
    }
    UNPROTECT(save);
    LEAVE(nsAstSymbolList);
    return result;
}

static AstAlias *nsAstAlias(AstAlias *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstAlias);
    bool changed = false;
    AstType *new_type = nsAstType(node->type, context);
    int save = PROTECT(new_type);
    changed = changed || (new_type != node->type);
    HashSymbol *new_name = nsSymbol(node->name, context);
    changed = changed || (new_name != node->name);
    AstAlias *result = node;
    if (changed) {
        result = newAstAlias(CPI(node), new_name, new_type);
    }
    UNPROTECT(save);
    LEAVE(nsAstAlias);
    return result;
}

static AstExprAlias *nsAstExprAlias(AstExprAlias *node,
                                    VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstExprAlias);
    bool changed = false;
    AstExpression *new_value = nsAstExpression(node->value, context);
    int save = PROTECT(new_value);
    changed = changed || (new_value != node->value);
    HashSymbol *new_name = nsSymbol(node->name, context);
    changed = changed || (new_name != node->name);
    AstExprAlias *result = node;
    if (changed) {
        result = newAstExprAlias(CPI(node), new_name, new_value);
    }
    UNPROTECT(save);
    LEAVE(nsAstExprAlias);
    return result;
}

static AstAnnotatedSymbol *nsAstAnnotatedSymbol(AstAnnotatedSymbol *node,
                                                VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstAnnotatedSymbol);
    bool changed = false;
    AstExpression *new_originalImpl =
        nsAstExpression(node->originalImpl, context);
    int save = PROTECT(new_originalImpl);
    changed = changed || (new_originalImpl != node->originalImpl);
    HashSymbol *new_symbol = nsSymbol(node->symbol, context);
    changed = changed || (new_symbol != node->symbol);
    AstAnnotatedSymbol *result = node;
    if (changed) {
        result = newAstAnnotatedSymbol(CPI(node), new_symbol, new_originalImpl);
        result->isLazy = node->isLazy;
    }
    UNPROTECT(save);
    LEAVE(nsAstAnnotatedSymbol);
    return result;
}

static AstDefLazy *nsAstDefLazy(AstDefLazy *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstDefLazy);
    bool changed = false;
    AstAltFunction *new_definition =
        nsAstAltFunction(node->definition, context);
    int save = PROTECT(new_definition);
    changed = changed || (new_definition != node->definition);
    HashSymbol *new_name = nsSymbol(node->name, context);
    changed = changed || (new_name != node->name);
    AstDefLazy *result = node;
    if (changed) {
        result = newAstDefLazy(CPI(node), new_name, new_definition);
    }
    UNPROTECT(save);
    LEAVE(nsAstDefLazy);
    return result;
}

static AstTypeDef *nsAstTypeDef(AstTypeDef *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstTypeDef);
    bool changed = false;
    AstTypeSig *new_typeSig = nsAstTypeSig(node->typeSig, context);
    int save = PROTECT(new_typeSig);
    changed = changed || (new_typeSig != node->typeSig);
    AstTypeBody *new_typeBody = nsAstTypeBody(node->typeBody, context);
    PROTECT(new_typeBody);
    changed = changed || (new_typeBody != node->typeBody);
    AstTypeDef *result = node;
    if (changed) {
        result = newAstTypeDef(CPI(node), new_typeSig, new_typeBody);
    }
    UNPROTECT(save);
    LEAVE(nsAstTypeDef);
    return result;
}

static AstTypeSig *nsAstTypeSig(AstTypeSig *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstTypeSig);
    bool changed = false;
    AstTypeSymbols *new_typeSymbols =
        nsAstTypeSymbols(node->typeSymbols, context);
    int save = PROTECT(new_typeSymbols);
    changed = changed || (new_typeSymbols != node->typeSymbols);
    HashSymbol *new_symbol = nsSymbol(node->symbol, context);
    changed = changed || (new_symbol != node->symbol);
    AstTypeSig *result = node;
    if (changed) {
        result = newAstTypeSig(CPI(node), new_symbol, new_typeSymbols);
    }
    UNPROTECT(save);
    LEAVE(nsAstTypeSig);
    return result;
}

static AstTypeSymbols *nsAstTypeSymbols(AstTypeSymbols *node,
                                        VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstTypeSymbols);
    bool changed = false;
    AstTypeSymbols *new_next = nsAstTypeSymbols(node->next, context);
    int save = PROTECT(new_next);
    changed = changed || (new_next != node->next);
    HashSymbol *new_typeSymbol = nsSymbol(node->typeSymbol, context);
    changed = changed || (new_typeSymbol != node->typeSymbol);
    AstTypeSymbols *result = node;
    if (changed) {
        result = newAstTypeSymbols(CPI(node), new_typeSymbol, new_next);
    }
    UNPROTECT(save);
    LEAVE(nsAstTypeSymbols);
    return result;
}

static AstTypeBody *nsAstTypeBody(AstTypeBody *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstTypeBody);
    bool changed = false;
    AstTypeConstructor *new_typeConstructor =
        nsAstTypeConstructor(node->typeConstructor, context);
    int save = PROTECT(new_typeConstructor);
    changed = changed || (new_typeConstructor != node->typeConstructor);
    AstTypeBody *new_next = nsAstTypeBody(node->next, context);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);
    AstTypeBody *result = node;
    if (changed) {
        result = newAstTypeBody(CPI(node), new_typeConstructor, new_next);
    }
    UNPROTECT(save);
    LEAVE(nsAstTypeBody);
    return result;
}

static AstTypeConstructor *nsAstTypeConstructor(AstTypeConstructor *node,
                                                VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstTypeConstructor);
    bool changed = false;
    AstTypeConstructorArgs *new_args =
        nsAstTypeConstructorArgs(node->args, context);
    int save = PROTECT(new_args);
    changed = changed || (new_args != node->args);
    HashSymbol *new_symbol = nsSymbol(node->symbol, context);
    changed = changed || (new_symbol != node->symbol);
    AstTypeConstructor *result = node;
    if (changed) {
        result = newAstTypeConstructor(CPI(node), new_symbol, new_args);
    }
    UNPROTECT(save);
    LEAVE(nsAstTypeConstructor);
    return result;
}

static AstTypeFunction *nsAstTypeFunction(AstTypeFunction *node,
                                          VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstTypeFunction);
    bool changed = false;
    AstLookUpOrSymbol *new_symbol = nsAstLookUpOrSymbol(node->symbol, context);
    int save = PROTECT(new_symbol);
    changed = changed || (new_symbol != node->symbol);
    AstTypeList *new_typeList = nsAstTypeList(node->typeList, context);
    PROTECT(new_typeList);
    changed = changed || (new_typeList != node->typeList);
    AstTypeFunction *result = node;
    if (changed) {
        result = newAstTypeFunction(CPI(node), new_symbol, new_typeList);
    }
    UNPROTECT(save);
    LEAVE(nsAstTypeFunction);
    return result;
}

static AstTypeList *nsAstTypeList(AstTypeList *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstTypeList);
    bool changed = false;
    AstType *new_type = nsAstType(node->type, context);
    int save = PROTECT(new_type);
    changed = changed || (new_type != node->type);
    AstTypeList *new_next = nsAstTypeList(node->next, context);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);
    AstTypeList *result = node;
    if (changed) {
        result = newAstTypeList(CPI(node), new_type, new_next);
    }
    UNPROTECT(save);
    LEAVE(nsAstTypeList);
    return result;
}

static AstTypeMap *nsAstTypeMap(AstTypeMap *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstTypeMap);
    bool changed = false;
    AstType *new_type = nsAstType(node->type, context);
    int save = PROTECT(new_type);
    changed = changed || (new_type != node->type);
    AstTypeMap *new_next = nsAstTypeMap(node->next, context);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);
    AstTypeMap *result = node;
    if (changed) {
        result = newAstTypeMap(CPI(node), node->key, new_type, new_next);
    }
    UNPROTECT(save);
    LEAVE(nsAstTypeMap);
    return result;
}

static AstType *nsAstType(AstType *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstType);
    bool changed = false;
    AstTypeClause *new_typeClause = nsAstTypeClause(node->typeClause, context);
    int save = PROTECT(new_typeClause);
    changed = changed || (new_typeClause != node->typeClause);
    AstType *new_next = nsAstType(node->next, context);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);
    AstType *result = node;
    if (changed) {
        result = newAstType(CPI(node), new_typeClause, new_next);
    }
    UNPROTECT(save);
    LEAVE(nsAstType);
    return result;
}

static AstCompositeFunction *nsAstCompositeFunction(AstCompositeFunction *node,
                                                    VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstCompositeFunction);
    bool changed = false;
    AstFunction *new_function = nsAstFunction(node->function, context);
    int save = PROTECT(new_function);
    changed = changed || (new_function != node->function);
    AstCompositeFunction *new_next =
        nsAstCompositeFunction(node->next, context);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);
    AstCompositeFunction *result = node;
    if (changed) {
        result = newAstCompositeFunction(CPI(node), new_function, new_next);
        result->unsafe = node->unsafe;
    }
    UNPROTECT(save);
    LEAVE(nsAstCompositeFunction);
    return result;
}

static AstFunction *nsAstFunction(AstFunction *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstFunction);
    bool changed = false;
    AstFargList *new_argList = nsAstFargList(node->argList, context);
    int save = PROTECT(new_argList);
    changed = changed || (new_argList != node->argList);
    AstNest *new_nest = nsAstNest(node->nest, context);
    PROTECT(new_nest);
    changed = changed || (new_nest != node->nest);
    AstFunction *result = node;
    if (changed) {
        result = newAstFunction(CPI(node), new_argList, new_nest);
    }
    UNPROTECT(save);
    LEAVE(nsAstFunction);
    return result;
}

static AstFargList *nsAstFargList(AstFargList *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstFargList);
    bool changed = false;
    AstFarg *new_arg = nsAstFarg(node->arg, context);
    int save = PROTECT(new_arg);
    changed = changed || (new_arg != node->arg);
    AstFargList *new_next = nsAstFargList(node->next, context);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);
    AstFargList *result = node;
    if (changed) {
        result = newAstFargList(CPI(node), new_arg, new_next);
    }
    UNPROTECT(save);
    LEAVE(nsAstFargList);
    return result;
}

static AstTaggedArgList *nsAstTaggedArgList(AstTaggedArgList *node,
                                            VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstTaggedArgList);
    bool changed = false;
    AstFarg *new_arg = nsAstFarg(node->arg, context);
    int save = PROTECT(new_arg);
    changed = changed || (new_arg != node->arg);
    AstTaggedArgList *new_next = nsAstTaggedArgList(node->next, context);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);
    AstTaggedArgList *result = node;
    if (changed) {
        result = newAstTaggedArgList(CPI(node), node->tag, new_arg, new_next);
    }
    UNPROTECT(save);
    LEAVE(nsAstTaggedArgList);
    return result;
}

static AstAltArgs *nsAstAltArgs(AstAltArgs *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstAltArgs);
    bool changed = false;
    AstFargList *new_argList = nsAstFargList(node->argList, context);
    int save = PROTECT(new_argList);
    changed = changed || (new_argList != node->argList);
    AstAltArgs *new_next = nsAstAltArgs(node->next, context);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);
    AstAltArgs *result = node;
    if (changed) {
        result = newAstAltArgs(CPI(node), new_argList, new_next);
    }
    UNPROTECT(save);
    LEAVE(nsAstAltArgs);
    return result;
}

static AstAltFunction *nsAstAltFunction(AstAltFunction *node,
                                        VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstAltFunction);
    bool changed = false;
    AstAltArgs *new_altArgs = nsAstAltArgs(node->altArgs, context);
    int save = PROTECT(new_altArgs);
    changed = changed || (new_altArgs != node->altArgs);
    AstNest *new_nest = nsAstNest(node->nest, context);
    PROTECT(new_nest);
    changed = changed || (new_nest != node->nest);
    AstAltFunction *result = node;
    if (changed) {
        result = newAstAltFunction(CPI(node), new_altArgs, new_nest);
    }
    UNPROTECT(save);
    LEAVE(nsAstAltFunction);
    return result;
}

static AstUnpack *nsAstUnpack(AstUnpack *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstUnpack);
    bool changed = false;
    AstLookUpOrSymbol *new_symbol = nsAstLookUpOrSymbol(node->symbol, context);
    int save = PROTECT(new_symbol);
    changed = changed || (new_symbol != node->symbol);
    AstFargList *new_argList = nsAstFargList(node->argList, context);
    PROTECT(new_argList);
    changed = changed || (new_argList != node->argList);
    AstUnpack *result = node;
    if (changed) {
        result = newAstUnpack(CPI(node), new_symbol, new_argList);
    }
    UNPROTECT(save);
    LEAVE(nsAstUnpack);
    return result;
}

static AstUnpackStruct *nsAstUnpackStruct(AstUnpackStruct *node,
                                          VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstUnpackStruct);
    bool changed = false;
    AstLookUpOrSymbol *new_symbol = nsAstLookUpOrSymbol(node->symbol, context);
    int save = PROTECT(new_symbol);
    changed = changed || (new_symbol != node->symbol);
    AstTaggedArgList *new_argList = nsAstTaggedArgList(node->argList, context);
    PROTECT(new_argList);
    changed = changed || (new_argList != node->argList);
    AstUnpackStruct *result = node;
    if (changed) {
        result = newAstUnpackStruct(CPI(node), new_symbol, new_argList);
    }
    UNPROTECT(save);
    LEAVE(nsAstUnpackStruct);
    return result;
}

static AstNamedArg *nsAstNamedArg(AstNamedArg *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstNamedArg);
    bool changed = false;
    AstFarg *new_arg = nsAstFarg(node->arg, context);
    int save = PROTECT(new_arg);
    changed = changed || (new_arg != node->arg);
    HashSymbol *new_name = nsSymbol(node->name, context);
    changed = changed || (new_name != node->name);
    AstNamedArg *result = node;
    if (changed) {
        result = newAstNamedArg(CPI(node), new_name, new_arg);
    }
    UNPROTECT(save);
    LEAVE(nsAstNamedArg);
    return result;
}

static AstFunCall *nsAstFunCall(AstFunCall *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstFunCall);
    bool changed = false;
    AstExpression *new_function = nsAstExpression(node->function, context);
    int save = PROTECT(new_function);
    changed = changed || (new_function != node->function);
    AstExpressions *new_arguments = nsAstExpressions(node->arguments, context);
    PROTECT(new_arguments);
    changed = changed || (new_arguments != node->arguments);
    AstFunCall *result = node;
    if (changed) {
        result = newAstFunCall(CPI(node), new_function, new_arguments);
        result->isBuiltin = node->isBuiltin;
    }
    UNPROTECT(save);
    LEAVE(nsAstFunCall);
    return result;
}

static AstExpressions *nsAstExpressions(AstExpressions *node,
                                        VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstExpressions);
    bool changed = false;
    AstExpression *new_expression = nsAstExpression(node->expression, context);
    int save = PROTECT(new_expression);
    changed = changed || (new_expression != node->expression);
    AstExpressions *new_next = nsAstExpressions(node->next, context);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);
    AstExpressions *result = node;
    if (changed) {
        result = newAstExpressions(CPI(node), new_expression, new_next);
    }
    UNPROTECT(save);
    LEAVE(nsAstExpressions);
    return result;
}

static HashSymbol *nsAstLookUpSymbol(AstLookUpSymbol *node,
                                     VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstLookUpSymbol);
    context = getNsReplacements(context, node->nsId);
    return nsSymbol(node->symbol, context);
}

static AstExpression *nsAstLookUp(AstLookUp *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstLookUp);
    context = getNsReplacements(context, node->nsId);
    return nsAstExpression(node->expression, context);
}

static AstIff *nsAstIff(AstIff *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstIff);
    bool changed = false;
    AstExpression *new_test = nsAstExpression(node->test, context);
    int save = PROTECT(new_test);
    changed = changed || (new_test != node->test);
    AstNest *new_consequent = nsAstNest(node->consequent, context);
    PROTECT(new_consequent);
    changed = changed || (new_consequent != node->consequent);
    AstNest *new_alternative = nsAstNest(node->alternative, context);
    PROTECT(new_alternative);
    changed = changed || (new_alternative != node->alternative);
    AstIff *result = node;
    if (changed) {
        result =
            newAstIff(CPI(node), new_test, new_consequent, new_alternative);
    }
    UNPROTECT(save);
    LEAVE(nsAstIff);
    return result;
}

static AstPrint *nsAstPrint(AstPrint *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstPrint);
    bool changed = false;
    AstExpression *new_exp = nsAstExpression(node->exp, context);
    int save = PROTECT(new_exp);
    changed = changed || (new_exp != node->exp);
    AstPrint *result = node;
    if (changed) {
        result = newAstPrint(CPI(node), new_exp);
    }
    UNPROTECT(save);
    LEAVE(nsAstPrint);
    return result;
}

static AstTypeOf *nsAstTypeOf(AstTypeOf *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstTypeOf);
    bool changed = false;
    AstExpression *new_exp = nsAstExpression(node->exp, context);
    int save = PROTECT(new_exp);
    changed = changed || (new_exp != node->exp);
    AstTypeOf *result = node;
    if (changed) {
        result = newAstTypeOf(CPI(node), new_exp);
    }
    UNPROTECT(save);
    LEAVE(nsAstTypeOf);
    return result;
}

static AstStruct *nsAstStruct(AstStruct *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstStruct);
    bool changed = false;
    AstLookUpOrSymbol *new_symbol = nsAstLookUpOrSymbol(node->symbol, context);
    int save = PROTECT(new_symbol);
    changed = changed || (new_symbol != node->symbol);
    AstTaggedExpressions *new_expressions =
        nsAstTaggedExpressions(node->expressions, context);
    PROTECT(new_expressions);
    changed = changed || (new_expressions != node->expressions);
    AstStruct *result = node;
    if (changed) {
        result = newAstStruct(CPI(node), new_symbol, new_expressions);
    }
    UNPROTECT(save);
    LEAVE(nsAstStruct);
    return result;
}

static AstTaggedExpressions *nsAstTaggedExpressions(AstTaggedExpressions *node,
                                                    VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstTaggedExpressions);
    bool changed = false;
    AstExpression *new_expression = nsAstExpression(node->expression, context);
    int save = PROTECT(new_expression);
    changed = changed || (new_expression != node->expression);
    AstTaggedExpressions *new_next =
        nsAstTaggedExpressions(node->next, context);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);
    AstTaggedExpressions *result = node;
    if (changed) {
        result = newAstTaggedExpressions(CPI(node), node->tag, new_expression,
                                         new_next);
    }
    UNPROTECT(save);
    LEAVE(nsAstTaggedExpressions);
    return result;
}

static AstTypeConstructorArgs *
nsAstTypeConstructorArgs(AstTypeConstructorArgs *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstTypeConstructorArgs);
    int save = STARTPROTECT();
    AstTypeConstructorArgs *result = node;
    switch (node->type) {
    case AST_TYPECONSTRUCTORARGS_TYPE_LIST: {
        AstTypeList *variant = getAstTypeConstructorArgs_List(node);
        AstTypeList *new_variant = nsAstTypeList(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstTypeConstructorArgs_List(CPI(node), new_variant);
        }
        break;
    }
    case AST_TYPECONSTRUCTORARGS_TYPE_MAP: {
        AstTypeMap *variant = getAstTypeConstructorArgs_Map(node);
        AstTypeMap *new_variant = nsAstTypeMap(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstTypeConstructorArgs_Map(CPI(node), new_variant);
        }
        break;
    }
    default:
        cant_happen("unrecognized AstTypeConstructorArgs type %d", node->type);
    }
    UNPROTECT(save);
    LEAVE(nsAstTypeConstructorArgs);
    return result;
}

static AstLookUpOrSymbol *nsAstLookUpOrSymbol(AstLookUpOrSymbol *node,
                                              VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstLookUpOrSymbol);
    int save = STARTPROTECT();
    AstLookUpOrSymbol *result = node;
    switch (node->type) {
    case AST_LOOKUPORSYMBOL_TYPE_SYMBOL: {
        HashSymbol *variant = getAstLookUpOrSymbol_Symbol(node);
        HashSymbol *new_variant = nsSymbol(variant, context);
        if (new_variant != variant) {
            result = newAstLookUpOrSymbol_Symbol(CPI(node), new_variant);
        }
        break;
    }
    case AST_LOOKUPORSYMBOL_TYPE_LOOKUP: {
        AstLookUpSymbol *variant = getAstLookUpOrSymbol_LookUp(node);
        HashSymbol *new_variant = nsAstLookUpSymbol(variant, context);
        result = newAstLookUpOrSymbol_Symbol(CPI(node), new_variant);
        break;
    }
    default:
        cant_happen("unrecognized AstLookUpOrSymbol type %d", node->type);
    }
    UNPROTECT(save);
    LEAVE(nsAstLookUpOrSymbol);
    return result;
}

static AstSyntaxDecl *nsAstSyntaxDecl(AstSyntaxDecl *node,
                                      VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxDecl);
    bool changed = false;
    AstSyntaxAlternatives *new_alternatives =
        nsAstSyntaxAlternatives(node->alternatives, context);
    int save = PROTECT(new_alternatives);
    changed = changed || (new_alternatives != node->alternatives);
    AstSyntaxDecl *result = node;
    if (changed) {
        result = newAstSyntaxDecl(CPI(node), node->declarationId,
                                  node->ruleName, new_alternatives);
        result->surfaceHead = node->surfaceHead;
        result->parameters = node->parameters;
        result->entryKind = node->entryKind;
        result->resultKind = node->resultKind;
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxDecl);
    return result;
}

static AstSyntaxAlternatives *
nsAstSyntaxAlternatives(AstSyntaxAlternatives *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxAlternatives);
    bool changed = false;
    AstSyntaxAlternatives *result = newAstSyntaxAlternatives();
    int save = PROTECT(result);
    for (Index i = 0; i < sizeAstSyntaxAlternatives(node); ++i) {
        AstSyntaxAlternative *alternative = getAstSyntaxAlternatives(node, i);
        AstSyntaxAlternative *new_alternative =
            nsAstSyntaxAlternative(alternative, context);
        int save2 = PROTECT(new_alternative);
        changed = changed || (new_alternative != alternative);
        pushAstSyntaxAlternatives(result, new_alternative);
        UNPROTECT(save2);
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxAlternatives);
    return changed ? result : node;
}

static AstSyntaxAlternative *nsAstSyntaxAlternative(AstSyntaxAlternative *node,
                                                    VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxAlternative);
    bool changed = false;
    AstSyntaxTemplate *new_template =
        nsAstSyntaxTemplate(node->template, context);
    int save = PROTECT(new_template);
    changed = changed || (new_template != node->template);
    AstSyntaxAlternative *result = node;
    if (changed) {
        result = newAstSyntaxAlternative(CPI(node), node->patternItems,
                                         new_template);
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxAlternative);
    return result;
}

static AstSyntaxTemplate *nsAstSyntaxTemplate(AstSyntaxTemplate *node,
                                              VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxTemplate);
    bool changed = false;
    AstSyntaxTemplateExpr *new_expr =
        nsAstSyntaxTemplateExpr(node->expr, context);
    int save = PROTECT(new_expr);
    changed = changed || (new_expr != node->expr);
    AstSyntaxTemplateDefinition *new_definition =
        nsAstSyntaxTemplateDefinition(node->definition, context);
    PROTECT(new_definition);
    changed = changed || (new_definition != node->definition);
    AstSyntaxTemplate *result = node;
    if (changed) {
        result = newAstSyntaxTemplate(CPI(node), node->resultKind);
        result->expr = new_expr;
        result->definition = new_definition;
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxTemplate);
    return result;
}

static AstSyntaxTemplateDefinitions *
nsAstSyntaxTemplateDefinitions(AstSyntaxTemplateDefinitions *node,
                               VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxTemplateDefinitions);
    bool changed = false;
    AstSyntaxTemplateDefinition *new_definition =
        nsAstSyntaxTemplateDefinition(node->definition, context);
    int save = PROTECT(new_definition);
    changed = changed || (new_definition != node->definition);
    AstSyntaxTemplateDefinitions *new_next =
        nsAstSyntaxTemplateDefinitions(node->next, context);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);
    AstSyntaxTemplateDefinitions *result = node;
    if (changed) {
        result = newAstSyntaxTemplateDefinitions(CPI(node), new_definition);
        result->next = new_next;
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxTemplateDefinitions);
    return result;
}

static AstSyntaxTemplateDefinition *
nsAstSyntaxTemplateDefinition(AstSyntaxTemplateDefinition *node,
                              VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxTemplateDefinition);
    int save = STARTPROTECT();
    AstSyntaxTemplateDefinition *result = node;
    switch (node->type) {
    case AST_SYNTAXTEMPLATEDEFINITION_TYPE_DEFINE: {
        AstSyntaxTemplateDefine *variant =
            getAstSyntaxTemplateDefinition_Define(node);
        bool changed = false;
        AstSyntaxTemplateBinder *new_symbol =
            nsAstSyntaxTemplateBinder(variant->symbol, context);
        PROTECT(new_symbol);
        changed = changed || (new_symbol != variant->symbol);
        AstSyntaxTemplateExpr *new_expression =
            nsAstSyntaxTemplateExpr(variant->expression, context);
        PROTECT(new_expression);
        changed = changed || (new_expression != variant->expression);
        if (changed) {
            AstSyntaxTemplateDefine *new_variant = newAstSyntaxTemplateDefine(
                CPI(variant), new_symbol, new_expression);
            PROTECT(new_variant);
            result =
                newAstSyntaxTemplateDefinition_Define(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEDEFINITION_TYPE_MULTI: {
        AstSyntaxTemplateMultiDefine *variant =
            getAstSyntaxTemplateDefinition_Multi(node);
        bool changed = false;
        AstSyntaxTemplateBinders *new_symbols =
            nsAstSyntaxTemplateBinders(variant->symbols, context);
        PROTECT(new_symbols);
        changed = changed || (new_symbols != variant->symbols);
        AstSyntaxTemplateExpr *new_expression =
            nsAstSyntaxTemplateExpr(variant->expression, context);
        PROTECT(new_expression);
        changed = changed || (new_expression != variant->expression);
        if (changed) {
            AstSyntaxTemplateMultiDefine *new_variant =
                newAstSyntaxTemplateMultiDefine(CPI(variant), new_symbols,
                                                new_expression);
            PROTECT(new_variant);
            result =
                newAstSyntaxTemplateDefinition_Multi(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEDEFINITION_TYPE_LAZY: {
        AstSyntaxTemplateDefLazy *variant =
            getAstSyntaxTemplateDefinition_Lazy(node);
        bool changed = false;
        AstSyntaxTemplateBinder *new_name =
            nsAstSyntaxTemplateBinder(variant->name, context);
        PROTECT(new_name);
        changed = changed || (new_name != variant->name);
        AstSyntaxTemplateAltFunction *new_definition =
            nsAstSyntaxTemplateAltFunction(variant->definition, context);
        PROTECT(new_definition);
        changed = changed || (new_definition != variant->definition);
        if (changed) {
            AstSyntaxTemplateDefLazy *new_variant = newAstSyntaxTemplateDefLazy(
                CPI(variant), new_name, new_definition);
            PROTECT(new_variant);
            result =
                newAstSyntaxTemplateDefinition_Lazy(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEDEFINITION_TYPE_ALIAS: {
        AstSyntaxTemplateAlias *variant =
            getAstSyntaxTemplateDefinition_Alias(node);
        bool changed = false;
        AstSyntaxTemplateBinder *new_name =
            nsAstSyntaxTemplateBinder(variant->name, context);
        PROTECT(new_name);
        changed = changed || (new_name != variant->name);
        AstType *new_type = nsAstType(variant->type, context);
        PROTECT(new_type);
        changed = changed || (new_type != variant->type);
        if (changed) {
            AstSyntaxTemplateAlias *new_variant =
                newAstSyntaxTemplateAlias(CPI(variant), new_name, new_type);
            PROTECT(new_variant);
            result =
                newAstSyntaxTemplateDefinition_Alias(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEDEFINITION_TYPE_TYPEDEF: {
        AstSyntaxTemplateTypeDef *variant =
            getAstSyntaxTemplateDefinition_TypeDef(node);
        bool changed = false;
        AstTypeSig *new_typeSig = nsAstTypeSig(variant->typeSig, context);
        PROTECT(new_typeSig);
        changed = changed || (new_typeSig != variant->typeSig);
        AstTypeBody *new_typeBody = nsAstTypeBody(variant->typeBody, context);
        PROTECT(new_typeBody);
        changed = changed || (new_typeBody != variant->typeBody);
        if (changed) {
            AstSyntaxTemplateTypeDef *new_variant = newAstSyntaxTemplateTypeDef(
                CPI(variant), new_typeSig, new_typeBody);
            PROTECT(new_variant);
            result =
                newAstSyntaxTemplateDefinition_TypeDef(CPI(node), new_variant);
        }
        break;
    }
    default:
        cant_happen("unrecognized %s",
                    astSyntaxTemplateDefinitionTypeName(node->type));
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxTemplateDefinition);
    return result;
}

static AstSyntaxTemplateNameRef *
nsAstSyntaxTemplateNameRef(AstSyntaxTemplateNameRef *node,
                           VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxTemplateNameRef);
    int save = STARTPROTECT();
    AstSyntaxTemplateNameRef *result = node;
    switch (node->type) {
    case AST_SYNTAXTEMPLATENAMEREF_TYPE_LITERAL: {
        AstSyntaxLiteralRef *variant =
            getAstSyntaxTemplateNameRef_Literal(node);
        HashSymbol *resolved = variant->resolvedName != NULL
                                   ? variant->resolvedName
                                   : variant->writtenName;
        HashSymbol *new_resolved = nsSymbol(resolved, context);
        if (new_resolved != resolved) {
            AstSyntaxLiteralRef *new_variant =
                newAstSyntaxLiteralRef(CPI(variant), variant->writtenName);
            PROTECT(new_variant);
            new_variant->resolvedName = new_resolved;
            result =
                newAstSyntaxTemplateNameRef_Literal(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATENAMEREF_TYPE_INTRODUCED:
    case AST_SYNTAXTEMPLATENAMEREF_TYPE_UNQUOTE:
        break;
    default:
        cant_happen("unrecognized %s",
                    astSyntaxTemplateNameRefTypeName(node->type));
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxTemplateNameRef);
    return result;
}

static AstSyntaxTemplateBinder *
nsAstSyntaxTemplateBinder(AstSyntaxTemplateBinder *node,
                          VisitorContext context) {
    (void)context;
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxTemplateBinder);
    LEAVE(nsAstSyntaxTemplateBinder);
    return node;
}

static AstSyntaxTemplateBinders *
nsAstSyntaxTemplateBinders(AstSyntaxTemplateBinders *node,
                           VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxTemplateBinders);
    bool changed = false;
    AstSyntaxTemplateBinders *result = newAstSyntaxTemplateBinders();
    int save = PROTECT(result);
    for (Index i = 0; i < sizeAstSyntaxTemplateBinders(node); ++i) {
        AstSyntaxTemplateBinder *binder = getAstSyntaxTemplateBinders(node, i);
        AstSyntaxTemplateBinder *new_binder =
            nsAstSyntaxTemplateBinder(binder, context);
        int save2 = PROTECT(new_binder);
        changed = changed || (new_binder != binder);
        pushAstSyntaxTemplateBinders(result, new_binder);
        UNPROTECT(save2);
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxTemplateBinders);
    return changed ? result : node;
}

static AstSyntaxTemplateExprs *
nsAstSyntaxTemplateExprs(AstSyntaxTemplateExprs *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxTemplateExprs);
    bool changed = false;
    AstSyntaxTemplateExprs *result = newAstSyntaxTemplateExprs();
    int save = PROTECT(result);
    for (Index i = 0; i < sizeAstSyntaxTemplateExprs(node); ++i) {
        AstSyntaxTemplateExpr *expression = getAstSyntaxTemplateExprs(node, i);
        AstSyntaxTemplateExpr *new_expression =
            nsAstSyntaxTemplateExpr(expression, context);
        int save2 = PROTECT(new_expression);
        changed = changed || (new_expression != expression);
        pushAstSyntaxTemplateExprs(result, new_expression);
        UNPROTECT(save2);
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxTemplateExprs);
    return changed ? result : node;
}

static AstSyntaxTemplateNest *
nsAstSyntaxTemplateNest(AstSyntaxTemplateNest *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxTemplateNest);
    bool changed = false;
    AstSyntaxTemplateDefinitions *new_definitions =
        nsAstSyntaxTemplateDefinitions(node->definitions, context);
    int save = PROTECT(new_definitions);
    changed = changed || (new_definitions != node->definitions);
    AstSyntaxTemplateExprs *new_expressions =
        nsAstSyntaxTemplateExprs(node->expressions, context);
    PROTECT(new_expressions);
    changed = changed || (new_expressions != node->expressions);
    AstSyntaxTemplateNest *result = node;
    if (changed) {
        result = newAstSyntaxTemplateNest(CPI(node), new_definitions,
                                          new_expressions);
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxTemplateNest);
    return result;
}

static AstSyntaxTemplateFunction *
nsAstSyntaxTemplateFunction(AstSyntaxTemplateFunction *node,
                            VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxTemplateFunction);
    bool changed = false;
    AstSyntaxTemplateAltFunction *new_function =
        nsAstSyntaxTemplateAltFunction(node->function, context);
    int save = PROTECT(new_function);
    changed = changed || (new_function != node->function);
    AstSyntaxTemplateFunction *new_next =
        nsAstSyntaxTemplateFunction(node->next, context);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);
    AstSyntaxTemplateFunction *result = node;
    if (changed) {
        result = newAstSyntaxTemplateFunction(CPI(node), new_function);
        result->next = new_next;
        result->unsafe = node->unsafe;
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxTemplateFunction);
    return result;
}

static AstSyntaxTemplateAltFunction *
nsAstSyntaxTemplateAltFunction(AstSyntaxTemplateAltFunction *node,
                               VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxTemplateAltFunction);
    bool changed = false;
    AstSyntaxTemplateAltArgs *new_altArgs =
        nsAstSyntaxTemplateAltArgs(node->altArgs, context);
    int save = PROTECT(new_altArgs);
    changed = changed || (new_altArgs != node->altArgs);
    AstSyntaxTemplateNest *new_nest =
        nsAstSyntaxTemplateNest(node->nest, context);
    PROTECT(new_nest);
    changed = changed || (new_nest != node->nest);
    AstSyntaxTemplateAltFunction *result = node;
    if (changed) {
        result =
            newAstSyntaxTemplateAltFunction(CPI(node), new_altArgs, new_nest);
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxTemplateAltFunction);
    return result;
}

static AstSyntaxTemplateAltArgs *
nsAstSyntaxTemplateAltArgs(AstSyntaxTemplateAltArgs *node,
                           VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxTemplateAltArgs);
    bool changed = false;
    AstSyntaxTemplateFargList *new_argList =
        nsAstSyntaxTemplateFargList(node->argList, context);
    int save = PROTECT(new_argList);
    changed = changed || (new_argList != node->argList);
    AstSyntaxTemplateAltArgs *new_next =
        nsAstSyntaxTemplateAltArgs(node->next, context);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);
    AstSyntaxTemplateAltArgs *result = node;
    if (changed) {
        result = newAstSyntaxTemplateAltArgs(CPI(node), new_argList);
        result->next = new_next;
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxTemplateAltArgs);
    return result;
}

static AstSyntaxTemplateFargList *
nsAstSyntaxTemplateFargList(AstSyntaxTemplateFargList *node,
                            VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxTemplateFargList);
    bool changed = false;
    AstSyntaxTemplateFargList *result = newAstSyntaxTemplateFargList();
    int save = PROTECT(result);
    for (Index i = 0; i < sizeAstSyntaxTemplateFargList(node); ++i) {
        AstSyntaxTemplateFarg *arg = getAstSyntaxTemplateFargList(node, i);
        AstSyntaxTemplateFarg *new_arg = nsAstSyntaxTemplateFarg(arg, context);
        int save2 = PROTECT(new_arg);
        changed = changed || (new_arg != arg);
        pushAstSyntaxTemplateFargList(result, new_arg);
        UNPROTECT(save2);
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxTemplateFargList);
    return changed ? result : node;
}

static AstSyntaxTemplateTaggedArgs *
nsAstSyntaxTemplateTaggedArgs(AstSyntaxTemplateTaggedArgs *node,
                              VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxTemplateTaggedArgs);
    bool changed = false;
    AstSyntaxTemplateTaggedArgs *result = newAstSyntaxTemplateTaggedArgs();
    int save = PROTECT(result);
    for (Index i = 0; i < sizeAstSyntaxTemplateTaggedArgs(node); ++i) {
        AstSyntaxTemplateTaggedArg *arg =
            getAstSyntaxTemplateTaggedArgs(node, i);
        AstSyntaxTemplateFarg *new_arg =
            nsAstSyntaxTemplateFarg(arg->arg, context);
        int save2 = PROTECT(new_arg);
        changed = changed || (new_arg != arg->arg);
        AstSyntaxTemplateTaggedArg *new_tagged = arg;
        if (new_arg != arg->arg) {
            new_tagged =
                newAstSyntaxTemplateTaggedArg(CPI(arg), arg->tag, new_arg);
        }
        PROTECT(new_tagged);
        pushAstSyntaxTemplateTaggedArgs(result, new_tagged);
        UNPROTECT(save2);
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxTemplateTaggedArgs);
    return changed ? result : node;
}

static AstSyntaxTemplateTaggedExpressions *
nsAstSyntaxTemplateTaggedExpressions(AstSyntaxTemplateTaggedExpressions *node,
                                     VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxTemplateTaggedExpressions);
    bool changed = false;
    AstSyntaxTemplateTaggedExpressions *result =
        newAstSyntaxTemplateTaggedExpressions();
    int save = PROTECT(result);
    for (Index i = 0; i < sizeAstSyntaxTemplateTaggedExpressions(node); ++i) {
        AstSyntaxTemplateTaggedExpression *expression =
            getAstSyntaxTemplateTaggedExpressions(node, i);
        AstSyntaxTemplateExpr *new_expression =
            nsAstSyntaxTemplateExpr(expression->expression, context);
        int save2 = PROTECT(new_expression);
        changed = changed || (new_expression != expression->expression);
        AstSyntaxTemplateTaggedExpression *new_tagged = expression;
        if (new_expression != expression->expression) {
            new_tagged = newAstSyntaxTemplateTaggedExpression(
                CPI(expression), expression->tag, new_expression);
        }
        PROTECT(new_tagged);
        pushAstSyntaxTemplateTaggedExpressions(result, new_tagged);
        UNPROTECT(save2);
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxTemplateTaggedExpressions);
    return changed ? result : node;
}

static AstSyntaxTemplateFarg *
nsAstSyntaxTemplateFarg(AstSyntaxTemplateFarg *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxTemplateFarg);
    int save = STARTPROTECT();
    AstSyntaxTemplateFarg *result = node;
    switch (node->type) {
    case AST_SYNTAXTEMPLATEFARG_TYPE_WILDCARD:
    case AST_SYNTAXTEMPLATEFARG_TYPE_NUMBER:
    case AST_SYNTAXTEMPLATEFARG_TYPE_CHARACTER:
        break;
    case AST_SYNTAXTEMPLATEFARG_TYPE_BINDER: {
        AstSyntaxTemplateBinder *variant =
            getAstSyntaxTemplateFarg_Binder(node);
        AstSyntaxTemplateBinder *new_variant =
            nsAstSyntaxTemplateBinder(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstSyntaxTemplateFarg_Binder(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEFARG_TYPE_LOOKUP: {
        AstLookUpSymbol *variant = getAstSyntaxTemplateFarg_LookUp(node);
        HashSymbol *new_symbol = nsAstLookUpSymbol(variant, context);
        if (new_symbol != variant->symbol) {
            AstLookUpSymbol *new_variant = newAstLookUpSymbol(
                CPI(variant), variant->nsId, variant->nsSymbol, new_symbol);
            PROTECT(new_variant);
            result = newAstSyntaxTemplateFarg_LookUp(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEFARG_TYPE_NAMED: {
        AstSyntaxTemplateNamedArg *variant =
            getAstSyntaxTemplateFarg_Named(node);
        bool changed = false;
        HashSymbol *new_name = nsSymbol(variant->name, context);
        changed = changed || (new_name != variant->name);
        AstSyntaxTemplateFarg *new_arg =
            nsAstSyntaxTemplateFarg(variant->arg, context);
        PROTECT(new_arg);
        changed = changed || (new_arg != variant->arg);
        if (changed) {
            AstSyntaxTemplateNamedArg *new_variant =
                newAstSyntaxTemplateNamedArg(CPI(variant), new_name, new_arg);
            PROTECT(new_variant);
            result = newAstSyntaxTemplateFarg_Named(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEFARG_TYPE_UNPACK: {
        AstSyntaxTemplateUnpack *variant =
            getAstSyntaxTemplateFarg_Unpack(node);
        bool changed = false;
        AstLookUpOrSymbol *new_symbol =
            nsAstLookUpOrSymbol(variant->symbol, context);
        PROTECT(new_symbol);
        changed = changed || (new_symbol != variant->symbol);
        AstSyntaxTemplateFargList *new_argList =
            nsAstSyntaxTemplateFargList(variant->argList, context);
        PROTECT(new_argList);
        changed = changed || (new_argList != variant->argList);
        if (changed) {
            AstSyntaxTemplateUnpack *new_variant = newAstSyntaxTemplateUnpack(
                CPI(variant), new_symbol, new_argList);
            PROTECT(new_variant);
            result = newAstSyntaxTemplateFarg_Unpack(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEFARG_TYPE_UNPACKSTRUCT: {
        AstSyntaxTemplateUnpackStruct *variant =
            getAstSyntaxTemplateFarg_UnpackStruct(node);
        bool changed = false;
        AstLookUpOrSymbol *new_symbol =
            nsAstLookUpOrSymbol(variant->symbol, context);
        PROTECT(new_symbol);
        changed = changed || (new_symbol != variant->symbol);
        AstSyntaxTemplateTaggedArgs *new_argList =
            nsAstSyntaxTemplateTaggedArgs(variant->argList, context);
        PROTECT(new_argList);
        changed = changed || (new_argList != variant->argList);
        if (changed) {
            AstSyntaxTemplateUnpackStruct *new_variant =
                newAstSyntaxTemplateUnpackStruct(CPI(variant), new_symbol,
                                                 new_argList);
            PROTECT(new_variant);
            result =
                newAstSyntaxTemplateFarg_UnpackStruct(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEFARG_TYPE_TUPLE: {
        AstSyntaxTemplateFargList *variant =
            getAstSyntaxTemplateFarg_Tuple(node);
        AstSyntaxTemplateFargList *new_variant =
            nsAstSyntaxTemplateFargList(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstSyntaxTemplateFarg_Tuple(CPI(node), new_variant);
        }
        break;
    }
    default:
        cant_happen("unrecognized %s",
                    astSyntaxTemplateFargTypeName(node->type));
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxTemplateFarg);
    return result;
}

static AstSyntaxTemplateExpr *
nsAstSyntaxTemplateExpr(AstSyntaxTemplateExpr *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxTemplateExpr);
    int save = STARTPROTECT();
    AstSyntaxTemplateExpr *result = node;
    switch (node->type) {
    case AST_SYNTAXTEMPLATEEXPR_TYPE_BACK:
    case AST_SYNTAXTEMPLATEEXPR_TYPE_WILDCARD:
    case AST_SYNTAXTEMPLATEEXPR_TYPE_NUMBER:
    case AST_SYNTAXTEMPLATEEXPR_TYPE_CHARACTER:
        break;
    case AST_SYNTAXTEMPLATEEXPR_TYPE_NAMEREF: {
        AstSyntaxTemplateNameRef *variant =
            getAstSyntaxTemplateExpr_NameRef(node);
        AstSyntaxTemplateNameRef *new_variant =
            nsAstSyntaxTemplateNameRef(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstSyntaxTemplateExpr_NameRef(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEEXPR_TYPE_FUNCALL: {
        AstSyntaxTemplateFunCall *variant =
            getAstSyntaxTemplateExpr_FunCall(node);
        bool changed = false;
        AstSyntaxTemplateExpr *new_function =
            nsAstSyntaxTemplateExpr(variant->function, context);
        PROTECT(new_function);
        changed = changed || (new_function != variant->function);
        AstSyntaxTemplateExprs *new_arguments =
            nsAstSyntaxTemplateExprs(variant->arguments, context);
        PROTECT(new_arguments);
        changed = changed || (new_arguments != variant->arguments);
        if (changed) {
            AstSyntaxTemplateFunCall *new_variant = newAstSyntaxTemplateFunCall(
                CPI(variant), new_function, new_arguments);
            PROTECT(new_variant);
            result = newAstSyntaxTemplateExpr_FunCall(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEEXPR_TYPE_LOOKUP: {
        AstSyntaxTemplateLookUp *variant =
            getAstSyntaxTemplateExpr_LookUp(node);
        VisitorContext lookupContext =
            getNsReplacements(context, variant->nsId);
        AstSyntaxTemplateExpr *new_expression =
            nsAstSyntaxTemplateExpr(variant->expression, lookupContext);
        if (new_expression != variant->expression) {
            PROTECT(new_expression);
            AstSyntaxTemplateLookUp *new_variant = newAstSyntaxTemplateLookUp(
                CPI(variant), variant->nsId, variant->nsSymbol, new_expression);
            PROTECT(new_variant);
            result = newAstSyntaxTemplateExpr_LookUp(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEEXPR_TYPE_FUN: {
        AstSyntaxTemplateFunction *variant = getAstSyntaxTemplateExpr_Fun(node);
        AstSyntaxTemplateFunction *new_variant =
            nsAstSyntaxTemplateFunction(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstSyntaxTemplateExpr_Fun(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEEXPR_TYPE_NEST: {
        AstSyntaxTemplateNest *variant = getAstSyntaxTemplateExpr_Nest(node);
        AstSyntaxTemplateNest *new_variant =
            nsAstSyntaxTemplateNest(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstSyntaxTemplateExpr_Nest(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEEXPR_TYPE_IFF: {
        AstSyntaxTemplateIff *variant = getAstSyntaxTemplateExpr_Iff(node);
        bool changed = false;
        AstSyntaxTemplateExpr *new_test =
            nsAstSyntaxTemplateExpr(variant->test, context);
        PROTECT(new_test);
        changed = changed || (new_test != variant->test);
        AstSyntaxTemplateNest *new_consequent =
            nsAstSyntaxTemplateNest(variant->consequent, context);
        PROTECT(new_consequent);
        changed = changed || (new_consequent != variant->consequent);
        AstSyntaxTemplateNest *new_alternative =
            nsAstSyntaxTemplateNest(variant->alternative, context);
        PROTECT(new_alternative);
        changed = changed || (new_alternative != variant->alternative);
        if (changed) {
            AstSyntaxTemplateIff *new_variant = newAstSyntaxTemplateIff(
                CPI(variant), new_test, new_consequent, new_alternative);
            PROTECT(new_variant);
            result = newAstSyntaxTemplateExpr_Iff(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEEXPR_TYPE_PRINT: {
        AstSyntaxTemplatePrint *variant = getAstSyntaxTemplateExpr_Print(node);
        AstSyntaxTemplateExpr *new_expression =
            nsAstSyntaxTemplateExpr(variant->expression, context);
        if (new_expression != variant->expression) {
            PROTECT(new_expression);
            AstSyntaxTemplatePrint *new_variant =
                newAstSyntaxTemplatePrint(CPI(variant), new_expression);
            PROTECT(new_variant);
            result = newAstSyntaxTemplateExpr_Print(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEEXPR_TYPE_TYPEOF: {
        AstSyntaxTemplateTypeOf *variant =
            getAstSyntaxTemplateExpr_TypeOf(node);
        AstSyntaxTemplateExpr *new_expression =
            nsAstSyntaxTemplateExpr(variant->expression, context);
        if (new_expression != variant->expression) {
            PROTECT(new_expression);
            AstSyntaxTemplateTypeOf *new_variant =
                newAstSyntaxTemplateTypeOf(CPI(variant), new_expression);
            PROTECT(new_variant);
            result = newAstSyntaxTemplateExpr_TypeOf(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEEXPR_TYPE_TUPLE: {
        AstSyntaxTemplateExprs *variant = getAstSyntaxTemplateExpr_Tuple(node);
        AstSyntaxTemplateExprs *new_variant =
            nsAstSyntaxTemplateExprs(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstSyntaxTemplateExpr_Tuple(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEEXPR_TYPE_STRUCTURE: {
        AstSyntaxTemplateStruct *variant =
            getAstSyntaxTemplateExpr_Structure(node);
        bool changed = false;
        AstLookUpOrSymbol *new_symbol =
            nsAstLookUpOrSymbol(variant->symbol, context);
        PROTECT(new_symbol);
        changed = changed || (new_symbol != variant->symbol);
        AstSyntaxTemplateTaggedExpressions *new_expressions =
            nsAstSyntaxTemplateTaggedExpressions(variant->expressions, context);
        PROTECT(new_expressions);
        changed = changed || (new_expressions != variant->expressions);
        if (changed) {
            AstSyntaxTemplateStruct *new_variant = newAstSyntaxTemplateStruct(
                CPI(variant), new_symbol, new_expressions);
            PROTECT(new_variant);
            result = newAstSyntaxTemplateExpr_Structure(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEEXPR_TYPE_ASSERTION: {
        AstSyntaxTemplateExpr *variant =
            getAstSyntaxTemplateExpr_Assertion(node);
        AstSyntaxTemplateExpr *new_variant =
            nsAstSyntaxTemplateExpr(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstSyntaxTemplateExpr_Assertion(CPI(node), new_variant);
        }
        break;
    }
    case AST_SYNTAXTEMPLATEEXPR_TYPE_ERROR: {
        AstSyntaxTemplateExpr *variant = getAstSyntaxTemplateExpr_Error(node);
        AstSyntaxTemplateExpr *new_variant =
            nsAstSyntaxTemplateExpr(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstSyntaxTemplateExpr_Error(CPI(node), new_variant);
        }
        break;
    }
    default:
        cant_happen("unrecognized %s",
                    astSyntaxTemplateExprTypeName(node->type));
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxTemplateExpr);
    return result;
}

static AstSyntaxBinding *nsAstSyntaxBinding(AstSyntaxBinding *node,
                                            VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxBinding);
    bool changed = false;
    AstExpression *new_value = nsAstExpression(node->value, context);
    int save = PROTECT(new_value);
    changed = changed || (new_value != node->value);
    AstSyntaxBinding *result = node;
    if (changed) {
        result = newAstSyntaxBinding(CPI(node), node->name, new_value);
        result->inherited = node->inherited;
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxBinding);
    return result;
}

static AstSyntaxBindings *nsAstSyntaxBindings(AstSyntaxBindings *node,
                                              VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstSyntaxBindings);
    bool changed = false;
    AstSyntaxBindings *result = newAstSyntaxBindings();
    int save = PROTECT(result);
    for (Index i = 0; i < sizeAstSyntaxBindings(node); ++i) {
        AstSyntaxBinding *binding = getAstSyntaxBindings(node, i);
        AstSyntaxBinding *new_binding = nsAstSyntaxBinding(binding, context);
        int save2 = PROTECT(new_binding);
        changed = changed || (new_binding != binding);
        pushAstSyntaxBindings(result, new_binding);
        UNPROTECT(save2);
    }
    UNPROTECT(save);
    LEAVE(nsAstSyntaxBindings);
    return changed ? result : node;
}

static AstExprSyntaxUse *nsAstExprSyntaxUse(AstExprSyntaxUse *node,
                                            VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstExprSyntaxUse);
    bool changed = false;
    AstSyntaxBindings *new_bindings =
        nsAstSyntaxBindings(node->bindings, context);
    int save = PROTECT(new_bindings);
    changed = changed || (new_bindings != node->bindings);
    AstExprSyntaxUse *result = node;
    if (changed) {
        result = newAstExprSyntaxUse(CPI(node), node->declarationId,
                                     node->alternativeIndex, new_bindings);
    }
    UNPROTECT(save);
    LEAVE(nsAstExprSyntaxUse);
    return result;
}

static AstDefSyntaxUse *nsAstDefSyntaxUse(AstDefSyntaxUse *node,
                                          VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstDefSyntaxUse);
    bool changed = false;
    AstSyntaxBindings *new_bindings =
        nsAstSyntaxBindings(node->bindings, context);
    int save = PROTECT(new_bindings);
    changed = changed || (new_bindings != node->bindings);
    AstDefSyntaxUse *result = node;
    if (changed) {
        result = newAstDefSyntaxUse(CPI(node), node->declarationId,
                                    node->alternativeIndex, new_bindings);
    }
    UNPROTECT(save);
    LEAVE(nsAstDefSyntaxUse);
    return result;
}

static AstDefinition *nsAstDefinition(AstDefinition *node,
                                      VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstDefinition);
    int save = STARTPROTECT();
    AstDefinition *result = node;
    switch (node->type) {
    case AST_DEFINITION_TYPE_DEFINE: {
        AstDefine *variant = getAstDefinition_Define(node);
        AstDefine *new_variant = nsAstDefine(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstDefinition_Define(CPI(node), new_variant);
        }
        break;
    }
    case AST_DEFINITION_TYPE_MULTI: {
        AstMultiDefine *variant = getAstDefinition_Multi(node);
        AstMultiDefine *new_variant = nsAstMultiDefine(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstDefinition_Multi(CPI(node), new_variant);
        }
        break;
    }
    case AST_DEFINITION_TYPE_TYPEDEF: {
        AstTypeDef *variant = getAstDefinition_TypeDef(node);
        AstTypeDef *new_variant = nsAstTypeDef(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstDefinition_TypeDef(CPI(node), new_variant);
        }
        break;
    }
    case AST_DEFINITION_TYPE_LAZY: {
        AstDefLazy *variant = getAstDefinition_Lazy(node);
        AstDefLazy *new_variant = nsAstDefLazy(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstDefinition_Lazy(CPI(node), new_variant);
        }
        break;
    }
    case AST_DEFINITION_TYPE_ALIAS: {
        AstAlias *variant = getAstDefinition_Alias(node);
        AstAlias *new_variant = nsAstAlias(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstDefinition_Alias(CPI(node), new_variant);
        }
        break;
    }
    case AST_DEFINITION_TYPE_BLANK: {
        break;
    }
    case AST_DEFINITION_TYPE_BUILTINSSLOT: {
        break;
    }
    case AST_DEFINITION_TYPE_SYNTAXDECL: {
        AstSyntaxDecl *variant = getAstDefinition_SyntaxDecl(node);
        AstSyntaxDecl *new_variant = nsAstSyntaxDecl(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstDefinition_SyntaxDecl(CPI(node), new_variant);
        }
        break;
    }
    case AST_DEFINITION_TYPE_SYNTAXUSE: {
        AstDefSyntaxUse *variant = getAstDefinition_SyntaxUse(node);
        AstDefSyntaxUse *new_variant = nsAstDefSyntaxUse(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstDefinition_SyntaxUse(CPI(node), new_variant);
        }
        break;
    }
    default:
        cant_happen("unrecognized AstDefinition type %s",
                    astDefinitionTypeName(node->type));
    }
    UNPROTECT(save);
    LEAVE(nsAstDefinition);
    return result;
}

static AstTypeClause *nsAstTypeClause(AstTypeClause *node,
                                      VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstTypeClause);
    int save = STARTPROTECT();
    AstTypeClause *result = node;
    switch (node->type) {
    case AST_TYPECLAUSE_TYPE_INTEGER:
    case AST_TYPECLAUSE_TYPE_CHARACTER:
    case AST_TYPECLAUSE_TYPE_VAR:
        break;
    case AST_TYPECLAUSE_TYPE_TYPEFUNCTION: {
        AstTypeFunction *variant = getAstTypeClause_TypeFunction(node);
        AstTypeFunction *new_variant = nsAstTypeFunction(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstTypeClause_TypeFunction(CPI(node), new_variant);
        }
        break;
    }
    case AST_TYPECLAUSE_TYPE_TYPETUPLE: {
        AstTypeList *variant = getAstTypeClause_TypeTuple(node);
        AstTypeList *new_variant = nsAstTypeList(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstTypeClause_TypeTuple(CPI(node), new_variant);
        }
        break;
    }
    default:
        cant_happen("unrecognized AstTypeClause type %d", node->type);
    }
    UNPROTECT(save);
    LEAVE(nsAstTypeClause);
    return result;
}

static AstFarg *nsAstFarg(AstFarg *node, VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstFarg);
    int save = STARTPROTECT();
    AstFarg *result = node;
    switch (node->type) {
    case AST_FARG_TYPE_WILDCARD: {
        break;
    }
    case AST_FARG_TYPE_SYMBOL: {
        HashSymbol *variant = getAstFarg_Symbol(node);
        HashSymbol *new_variant = nsSymbol(variant, context);
        if (new_variant != variant) {
            result = newAstFarg_Symbol(CPI(node), new_variant);
        }
        break;
    }
    case AST_FARG_TYPE_LOOKUP: {
        AstLookUpSymbol *variant = getAstFarg_LookUp(node);
        HashSymbol *new_variant = nsAstLookUpSymbol(variant, context);
        result = newAstFarg_Symbol(CPI(node), new_variant);
        break;
    }
    case AST_FARG_TYPE_NAMED: {
        AstNamedArg *variant = getAstFarg_Named(node);
        AstNamedArg *new_variant = nsAstNamedArg(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstFarg_Named(CPI(node), new_variant);
        }
        break;
    }
    case AST_FARG_TYPE_UNPACK: {
        AstUnpack *variant = getAstFarg_Unpack(node);
        AstUnpack *new_variant = nsAstUnpack(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstFarg_Unpack(CPI(node), new_variant);
        }
        break;
    }
    case AST_FARG_TYPE_UNPACKSTRUCT: {
        AstUnpackStruct *variant = getAstFarg_UnpackStruct(node);
        AstUnpackStruct *new_variant = nsAstUnpackStruct(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstFarg_UnpackStruct(CPI(node), new_variant);
        }
        break;
    }
    case AST_FARG_TYPE_NUMBER:
    case AST_FARG_TYPE_CHARACTER:
        break;
    case AST_FARG_TYPE_TUPLE: {
        AstFargList *variant = getAstFarg_Tuple(node);
        AstFargList *new_variant = nsAstFargList(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstFarg_Tuple(CPI(node), new_variant);
        }
        break;
    }
    default:
        cant_happen("unrecognized AstFarg type %d", node->type);
    }
    UNPROTECT(save);
    LEAVE(nsAstFarg);
    return result;
}

static AstExpression *nsAstExpression(AstExpression *node,
                                      VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstExpression);
    int save = STARTPROTECT();
    AstExpression *result = node;
    switch (node->type) {
    case AST_EXPRESSION_TYPE_BACK:
    case AST_EXPRESSION_TYPE_WILDCARD:
    case AST_EXPRESSION_TYPE_NUMBER:
    case AST_EXPRESSION_TYPE_CHARACTER:
    case AST_EXPRESSION_TYPE_ENV:
        break;
    case AST_EXPRESSION_TYPE_ALIAS: {
        AstExprAlias *variant = getAstExpression_Alias(node);
        AstExprAlias *new_variant = nsAstExprAlias(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstExpression_Alias(CPI(node), new_variant);
        }
        break;
    }
    case AST_EXPRESSION_TYPE_ANNOTATEDSYMBOL: {
        AstAnnotatedSymbol *variant = getAstExpression_AnnotatedSymbol(node);
        AstAnnotatedSymbol *new_variant =
            nsAstAnnotatedSymbol(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstExpression_AnnotatedSymbol(CPI(node), new_variant);
        }
        break;
    }
    case AST_EXPRESSION_TYPE_FUNCALL: {
        AstFunCall *variant = getAstExpression_FunCall(node);
        AstFunCall *new_variant = nsAstFunCall(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstExpression_FunCall(CPI(node), new_variant);
        }
        break;
    }
    case AST_EXPRESSION_TYPE_LOOKUP: {
        AstLookUp *variant = getAstExpression_LookUp(node);
        result = nsAstLookUp(variant, context);
        break;
    }
    case AST_EXPRESSION_TYPE_SYMBOL: {
        HashSymbol *new_symbol =
            nsSymbol(getAstExpression_Symbol(node), context);
        result = newAstExpression_Symbol(CPI(node), new_symbol);
        break;
    }
    case AST_EXPRESSION_TYPE_FUN: {
        AstCompositeFunction *variant = getAstExpression_Fun(node);
        AstCompositeFunction *new_variant =
            nsAstCompositeFunction(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstExpression_Fun(CPI(node), new_variant);
        }
        break;
    }
    case AST_EXPRESSION_TYPE_NEST: {
        AstNest *variant = getAstExpression_Nest(node);
        AstNest *new_variant = nsAstNest(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstExpression_Nest(CPI(node), new_variant);
        }
        break;
    }
    case AST_EXPRESSION_TYPE_IFF: {
        AstIff *variant = getAstExpression_Iff(node);
        AstIff *new_variant = nsAstIff(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstExpression_Iff(CPI(node), new_variant);
        }
        break;
    }
    case AST_EXPRESSION_TYPE_PRINT: {
        AstPrint *variant = getAstExpression_Print(node);
        AstPrint *new_variant = nsAstPrint(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstExpression_Print(CPI(node), new_variant);
        }
        break;
    }
    case AST_EXPRESSION_TYPE_TYPEOF: {
        AstTypeOf *variant = getAstExpression_TypeOf(node);
        AstTypeOf *new_variant = nsAstTypeOf(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstExpression_TypeOf(CPI(node), new_variant);
        }
        break;
    }
    case AST_EXPRESSION_TYPE_TUPLE: {
        AstExpressions *variant = getAstExpression_Tuple(node);
        AstExpressions *new_variant = nsAstExpressions(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstExpression_Tuple(CPI(node), new_variant);
        }
        break;
    }
    case AST_EXPRESSION_TYPE_STRUCTURE: {
        AstStruct *variant = getAstExpression_Structure(node);
        AstStruct *new_variant = nsAstStruct(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstExpression_Structure(CPI(node), new_variant);
        }
        break;
    }
    case AST_EXPRESSION_TYPE_ASSERTION: {
        AstExpression *variant = getAstExpression_Assertion(node);
        AstExpression *new_variant = nsAstExpression(variant, context);
        PROTECT(new_variant);
        result = rewriteAssertionToCall(new_variant, context);
        break;
    }
    case AST_EXPRESSION_TYPE_ERROR: {
        AstExpression *variant = getAstExpression_Error(node);
        AstExpression *new_variant = nsAstExpression(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstExpression_Error(CPI(node), new_variant);
        }
        break;
    }
    case AST_EXPRESSION_TYPE_SYNTAXUSE: {
        AstExprSyntaxUse *variant = getAstExpression_SyntaxUse(node);
        AstExprSyntaxUse *new_variant = nsAstExprSyntaxUse(variant, context);
        if (new_variant != variant) {
            PROTECT(new_variant);
            result = newAstExpression_SyntaxUse(CPI(node), new_variant);
        }
        break;
    }
    default:
        cant_happen("unrecognized AstExpression type %s",
                    astExpressionTypeName(node->type));
    }
    UNPROTECT(save);
    LEAVE(nsAstExpression);
    return result;
}

static AstNameSpaceArray *nsAstNameSpaceArray(AstNameSpaceArray *node,
                                              VisitorContext context) {
    if (node == NULL) {
        return NULL;
    }
    ENTER(nsAstNameSpaceArray);
    bool changed = false;
    AstNameSpaceArray *result = newAstNameSpaceArray();
    int save = PROTECT(result);
    // process in reverse order because lower ones depend on the higher
    // ones
    for (Index i = 0; i < node->size; i++) {
        pushAstNameSpaceArray(result, NULL);
    }
    for (Index i = 0; i < node->size; i++) {
        struct AstNameSpaceImpl *element = peeknAstNameSpaceArray(node, i);
        struct AstNameSpaceImpl *new_element =
            nsAstNameSpaceImpl(element, i, context);
        PROTECT(new_element);
        changed = changed || (new_element != element);
        pokeAstNameSpaceArray(result, i, new_element);
    }
    if (changed) {
        UNPROTECT(save);
        LEAVE(nsAstNameSpaceArray);
        return result;
    }
    UNPROTECT(save);
    LEAVE(nsAstNameSpaceArray);
    return node;
}

static HashSymbol *nsSymbol(HashSymbol *symbol, VisitorContext context) {
    HashSymbol *new = NULL;
    if (getSymbolMap(context.replacements, symbol, &new)) {
        return new;
    }
    return symbol;
}