/*
 * CEKF - VM supporting amb
 * Copyright (C) 2022-2025  Bill Hails
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * Plain lambda structures generated by lambda conversion.
 * Generated from src/lambda.yaml by tools/generate.py
 */

#include "lambda.h"
#include "memory.h"
#include "symbol.h"

#include "lambda_cps.h"
#include "lambda_functions.h"
#include "cps_kont.h"
#include "cps_kont_impl.h"

#ifdef DEBUG_LAMBDA_CPSTK
#  include "debugging_on.h"
#else
#  include "debugging_off.h"
#endif

// Forward declarations
static LamMacroSet *cpsTkLamMacroSet(LamMacroSet *node, CpsKont *k);
static LamInfoTable *cpsTkLamInfoTable(LamInfoTable *node, CpsKont *k);
static LamAliasTable *cpsTkLamAliasTable(LamAliasTable *node, CpsKont *k);
static LamAlphaTable *cpsTkLamAlphaTable(LamAlphaTable *node, CpsKont *k);
static LamExp *cpsTkLamPrimApp(LamPrimApp *node, CpsKont *k);
static LamExp *cpsTkLamSequence(LamSequence *node, CpsKont *k);
static LamExp *cpsTkMakeTuple(LamArgs *node, CpsKont *k);
static LamExp *cpsTkLamApply(LamExp *node, CpsKont *k);
static LamExp *cpsTkLamLookup(LamLookup *node, CpsKont *k);
static LamLookupSymbol *cpsTkLamLookupSymbol(LamLookupSymbol *node, CpsKont *k);
static LamExp *cpsTkLamConstruct(LamConstruct *node, CpsKont *k);
static LamExp *cpsTkLamDeconstruct(LamDeconstruct *node, CpsKont *k);
static LamTupleIndex *cpsTkLamTupleIndex(LamTupleIndex *node, CpsKont *k);
static LamExp *cpsTkMakeVec(LamMakeVec *node, CpsKont *k);
static LamExp *cpsTkLamIff(LamIff *node, CpsKont *k);
static LamExp *cpsTkLamCond(LamCond *node, CpsKont *k);
static LamExp *cpsTkLamMatch(LamMatch *node, CpsKont *k);
static LamExp *cpsTkLamLet(LamLet *node, CpsKont *k);
static LamExp *cpsTkLamLetStar(LamLetStar *node, CpsKont *k);
static LamExp *cpsTkLamLetRec(LamLetRec *node, CpsKont *k);
static LamContext *cpsTkLamContext(LamContext *node, CpsKont *k);
static LamExp *cpsTkLamAmb(LamAmb *node, CpsKont *k);
static LamExp *cpsTkLamPrint(LamPrint *node, CpsKont *k);
static LamTypeof *cpsTkLamTypeof(LamTypeof *node, CpsKont *k);
static LamTypeDefs *cpsTkLamTypeDefs(LamTypeDefs *node, CpsKont *k);
static LamTypeDefList *cpsTkLamTypeDefList(LamTypeDefList *node, CpsKont *k);
static LamTypeDef *cpsTkLamTypeDef(LamTypeDef *node, CpsKont *k);
static LamTypeConstructorList *cpsTkLamTypeConstructorList(LamTypeConstructorList *node, CpsKont *k);
static LamTypeSig *cpsTkLamTypeSig(LamTypeSig *node, CpsKont *k);
static LamTypeTags *cpsTkLamTypeTags(LamTypeTags *node, CpsKont *k);
static LamTypeSigArgs *cpsTkLamTypeSigArgs(LamTypeSigArgs *node, CpsKont *k);
static LamTypeConstructor *cpsTkLamTypeConstructor(LamTypeConstructor *node, CpsKont *k);
static LamTypeConstructorArgs *cpsTkLamTypeConstructorArgs(LamTypeConstructorArgs *node, CpsKont *k);
static LamTypeFunction *cpsTkLamTypeFunction(LamTypeFunction *node, CpsKont *k);
static LamTypeConstructorInfo *cpsTkLamTypeConstructorInfo(LamTypeConstructorInfo *node, CpsKont *k);
static LamAlphaEnv *cpsTkLamAlphaEnv(LamAlphaEnv *node, CpsKont *k);
static LamExp *cpsTkLamExp(LamExp *node, CpsKont *k);
static LamLookupOrSymbol *cpsTkLamLookupOrSymbol(LamLookupOrSymbol *node, CpsKont *k);
static LamTypeConstructorType *cpsTkLamTypeConstructorType(LamTypeConstructorType *node, CpsKont *k);
static LamInfo *cpsTkLamInfo(LamInfo *node, CpsKont *k);
static LamExp *cpsTkLamNameSpaceArray(LamNameSpaceArray *node, CpsKont *k);
static LamAlphaEnvArray *cpsTkLamAlphaEnvArray(LamAlphaEnvArray *node, CpsKont *k);

// utilities
static inline LamExp *INVOKE(CpsKont *k, LamExp *arg) {
    return k->wrapper(arg, k->env);
}

bool isAexpr(LamExp *exp) {
    switch (exp->type) {
        case LAMEXP_TYPE_VAR:
        case LAMEXP_TYPE_BACK:
        case LAMEXP_TYPE_CHARACTER:
        case LAMEXP_TYPE_CONSTANT:
        case LAMEXP_TYPE_CONSTRUCTOR:
        case LAMEXP_TYPE_ENV:
        case LAMEXP_TYPE_ERROR:
        case LAMEXP_TYPE_LAM:
        case LAMEXP_TYPE_STDINT:
        case LAMEXP_TYPE_BIGINTEGER:
            return true;
        default:
            return false;
    }
}

LamExp *makeVar(ParserInfo PI, char *prefix) {
    return newLamExp_Var(PI, genSymDollar(prefix));
}

LamArgs *appendLamArg(LamArgs *args, LamExp *exp) {
    if (args == NULL) return newLamArgs(CPI(exp), exp, NULL);
    LamArgs *next = appendLamArg(args->next, exp);
    int save = PROTECT(next);
    LamArgs *this = newLamArgs(CPI(args), args->exp, next);
    UNPROTECT(save);
    return this;
}

LamVarList *appendLamVar(ParserInfo PI, LamVarList *args, HashSymbol *var) {
    if (args == NULL) return newLamVarList(PI, var, NULL);
    LamVarList *next = appendLamVar(PI, args->next, var);
    int save = PROTECT(next);
    LamVarList *this = newLamVarList(CPI(args), args->var, next);
    UNPROTECT(save);
    return this;
}

/*
    fn Ts_k {
        ([], k) { k([]) }
        (h @ t, k) {
            T_k(h, fn (hd) {
                Ts_k(t, fn (tl) {
                    k(hd @ tl)
                })
            })
        }
    }
 */
LamExp *cpsTs_k(LamExp *exp, CpsKont *k) {
    ENTER(cpsTs_k);
    LamArgs *args = getLamExp_Args(exp);
    if (args == NULL) {
        return INVOKE(k, exp);
    }
    LamExp *h = args->exp;
    LamArgs *t = args->next;
    CpsKont *k1 = makeKont_TkS1(t, k);
    int save = PROTECT(k1);
    LamExp *result = cpsTk(h, k1);
    LEAVE(cpsTs_k);
    UNPROTECT(save);
    return result;
}

LamExp *TkS1Kont(LamExp *hd, TkS1KontEnv *env) {
    ENTER(TkS1Kont);
    CpsKont *k2 = makeKont_TkS2(env->k, hd);
    int save = PROTECT(k2);
    LamExp *result = cpsTs_k(newLamExp_Args(CPI(env->t), env->t), k2);
    LEAVE(TkS1Kont);
    UNPROTECT(save);
    return result;
}

LamExp *TkS2Kont(LamExp *tl, TkS2KontEnv *env) {
    ENTER(TkS2Kont);
    LamExp *args = makeLamExp_Args(CPI(env->hd), env->hd, getLamExp_Args(tl));
    int save = PROTECT(args);
    LamExp *result = INVOKE(env->k, args);
    UNPROTECT(save);
    LEAVE(TkS2Kont);
    return result;
}

/*
    fn kToC(k) {
        let rv = gensym("$rv");
        in E.lambda([rv], k(rv))
    }
*/
static LamExp *kToC(ParserInfo PI, CpsKont *k) {
    LamExp *rv = makeVar(PI, "rv");
    int save = PROTECT(rv);
    LamExp *body = INVOKE(k, rv);
    PROTECT(body);
    LamVarList *args = newLamVarList(PI, getLamExp_Var(rv), NULL);
    PROTECT(args);
    LamExp *cont = makeLamExp_Lam(PI, args, body);
    UNPROTECT(save);
    return cont;
}

// Visitor implementations
static LamMacroSet *cpsTkLamMacroSet(LamMacroSet *node, CpsKont *k) {
    ENTER(cpsTkLamMacroSet);
    if (node == NULL) {
        LEAVE(cpsTkLamMacroSet);
        return NULL;
    }

    (void)k;  // Hash set has no values to visit
    // Iterate over keys (uncomment if you need to inspect/log them)
    // Index i = 0;
    // HashSymbol *key;
    // while ((key = iterateLamMacroSet(node, &i)) != NULL) {
    //     // Inspect/log key here
    // }
    LEAVE(cpsTkLamMacroSet);
    return node;
}

static LamInfoTable *cpsTkLamInfoTable(LamInfoTable *node, CpsKont *k) {
    ENTER(cpsTkLamInfoTable);
    if (node == NULL) {
        LEAVE(cpsTkLamInfoTable);
        return NULL;
    }

    bool changed = false;
    LamInfoTable *result = newLamInfoTable();
    int save = PROTECT(result);

    // Iterate over all entries
    Index i = 0;
    struct LamInfo * value;
    HashSymbol *key;
    while ((key = iterateLamInfoTable(node, &i, &value)) != NULL) {
        struct LamInfo * new_value = cpsTkLamInfo(value, k);
        PROTECT(new_value);
        changed = changed || (new_value != value);
        setLamInfoTable(result, key, new_value);
    }

    if (changed) {
        UNPROTECT(save);
        LEAVE(cpsTkLamInfoTable);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamInfoTable);
    return node;
}

static LamAliasTable *cpsTkLamAliasTable(LamAliasTable *node, CpsKont *k) {
    ENTER(cpsTkLamAliasTable);
    if (node == NULL) {
        LEAVE(cpsTkLamAliasTable);
        return NULL;
    }

    bool changed = false;
    LamAliasTable *result = newLamAliasTable();
    int save = PROTECT(result);

    // Iterate over all entries
    Index i = 0;
    struct LamTypeConstructorType * value;
    HashSymbol *key;
    while ((key = iterateLamAliasTable(node, &i, &value)) != NULL) {
        struct LamTypeConstructorType * new_value = cpsTkLamTypeConstructorType(value, k);
        PROTECT(new_value);
        changed = changed || (new_value != value);
        setLamAliasTable(result, key, new_value);
    }

    if (changed) {
        UNPROTECT(save);
        LEAVE(cpsTkLamAliasTable);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamAliasTable);
    return node;
}

static LamAlphaTable *cpsTkLamAlphaTable(LamAlphaTable *node, CpsKont *k) {
    ENTER(cpsTkLamAlphaTable);
    if (node == NULL) {
        LEAVE(cpsTkLamAlphaTable);
        return NULL;
    }

    (void)k;  // Values are HashSymbol (not memory-managed)
#ifdef NOTDEF
    // Iterate over all entries for inspection/logging
    Index i = 0;
    struct HashSymbol * value;
    HashSymbol *key;
    while ((key = iterateLamAlphaTable(node, &i, &value)) != NULL) {
        // Inspect/log key and value here
    }
#endif
    LEAVE(cpsTkLamAlphaTable);
    return node;
}

/*
    (E.primapp(p, e1, e2)) {
        T_k(e1, fn (s1) {
            T_k(e2, fn (s2) {
                k(E.primapp(p, s1, s2))
            })
        })
    }
*/
static LamExp *cpsTkLamPrimApp(LamPrimApp *node, CpsKont *k) {
    ENTER(cpsTkLamPrimApp);
    CpsKont *k1 = makeKont_TkPrimApp1(k, node->exp2, node->type);
    int save = PROTECT(k1);
    LamExp *result = cpsTk(node->exp1, k1);
    UNPROTECT(save);
    LEAVE(cpsTkLamPrimApp);
    return result;
}

LamExp *TkPrimApp1Kont(LamExp *s1, TkPrimApp1KontEnv *env) {
    ENTER(TkPrimApp1Kont);
    CpsKont *k = makeKont_TkPrimApp2(env->k, s1, env->p);
    int save = PROTECT(k);
    LamExp *result = cpsTk(env->e2, k);
    UNPROTECT(save);
    LEAVE(TkPrimApp1Kont);
    return result;
}

LamExp *TkPrimApp2Kont(LamExp *s2, TkPrimApp2KontEnv *env) {
    ENTER(TkPrimApp2Kont);
    LamExp *primapp = makeLamExp_Prim(CPI(env->s1), env->p, env->s1, s2);
    int save = PROTECT(primapp);
    LamExp *result = INVOKE(env->k, primapp);
    UNPROTECT(save);
    LEAVE(TkPrimApp2Kont);
    return result;
}

/*
    (E.sequence([expr])) { T_k(expr, k) }
    (E.sequence(expr @ exprs)) {
        T_k(expr, fn (ignored) {
            T_k(E.sequence(exprs), k)
        })
    }
*/
static LamExp *cpsTkLamSequence(LamSequence *node, CpsKont *k) {
    ENTER(cpsTkLamSequence);
    LamExp *result = NULL;
    int save = PROTECT(NULL);
    if(node->next == NULL) {
        result = cpsTk(node->exp, k);
    } else {
        CpsKont *k1 = makeKont_TkSequence(k, node->next);
        PROTECT(k1);
        result = cpsTk(node->exp, k1);
    }
    UNPROTECT(save);
    LEAVE(cpsTkLamSequence);
    return result;
}

LamExp *TkSequenceKont(LamExp *ignored, TkSequenceKontEnv *env) {
    ENTER(TkSequenceKont);
    LamExp *sequence = newLamExp_Sequence(CPI(ignored), env->exprs);
    int save = PROTECT(sequence);
    LamExp *result = INVOKE(env->k, sequence);
    UNPROTECT(save);
    LEAVE(TkSequenceKont);
    return result;
}

/*
    (E.make_tuple(args)) {
        Ts_k(args, fn (sargs) {
            k(E.make_tuple(sargs))
        })
    }
*/
static LamExp *cpsTkMakeTuple(LamArgs *node, CpsKont *k) {
    ENTER(cpsTkMakeTuple);
    CpsKont *k1 = makeKont_TkMakeTuple(k);
    int save = PROTECT(k1);
    LamExp *exp = newLamExp_Args(CPI(node), node);
    PROTECT(exp);
    LamExp *result = cpsTs_k(exp, k1);
    UNPROTECT(save);
    LEAVE(cpsTkMakeTuple);
    return result;
}

LamExp *TkMakeTupleKont(LamExp *sargs, TkMakeTupleKontEnv *env) {
    ENTER(TkMakeTupleKont);
    LamExp *make_tuple = newLamExp_MakeTuple(CPI(sargs), getLamExp_Args(sargs));
    int save = PROTECT(make_tuple);
    LamExp *result = INVOKE(env->k, make_tuple);
    UNPROTECT(save);
    LEAVE(TkMakeTupleKont);
    return result;
}

/*
    (E.apply(_, _)) {
        let
            c = kToC(k)
        in
            T_c(e, c)
    }
*/
static LamExp *cpsTkLamApply(LamExp *node, CpsKont *k) {
    ENTER(cpsTkLamApply);
    if (node == NULL) {
        LEAVE(cpsTkLamApply);
        return NULL;
    }

    LamExp *c = kToC(CPI(node), k);
    int save = PROTECT(c);
    LamExp *result = cpsTc(node, c);
    UNPROTECT(save);
    LEAVE(cpsTkLamApply);
    return result;
}

/*
    (E.lookup(name, index, expr)) {
        E.lookup(name, index, T_k(expr, k))
    }
*/
static LamExp *cpsTkLamLookup(LamLookup *node, CpsKont *k) {
    ENTER(cpsTkLamLookup);
    LamExp *expr = cpsTk(node->exp, k);
    int save = PROTECT(expr);
    LamExp *result = makeLamExp_Lookup(CPI(node), node->nsid, node->nsSymbol, expr);
    UNPROTECT(save);
    LEAVE(cpsTkLamLookup);
    return result;
}

static LamLookupSymbol *cpsTkLamLookupSymbol(LamLookupSymbol *node, CpsKont *k) {
    ENTER(cpsTkLamLookupSymbol);
    if (node == NULL) {
        LEAVE(cpsTkLamLookupSymbol);
        return NULL;
    }

    // Pass through nsid (type: int, not memory-managed)
    // Pass through nsSymbol (type: HashSymbol, not memory-managed)
    // Pass through symbol (type: HashSymbol, not memory-managed)

    (void)k;  // Unused parameter - all fields are pass-through
    LEAVE(cpsTkLamLookupSymbol);
    return node;
}

/*
    (E.construct(name, args)) {
        Ts_k(args, fn (sargs) {
            k(E.construct(name, sargs))
        })
    }
*/
static LamExp *cpsTkLamConstruct(LamConstruct *node, CpsKont *k) {
    ENTER(cpsTkLamConstruct);
    CpsKont *k1 = makeKont_TkConstruct(node->name, node->tag, k);
    int save = PROTECT(k1);
    LamExp *args = newLamExp_Args(CPI(node), node->args);
    PROTECT(args);
    LamExp *result = cpsTs_k(args, k1);
    UNPROTECT(save);
    LEAVE(cpsTkLamConstruct);
    return result;
}

LamExp *TkConstructKont(LamExp *sargs, TkConstructKontEnv *env) {
    ENTER(TkConstructKont);
    LamExp *construct = makeLamExp_Construct(CPI(sargs), env->name, env->tag, getLamExp_Args(sargs));
    int save = PROTECT(construct);
    LamExp *result = INVOKE(env->k, construct);
    UNPROTECT(save);
    LEAVE(TkConstructKont);
    return result;
}

/*
    (E.deconstruct(name, nsid, vec, expr)) {
        T_k(expr, fn (sexpr) {
            k(E.deconstruct(name, nsid, vec, sexpr))
        })
    }
*/
static LamExp *cpsTkLamDeconstruct(LamDeconstruct *node, CpsKont *k) {
    ENTER(cpsTkLamDeconstruct);
    CpsKont *k1 = makeKont_TkDeconstruct(node->name, node->nsid, node->vec, k);
    int save = PROTECT(k1);
    LamExp *result = cpsTk(node->exp, k1);
    UNPROTECT(save);
    LEAVE(cpsTkLamDeconstruct);
    return result;
}

LamExp *TkDeconstructKont(LamExp *sexpr, TkDeconstructKontEnv *env) {
    ENTER(TkDeconstructKont);
    LamExp *deconstruct = makeLamExp_Deconstruct(CPI(sexpr), env->name, env->nsid, env->vec, sexpr);
    int save = PROTECT(deconstruct);
    LamExp *result = INVOKE(env->k, deconstruct);
    UNPROTECT(save);
    LEAVE(TkDeconstructKont);
    return result;
}

static LamTupleIndex *cpsTkLamTupleIndex(LamTupleIndex *node, CpsKont *k) {
    ENTER(cpsTkLamTupleIndex);
    if (node == NULL) {
        LEAVE(cpsTkLamTupleIndex);
        return NULL;
    }

    bool changed = false;
    // Pass through vec (type: int, not memory-managed)
    // Pass through size (type: int, not memory-managed)
    LamExp *new_exp = cpsTkLamExp(node->exp, k);
    int save = PROTECT(new_exp);
    changed = changed || (new_exp != node->exp);

    if (changed) {
        // Create new node with modified fields
        LamTupleIndex *result = newLamTupleIndex(CPI(node), node->vec, node->size, new_exp);
        UNPROTECT(save);
        LEAVE(cpsTkLamTupleIndex);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamTupleIndex);
    return node;
}

/*
    (E.make_vec(size, args)) {
        Ts_k(args, fn (sargs) {
            k(E.make_vec(size, sargs))
        })
    }
*/
static LamExp *cpsTkMakeVec(LamMakeVec *node, CpsKont *k) {
    ENTER(cpsTkMakeVec);
    CpsKont *k1 = makeKont_TkMakeVec(node->nargs, k);
    int save = PROTECT(k1);
    LamExp *args = newLamExp_Args(CPI(node), node->args);
    PROTECT(args);
    LamExp *result = cpsTs_k(args, k1);
    UNPROTECT(save);
    LEAVE(cpsTkMakeVec);
    return result;
}

LamExp *TkMakeVecKont(LamExp *sargs, TkMakeVecKontEnv *env) {
    ENTER(TkMakeVecKont);
    LamExp *make_vec = makeLamExp_MakeVec(CPI(sargs), env->size, getLamExp_Args(sargs));
    int save = PROTECT(make_vec);
    LamExp *result = INVOKE(env->k, make_vec);
    UNPROTECT(save);
    LEAVE(TkMakeVecKont);
    return result;
}

/*
    (E.if_expr(exprc, exprt, exprf)) {
        let
            c = kToC(k);
        in 
            T_k(exprc, fn(aexp) {
                E.if_expr(aexp, T_c(exprt, c), T_c(exprf, c))
            })
    }
*/
static LamExp *cpsTkLamIff(LamIff *node, CpsKont *k) {
    ENTER(cpsTkLamIff);
    if (node == NULL) {
        LEAVE(cpsTkLamIff);
        return NULL;
    }
    LamExp *c = kToC(CPI(node), k);
    int save = PROTECT(c);
    CpsKont *k2 = makeKont_TkIff(c, node->consequent, node->alternative);
    PROTECT(k2);
    LamExp *result = cpsTk(node->condition, k2);
    UNPROTECT(save);
    LEAVE(cpsTkLamIff);
    return result;
}

LamExp *TkIffKont(LamExp *aexp, TkIffKontEnv *env) {
    ENTER(TkIffKont);
    LamExp *consequent = cpsTc(env->exprt, env->c);
    int save = PROTECT(consequent);
    LamExp *alternative = cpsTc(env->exprf, env->c);
    PROTECT(alternative);
    LamExp *result = makeLamExp_Iff(CPI(aexp), aexp, consequent, alternative);
    UNPROTECT(save);
    LEAVE(TkIffKont);
    return result;
}

static LamIntCondCases *mapIntCondCases(LamIntCondCases *cases, LamExp *c) {
    if (cases == NULL) return NULL;
    LamIntCondCases *next = mapIntCondCases(cases->next, c);
    int save = PROTECT(next);
    LamExp *body = cpsTc(cases->body, c);
    PROTECT(body);
    LamIntCondCases *this = newLamIntCondCases(CPI(cases), cases->constant, body, next);
    UNPROTECT(save);
    return this;
}

static LamCharCondCases *mapCharCondCases(LamCharCondCases *cases, LamExp *c) {
    if (cases == NULL) return NULL;
    LamCharCondCases *next = mapCharCondCases(cases->next, c);
    int save = PROTECT(next);
    LamExp *body = cpsTc(cases->body, c);
    PROTECT(body);
    LamCharCondCases *this = newLamCharCondCases(CPI(cases), cases->constant, body, next);
    UNPROTECT(save);
    return this;
}

/*
    (E.cond_expr(test, branches)) {
        let
            c = kToC(k);
        in
            T_k(test, fn (atest) {
                E.cond_expr(atest, list.map(fn {(#(val, result)) {
                    #(val, T_c(result, c))
                }}, branches))
            })
    }
*/
static LamExp *cpsTkLamCond(LamCond *node, CpsKont *k) {
    ENTER(cpsTkLamCond);
    if (node == NULL) {
        LEAVE(cpsTkLamCond);
        return NULL;
    }
    LamExp *c = kToC(CPI(node), k);
    int save = PROTECT(c);
    CpsKont *k2 = makeKont_TkCond(c, node->cases);
    PROTECT(k2);
    LamExp *result = cpsTk(node->value, k2);
    UNPROTECT(save);
    LEAVE(cpsTkLamCond);
    return result;
}

LamExp *TkCondKont(LamExp *atest, TkCondKontEnv *env) {
    ENTER(TkCondKont);
    LamCondCases *cases = NULL;
    int save = PROTECT(NULL);
    switch (env->branches->type) {
        case LAMCONDCASES_TYPE_INTEGERS: {
            LamIntCondCases *int_cases = mapIntCondCases(getLamCondCases_Integers(env->branches), env->c);
            PROTECT(int_cases);
            cases = newLamCondCases_Integers(CPI(atest), int_cases);
            PROTECT(cases);
        }
        break;
        case LAMCONDCASES_TYPE_CHARACTERS: {
            LamCharCondCases *char_cases = mapCharCondCases(getLamCondCases_Characters(env->branches), env->c);
            PROTECT(char_cases);
            cases = newLamCondCases_Characters(CPI(atest), char_cases);
            PROTECT(cases);
        }
        default:
            cant_happen("Unknown LamCondCases type %s in TkCondKont", lamCondCasesTypeName(env->branches->type));
    }
    LamExp *result = makeLamExp_Cond(CPI(atest), atest, cases);
    LEAVE(TkCondKont);
    UNPROTECT(save);
    return result;
}

/*
    (E.match_cases(test, cases)) {
        let
            c = kToC(k);
        in
            T_k(test, fn (atest) {
                E.match_cases(atest, list.map(fn {(#(indices, result)) {
                    #(indices, T_c(result, c))
                }}, cases))
            })
    }
*/
static LamExp *cpsTkLamMatch(LamMatch *node, CpsKont *k) {
    ENTER(cpsTkLamMatch);
    LamExp *c = kToC(CPI(node), k);
    int save = PROTECT(c);
    CpsKont *k2 = makeKont_TkMatch(c, node->cases);
    PROTECT(k2);
    LamExp *result = cpsTk(node->index, k2);
    UNPROTECT(save);
    LEAVE(cpsTkLamMatch);
    return result;
}

LamMatchList *mapTcOverMatchCases(LamMatchList *cases, LamExp *c) {
    if (cases == NULL) return NULL;
    LamMatchList *next = mapTcOverMatchCases(cases->next, c);
    int save = PROTECT(next);
    LamExp *body = cpsTc(cases->body, c);
    PROTECT(body);
    LamMatchList *this = newLamMatchList(CPI(cases), cases->matches, body, next);
    UNPROTECT(save);
    return this;
}

LamExp *TkMatchKont(LamExp *atest, TkMatchKontEnv *env) {
    ENTER(TkMatchKont);
    LamMatchList *cases = mapTcOverMatchCases(env->cases, env->c);
    int save = PROTECT(cases);
    LamExp *result = makeLamExp_Match(CPI(atest), atest, cases);
    UNPROTECT(save);
    LEAVE(TkMatchKont);
    return result;
}

void cpsUnzipLamBindings(LamBindings *bindings, LamVarList **vars, LamArgs **exps) {
    if (bindings == NULL) {
        *vars = NULL;
        *exps = NULL;
        return;
    }
    cpsUnzipLamBindings(bindings->next, vars, exps);
    *vars = newLamVarList(CPI(bindings), bindings->var, *vars);
    PROTECT(*vars);
    *exps = newLamArgs(CPI(bindings), bindings->val, *exps);
    PROTECT(*exps);
}

/*
    (E.let_expr(bindings, expr)) {
        let
            #(vars, exps) = list.unzip(bindings);
        in
            T_k(E.apply(E.lambda(vars, expr), exps), k)
    }
*/
static LamExp *cpsTkLamLet(LamLet *node, CpsKont *k) {
    ENTER(cpsTkLamLet);
    int save = PROTECT(NULL);
    LamVarList *vars = NULL;
    LamArgs *exps = NULL;
    cpsUnzipLamBindings(node->bindings, &vars, &exps); // PROTECTED
    LamExp *lambda = makeLamExp_Lam(CPI(node), vars, node->body);
    PROTECT(lambda);
    LamExp *apply = makeLamExp_Apply(CPI(node), lambda, exps);
    PROTECT(apply);
    LamExp *result = cpsTk(apply, k);
    UNPROTECT(save);
    LEAVE(cpsTkLamLet);
    return result;
}

LamExp *cpsNestLets(LamBindings *bindings, LamExp *body) {
    if (bindings == NULL) {
        return body;
    }
    LamExp *rest = cpsNestLets(bindings->next, body);
    int save = PROTECT(rest);
    LamBindings *binding = newLamBindings(CPI(bindings), bindings->var, bindings->val, NULL);
    PROTECT(binding);
    LamExp *this = makeLamExp_Let(CPI(bindings), binding, rest);
    UNPROTECT(save);
    return this;
}
/*
    (E.letstar_expr(bindings, expr)) {
        let
            fn nest_lets {
                ([], body) { body }
                (#(var, exp) @ rest, body) {
                    E.let_expr([#(var, exp)], nest_lets(rest, body))
                }
            }
        in
            T_k(nest_lets(bindings, expr), k)
    }
*/
static LamExp *cpsTkLamLetStar(LamLetStar *node, CpsKont *k) {
    ENTER(cpsTkLamLetStar);
    LamExp *lets = cpsNestLets(node->bindings, node->body);
    int save = PROTECT(lets);
    LamExp *result = cpsTk(lets, k);
    UNPROTECT(save);
    LEAVE(cpsTkLamLetStar);
    return result;
}

LamBindings *mapMOverBindings(LamBindings *bindings) {
    if (bindings == NULL) return NULL;
    LamBindings *next = mapMOverBindings(bindings->next);
    int save = PROTECT(next);
    LamExp *new_val = cpsM(bindings->val);
    PROTECT(new_val);
    LamBindings *this = newLamBindings(CPI(bindings), bindings->var, new_val, next);
    UNPROTECT(save);
    return this;
}

/*
    (E.letrec_expr(bindings, expr)) {
        let
            #(vars, aexps) = list.unzip(bindings);
        in
            E.letrec_expr(list.zip(vars, list.map(M, aexps)), T_k(expr, k))
    }
*/
static LamExp *cpsTkLamLetRec(LamLetRec *node, CpsKont *k) {
    ENTER(cpsTkLamLetRec);
    LamBindings *bindings = mapMOverBindings(node->bindings);
    int save = PROTECT(bindings);
    LamExp *body = cpsTkLamExp(node->body, k);
    PROTECT(body);
    LamExp *result = makeLamExp_LetRec(CPI(node), bindings, body);
    UNPROTECT(save);
    LEAVE(cpsTkLamLetRec);
    return result;
}

static LamContext *cpsTkLamContext(LamContext *node, CpsKont *k) {
    ENTER(cpsTkLamContext);
    if (node == NULL) {
        LEAVE(cpsTkLamContext);
        return NULL;
    }

    bool changed = false;
    LamInfoTable *new_frame = cpsTkLamInfoTable(node->frame, k);
    int save = PROTECT(new_frame);
    changed = changed || (new_frame != node->frame);
    LamAliasTable *new_aliases = cpsTkLamAliasTable(node->aliases, k);
    PROTECT(new_aliases);
    changed = changed || (new_aliases != node->aliases);
    LamMacroSet *new_macros = cpsTkLamMacroSet(node->macros, k);
    PROTECT(new_macros);
    changed = changed || (new_macros != node->macros);
    LamContext *new_parent = cpsTkLamContext(node->parent, k);
    PROTECT(new_parent);
    changed = changed || (new_parent != node->parent);

    if (changed) {
        // Create new node with modified fields
        LamContext *result = newLamContext(CPI(node), new_parent);
        result->frame = new_frame;
        result->aliases = new_aliases;
        result->macros = new_macros;
        UNPROTECT(save);
        LEAVE(cpsTkLamContext);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamContext);
    return node;
}

/*
    (E.amb_expr(expr1, expr2)) {
        let
            c = kToC(k);
        in 
            E.amb_expr(T_c(expr1, c), T_c(expr2, c))
    }
*/
static LamExp *cpsTkLamAmb(LamAmb *node, CpsKont *k) {
    LamExp *c = kToC(CPI(node), k);
    int save = PROTECT(c);
    LamExp *exp1 = cpsTc(node->left, c);
    PROTECT(exp1);
    LamExp *exp2 = cpsTc(node->right, c);
    PROTECT(exp2);
    LamExp *result = makeLamExp_Amb(CPI(node), exp1, exp2);
    UNPROTECT(save);
    return result;
}

/*
    (E.print_exp(expr)) {
        T_k(expr, fn (sexpr) {
            k(E.print_exp(sexpr))
        })
    }
*/
static LamExp *cpsTkLamPrint(LamPrint *node, CpsKont *k) {
    ENTER(cpsTkLamPrint);
    CpsKont *k1 = makeKont_TkPrint(k);
    int save = PROTECT(k1);
    LamExp *result = cpsTk(node->exp, k1);
    UNPROTECT(save);
    LEAVE(cpsTkLamPrint);
    return result;
}

LamExp *TkPrintKont(LamExp *sexpr, TkPrintKontEnv *env) {
    ENTER(TkPrintKont);
    LamExp *print_exp = makeLamExp_Print(CPI(sexpr), sexpr);
    int save = PROTECT(print_exp);
    LamExp *result = INVOKE(env->k, print_exp);
    UNPROTECT(save);
    LEAVE(TkPrintKont);
    return result;
}

static LamTypeof *cpsTkLamTypeof(LamTypeof *node, CpsKont *k) {
    ENTER(cpsTkLamTypeof);
    if (node == NULL) {
        LEAVE(cpsTkLamTypeof);
        return NULL;
    }

    bool changed = false;
    LamExp *new_exp = cpsTkLamExp(node->exp, k);
    int save = PROTECT(new_exp);
    changed = changed || (new_exp != node->exp);
    LamExp *new_typestring = cpsTkLamExp(node->typestring, k);
    PROTECT(new_typestring);
    changed = changed || (new_typestring != node->typestring);

    if (changed) {
        // Create new node with modified fields
        LamTypeof *result = newLamTypeof(CPI(node), new_exp);
        result->typestring = new_typestring;
        UNPROTECT(save);
        LEAVE(cpsTkLamTypeof);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamTypeof);
    return node;
}

static LamTypeDefs *cpsTkLamTypeDefs(LamTypeDefs *node, CpsKont *k) {
    ENTER(cpsTkLamTypeDefs);
    if (node == NULL) {
        LEAVE(cpsTkLamTypeDefs);
        return NULL;
    }

    bool changed = false;
    LamTypeDefList *new_typeDefs = cpsTkLamTypeDefList(node->typeDefs, k);
    int save = PROTECT(new_typeDefs);
    changed = changed || (new_typeDefs != node->typeDefs);
    LamExp *new_body = cpsTkLamExp(node->body, k);
    PROTECT(new_body);
    changed = changed || (new_body != node->body);

    if (changed) {
        // Create new node with modified fields
        LamTypeDefs *result = newLamTypeDefs(CPI(node), new_typeDefs, new_body);
        UNPROTECT(save);
        LEAVE(cpsTkLamTypeDefs);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamTypeDefs);
    return node;
}

static LamTypeDefList *cpsTkLamTypeDefList(LamTypeDefList *node, CpsKont *k) {
    ENTER(cpsTkLamTypeDefList);
    if (node == NULL) {
        LEAVE(cpsTkLamTypeDefList);
        return NULL;
    }

    bool changed = false;
    LamTypeDef *new_typeDef = cpsTkLamTypeDef(node->typeDef, k);
    int save = PROTECT(new_typeDef);
    changed = changed || (new_typeDef != node->typeDef);
    LamTypeDefList *new_next = cpsTkLamTypeDefList(node->next, k);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);

    if (changed) {
        // Create new node with modified fields
        LamTypeDefList *result = newLamTypeDefList(CPI(node), new_typeDef, new_next);
        UNPROTECT(save);
        LEAVE(cpsTkLamTypeDefList);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamTypeDefList);
    return node;
}

static LamTypeDef *cpsTkLamTypeDef(LamTypeDef *node, CpsKont *k) {
    ENTER(cpsTkLamTypeDef);
    if (node == NULL) {
        LEAVE(cpsTkLamTypeDef);
        return NULL;
    }

    bool changed = false;
    LamTypeSig *new_type = cpsTkLamTypeSig(node->type, k);
    int save = PROTECT(new_type);
    changed = changed || (new_type != node->type);
    LamTypeConstructorList *new_constructors = cpsTkLamTypeConstructorList(node->constructors, k);
    PROTECT(new_constructors);
    changed = changed || (new_constructors != node->constructors);

    if (changed) {
        // Create new node with modified fields
        LamTypeDef *result = newLamTypeDef(CPI(node), new_type, new_constructors);
        UNPROTECT(save);
        LEAVE(cpsTkLamTypeDef);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamTypeDef);
    return node;
}

static LamTypeConstructorList *cpsTkLamTypeConstructorList(LamTypeConstructorList *node, CpsKont *k) {
    ENTER(cpsTkLamTypeConstructorList);
    if (node == NULL) {
        LEAVE(cpsTkLamTypeConstructorList);
        return NULL;
    }

    bool changed = false;
    LamTypeConstructor *new_constructor = cpsTkLamTypeConstructor(node->constructor, k);
    int save = PROTECT(new_constructor);
    changed = changed || (new_constructor != node->constructor);
    LamTypeConstructorList *new_next = cpsTkLamTypeConstructorList(node->next, k);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);

    if (changed) {
        // Create new node with modified fields
        LamTypeConstructorList *result = newLamTypeConstructorList(CPI(node), new_constructor, new_next);
        UNPROTECT(save);
        LEAVE(cpsTkLamTypeConstructorList);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamTypeConstructorList);
    return node;
}

static LamTypeSig *cpsTkLamTypeSig(LamTypeSig *node, CpsKont *k) {
    ENTER(cpsTkLamTypeSig);
    if (node == NULL) {
        LEAVE(cpsTkLamTypeSig);
        return NULL;
    }

    bool changed = false;
    // Pass through name (type: HashSymbol, not memory-managed)
    LamTypeSigArgs *new_args = cpsTkLamTypeSigArgs(node->args, k);
    int save = PROTECT(new_args);
    changed = changed || (new_args != node->args);

    if (changed) {
        // Create new node with modified fields
        LamTypeSig *result = newLamTypeSig(CPI(node), node->name, new_args);
        UNPROTECT(save);
        LEAVE(cpsTkLamTypeSig);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamTypeSig);
    return node;
}

static LamTypeTags *cpsTkLamTypeTags(LamTypeTags *node, CpsKont *k) {
    ENTER(cpsTkLamTypeTags);
    if (node == NULL) {
        LEAVE(cpsTkLamTypeTags);
        return NULL;
    }

    bool changed = false;
    // Pass through tag (type: HashSymbol, not memory-managed)
    LamTypeTags *new_next = cpsTkLamTypeTags(node->next, k);
    int save = PROTECT(new_next);
    changed = changed || (new_next != node->next);

    if (changed) {
        // Create new node with modified fields
        LamTypeTags *result = newLamTypeTags(CPI(node), node->tag, new_next);
        UNPROTECT(save);
        LEAVE(cpsTkLamTypeTags);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamTypeTags);
    return node;
}

static LamTypeSigArgs *cpsTkLamTypeSigArgs(LamTypeSigArgs *node, CpsKont *k) {
    ENTER(cpsTkLamTypeSigArgs);
    if (node == NULL) {
        LEAVE(cpsTkLamTypeSigArgs);
        return NULL;
    }

    bool changed = false;
    // Pass through name (type: HashSymbol, not memory-managed)
    LamTypeSigArgs *new_next = cpsTkLamTypeSigArgs(node->next, k);
    int save = PROTECT(new_next);
    changed = changed || (new_next != node->next);

    if (changed) {
        // Create new node with modified fields
        LamTypeSigArgs *result = newLamTypeSigArgs(CPI(node), node->name, new_next);
        UNPROTECT(save);
        LEAVE(cpsTkLamTypeSigArgs);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamTypeSigArgs);
    return node;
}

static LamTypeConstructor *cpsTkLamTypeConstructor(LamTypeConstructor *node, CpsKont *k) {
    ENTER(cpsTkLamTypeConstructor);
    if (node == NULL) {
        LEAVE(cpsTkLamTypeConstructor);
        return NULL;
    }

    bool changed = false;
    // Pass through name (type: HashSymbol, not memory-managed)
    LamTypeSig *new_type = cpsTkLamTypeSig(node->type, k);
    int save = PROTECT(new_type);
    changed = changed || (new_type != node->type);
    LamTypeConstructorArgs *new_args = cpsTkLamTypeConstructorArgs(node->args, k);
    PROTECT(new_args);
    changed = changed || (new_args != node->args);

    if (changed) {
        // Create new node with modified fields
        LamTypeConstructor *result = newLamTypeConstructor(CPI(node), node->name, new_type, new_args);
        UNPROTECT(save);
        LEAVE(cpsTkLamTypeConstructor);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamTypeConstructor);
    return node;
}

static LamTypeConstructorArgs *cpsTkLamTypeConstructorArgs(LamTypeConstructorArgs *node, CpsKont *k) {
    ENTER(cpsTkLamTypeConstructorArgs);
    if (node == NULL) {
        LEAVE(cpsTkLamTypeConstructorArgs);
        return NULL;
    }

    bool changed = false;
    LamTypeConstructorType *new_arg = cpsTkLamTypeConstructorType(node->arg, k);
    int save = PROTECT(new_arg);
    changed = changed || (new_arg != node->arg);
    LamTypeConstructorArgs *new_next = cpsTkLamTypeConstructorArgs(node->next, k);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);

    if (changed) {
        // Create new node with modified fields
        LamTypeConstructorArgs *result = newLamTypeConstructorArgs(CPI(node), new_arg, new_next);
        UNPROTECT(save);
        LEAVE(cpsTkLamTypeConstructorArgs);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamTypeConstructorArgs);
    return node;
}

static LamTypeFunction *cpsTkLamTypeFunction(LamTypeFunction *node, CpsKont *k) {
    ENTER(cpsTkLamTypeFunction);
    if (node == NULL) {
        LEAVE(cpsTkLamTypeFunction);
        return NULL;
    }

    bool changed = false;
    LamLookupOrSymbol *new_name = cpsTkLamLookupOrSymbol(node->name, k);
    int save = PROTECT(new_name);
    changed = changed || (new_name != node->name);
    LamTypeConstructorArgs *new_args = cpsTkLamTypeConstructorArgs(node->args, k);
    PROTECT(new_args);
    changed = changed || (new_args != node->args);

    if (changed) {
        // Create new node with modified fields
        LamTypeFunction *result = newLamTypeFunction(CPI(node), new_name, new_args);
        UNPROTECT(save);
        LEAVE(cpsTkLamTypeFunction);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamTypeFunction);
    return node;
}

static LamTypeConstructorInfo *cpsTkLamTypeConstructorInfo(LamTypeConstructorInfo *node, CpsKont *k) {
    ENTER(cpsTkLamTypeConstructorInfo);
    if (node == NULL) {
        LEAVE(cpsTkLamTypeConstructorInfo);
        return NULL;
    }

    bool changed = false;
    // Pass through name (type: HashSymbol, not memory-managed)
    // Pass through nsid (type: int, not memory-managed)
    LamTypeConstructor *new_type = cpsTkLamTypeConstructor(node->type, k);
    int save = PROTECT(new_type);
    changed = changed || (new_type != node->type);
    LamTypeTags *new_tags = cpsTkLamTypeTags(node->tags, k);
    PROTECT(new_tags);
    changed = changed || (new_tags != node->tags);
    // Pass through needsVec (type: bool, not memory-managed)
    // Pass through arity (type: int, not memory-managed)
    // Pass through size (type: int, not memory-managed)
    // Pass through index (type: int, not memory-managed)

    if (changed) {
        // Create new node with modified fields
        LamTypeConstructorInfo *result = newLamTypeConstructorInfo(CPI(node), node->name, node->nsid, new_type, new_tags, node->needsVec, node->arity, node->size, node->index);
        UNPROTECT(save);
        LEAVE(cpsTkLamTypeConstructorInfo);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamTypeConstructorInfo);
    return node;
}

static LamAlphaEnv *cpsTkLamAlphaEnv(LamAlphaEnv *node, CpsKont *k) {
    ENTER(cpsTkLamAlphaEnv);
    if (node == NULL) {
        LEAVE(cpsTkLamAlphaEnv);
        return NULL;
    }

    bool changed = false;
    LamAlphaTable *new_alphaTable = cpsTkLamAlphaTable(node->alphaTable, k);
    int save = PROTECT(new_alphaTable);
    changed = changed || (new_alphaTable != node->alphaTable);
    LamAlphaEnv *new_next = cpsTkLamAlphaEnv(node->next, k);
    PROTECT(new_next);
    changed = changed || (new_next != node->next);
    LamAlphaEnvArray *new_nameSpaces = cpsTkLamAlphaEnvArray(node->nameSpaces, k);
    PROTECT(new_nameSpaces);
    changed = changed || (new_nameSpaces != node->nameSpaces);

    if (changed) {
        // Create new node with modified fields
        LamAlphaEnv *result = newLamAlphaEnv(new_next);
        result->alphaTable = new_alphaTable;
        result->nameSpaces = new_nameSpaces;
        UNPROTECT(save);
        LEAVE(cpsTkLamAlphaEnv);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamAlphaEnv);
    return node;
}

/*
    (E.callCC_expr(e)) {
        let
            c = kToC(k);
        in
            T_c(E.callCC_expr(e), c)
    }
*/
static LamExp *cpsTkCallCC(LamExp *node, CpsKont *k) {
    ENTER(cpsTkCallCC);
    LamExp *c = kToC(CPI(node), k);
    int save = PROTECT(c);
    LamExp *result = cpsTc(node, c);
    UNPROTECT(save);
    LEAVE(cpsTkCallCC);
    return result;
}

static LamExp *cpsTkLamExp(LamExp *node, CpsKont *k) {
    ENTER(cpsTkLamExp);
    if (node == NULL) {
        LEAVE(cpsTkLamExp);
        return NULL;
    }

    if (isAexpr(node)) {
        LamExp *expr = cpsM(node);
        int save = PROTECT(expr);
        LamExp *result = INVOKE(k, expr);
        UNPROTECT(save);
        LEAVE(cpsTkLamExp);
        return result;
    }

    int save = PROTECT(NULL);
    LamExp *result = node;

    switch (node->type) {
        case LAMEXP_TYPE_AMB: {
            result = cpsTkLamAmb(getLamExp_Amb(node), k);
            break;
        }
        case LAMEXP_TYPE_APPLY: {
            result = cpsTkLamApply(node, k);
            break;
        }
        case LAMEXP_TYPE_CALLCC: {
            result = cpsTkCallCC(getLamExp_CallCC(node), k);
            break;
        }
        case LAMEXP_TYPE_COND: {
            result = cpsTkLamCond(getLamExp_Cond(node), k);
            break;
        }
        case LAMEXP_TYPE_CONSTRUCT: {
            result = cpsTkLamConstruct(getLamExp_Construct(node), k);
            break;
        }
        case LAMEXP_TYPE_DECONSTRUCT: {
            result = cpsTkLamDeconstruct(getLamExp_Deconstruct(node), k);
            break;
        }
        case LAMEXP_TYPE_IFF: {
            result = cpsTkLamIff(getLamExp_Iff(node), k);
            break;
        }
        case LAMEXP_TYPE_LET: {
            result = cpsTkLamLet(getLamExp_Let(node), k);
            break;
        }
        case LAMEXP_TYPE_LETSTAR: {
            result = cpsTkLamLetStar(getLamExp_LetStar(node), k);
            break;
        }
        case LAMEXP_TYPE_LETREC: {
            result = cpsTkLamLetRec(getLamExp_LetRec(node), k);
            break;
        }
        case LAMEXP_TYPE_LOOKUP: {
            result = cpsTkLamLookup(getLamExp_Lookup(node), k);
            break;
        }
        case LAMEXP_TYPE_MAKETUPLE: {
            result = cpsTkMakeTuple(getLamExp_MakeTuple(node), k);
            break;
        }
        case LAMEXP_TYPE_MAKEVEC: {
            result = cpsTkMakeVec(getLamExp_MakeVec(node), k);
            break;
        }
        case LAMEXP_TYPE_MATCH: {
            result = cpsTkLamMatch(getLamExp_Match(node), k);
            break;
        }
        case LAMEXP_TYPE_NAMESPACES: {
            result = cpsTkLamNameSpaceArray(getLamExp_NameSpaces(node), k);
            break;
        }
        case LAMEXP_TYPE_PRIM: {
            // LamPrimApp
            result = cpsTkLamPrimApp(getLamExp_Prim(node), k);
            break;
        }
        case LAMEXP_TYPE_PRINT: {
            result = cpsTkLamPrint(getLamExp_Print(node), k);
            break;
        }
        case LAMEXP_TYPE_SEQUENCE: {
            result = cpsTkLamSequence(getLamExp_Sequence(node), k);
            break;
        }
        case LAMEXP_TYPE_STDINT: {
            // int
            break;
        }
        case LAMEXP_TYPE_TAG: {
            // LamExp
            LamExp *variant = getLamExp_Tag(node);
            LamExp *new_variant = cpsTkLamExp(variant, k);
            if (new_variant != variant) {
                PROTECT(new_variant);
                result = newLamExp_Tag(CPI(node), new_variant);
            }
            break;
        }
        case LAMEXP_TYPE_TUPLEINDEX: {
            // LamTupleIndex
            LamTupleIndex *variant = getLamExp_TupleIndex(node);
            LamTupleIndex *new_variant = cpsTkLamTupleIndex(variant, k);
            if (new_variant != variant) {
                PROTECT(new_variant);
                result = newLamExp_TupleIndex(CPI(node), new_variant);
            }
            break;
        }
        case LAMEXP_TYPE_TYPEDEFS: {
            // LamTypeDefs
            LamTypeDefs *variant = getLamExp_Typedefs(node);
            LamTypeDefs *new_variant = cpsTkLamTypeDefs(variant, k);
            if (new_variant != variant) {
                PROTECT(new_variant);
                result = newLamExp_Typedefs(CPI(node), new_variant);
            }
            break;
        }
        case LAMEXP_TYPE_TYPEOF: {
            // LamTypeof
            LamTypeof *variant = getLamExp_TypeOf(node);
            LamTypeof *new_variant = cpsTkLamTypeof(variant, k);
            if (new_variant != variant) {
                PROTECT(new_variant);
                result = newLamExp_TypeOf(CPI(node), new_variant);
            }
            break;
        }
        case LAMEXP_TYPE_VAR: {
            // HashSymbol
            break;
        }
        default:
            cant_happen("unrecognized LamExp type %d", node->type);
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamExp);
    return result;
}

static LamLookupOrSymbol *cpsTkLamLookupOrSymbol(LamLookupOrSymbol *node, CpsKont *k) {
    ENTER(cpsTkLamLookupOrSymbol);
    if (node == NULL) {
        LEAVE(cpsTkLamLookupOrSymbol);
        return NULL;
    }

    int save = PROTECT(NULL);
    LamLookupOrSymbol *result = node;

    switch (node->type) {
        case LAMLOOKUPORSYMBOL_TYPE_SYMBOL: {
            // HashSymbol
            break;
        }
        case LAMLOOKUPORSYMBOL_TYPE_LOOKUP: {
            // LamLookupSymbol
            LamLookupSymbol *variant = getLamLookupOrSymbol_Lookup(node);
            LamLookupSymbol *new_variant = cpsTkLamLookupSymbol(variant, k);
            if (new_variant != variant) {
                PROTECT(new_variant);
                result = newLamLookupOrSymbol_Lookup(CPI(node), new_variant);
            }
            break;
        }
        default:
            cant_happen("unrecognized LamLookupOrSymbol type %d", node->type);
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamLookupOrSymbol);
    return result;
}

static LamTypeConstructorType *cpsTkLamTypeConstructorType(LamTypeConstructorType *node, CpsKont *k) {
    ENTER(cpsTkLamTypeConstructorType);
    if (node == NULL) {
        LEAVE(cpsTkLamTypeConstructorType);
        return NULL;
    }

    int save = PROTECT(NULL);
    LamTypeConstructorType *result = node;

    switch (node->type) {
        case LAMTYPECONSTRUCTORTYPE_TYPE_INTEGER: {
            // void_ptr
            break;
        }
        case LAMTYPECONSTRUCTORTYPE_TYPE_CHARACTER: {
            // void_ptr
            break;
        }
        case LAMTYPECONSTRUCTORTYPE_TYPE_VAR: {
            // HashSymbol
            break;
        }
        case LAMTYPECONSTRUCTORTYPE_TYPE_FUNCTION: {
            // LamTypeFunction
            LamTypeFunction *variant = getLamTypeConstructorType_Function(node);
            LamTypeFunction *new_variant = cpsTkLamTypeFunction(variant, k);
            if (new_variant != variant) {
                PROTECT(new_variant);
                result = newLamTypeConstructorType_Function(CPI(node), new_variant);
            }
            break;
        }
        case LAMTYPECONSTRUCTORTYPE_TYPE_TUPLE: {
            // LamTypeConstructorArgs
            LamTypeConstructorArgs *variant = getLamTypeConstructorType_Tuple(node);
            LamTypeConstructorArgs *new_variant = cpsTkLamTypeConstructorArgs(variant, k);
            if (new_variant != variant) {
                PROTECT(new_variant);
                result = newLamTypeConstructorType_Tuple(CPI(node), new_variant);
            }
            break;
        }
        default:
            cant_happen("unrecognized LamTypeConstructorType type %d", node->type);
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamTypeConstructorType);
    return result;
}

static LamInfo *cpsTkLamInfo(LamInfo *node, CpsKont *k) {
    ENTER(cpsTkLamInfo);
    if (node == NULL) {
        LEAVE(cpsTkLamInfo);
        return NULL;
    }

    int save = PROTECT(NULL);
    LamInfo *result = node;

    switch (node->type) {
        case LAMINFO_TYPE_TYPECONSTRUCTORINFO: {
            // LamTypeConstructorInfo
            LamTypeConstructorInfo *variant = getLamInfo_TypeConstructorInfo(node);
            LamTypeConstructorInfo *new_variant = cpsTkLamTypeConstructorInfo(variant, k);
            if (new_variant != variant) {
                PROTECT(new_variant);
                result = newLamInfo_TypeConstructorInfo(CPI(node), new_variant);
            }
            break;
        }
        case LAMINFO_TYPE_NAMESPACEINFO: {
            // LamContext
            LamContext *variant = getLamInfo_NameSpaceInfo(node);
            LamContext *new_variant = cpsTkLamContext(variant, k);
            if (new_variant != variant) {
                PROTECT(new_variant);
                result = newLamInfo_NameSpaceInfo(CPI(node), new_variant);
            }
            break;
        }
        case LAMINFO_TYPE_NSID: {
            // int
            break;
        }
        default:
            cant_happen("unrecognized LamInfo type %d", node->type);
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamInfo);
    return result;
}

/*
    (E.namespaces(exprs)) {
        Ts_k(exprs, fn (sexprs) {
            k(E.namespaces(sexprs))
        })
    }
*/
static LamExp *cpsTkLamNameSpaceArray(LamNameSpaceArray *node, CpsKont *k) {
    ENTER(cpsTkLamNameSpaceArray);
    LamExp *seq = nsaToArgs(node);
    int save = PROTECT(seq);
    CpsKont *k1 = makeKont_TkNameSpaces(k);
    PROTECT(k1);
    LamExp *result = cpsTs_k(seq, k1);
    UNPROTECT(save);
    LEAVE(cpsTkLamNameSpaceArray);
    return result;
}

LamExp *TkNameSpacesKont(LamExp *sexprs, TkNameSpacesKontEnv *env) {
    ENTER(TkNameSpacesKont);
    LamNameSpaceArray *nsa = argsToNsa(sexprs);
    int save = PROTECT(nsa);
    LamExp *nsaExp = newLamExp_NameSpaces(CPI(sexprs), nsa);
    PROTECT(nsaExp);
    LamExp *result = INVOKE(env->k, nsaExp);
    UNPROTECT(save);
    LEAVE(TkNameSpacesKont);
    return result;
}

LamExp *nsaToArgs(LamNameSpaceArray *nsa) {
    ENTER(nsaToArgs);
    LamArgs *args = NULL;
    int save = PROTECT(NULL);
    for (Index i = nsa->size; i > 0; i--) {
        LamExp *ns_exp = peeknLamNameSpaceArray(nsa, i - 1);
        args = newLamArgs(CPI(ns_exp), ns_exp, args);
        PROTECT(args);
    }
    LamExp *result = newLamExp_Args(CPI(args), args);
    UNPROTECT(save);
    LEAVE(nsaToArgs);
    return result;
}

LamNameSpaceArray *argsToNsa(LamExp *args_exp) {
    ENTER(argsToNsa);
    LamArgs *args = getLamExp_Args(args_exp);
    LamNameSpaceArray *nsa = newLamNameSpaceArray();
    int save = PROTECT(nsa);
    for (LamArgs *current = args; current != NULL; current = current->next) {
        pushLamNameSpaceArray(nsa, current->exp);
    }
    UNPROTECT(save);
    LEAVE(argsToNsa);
    return nsa;
}

static LamAlphaEnvArray *cpsTkLamAlphaEnvArray(LamAlphaEnvArray *node, CpsKont *k) {
    ENTER(cpsTkLamAlphaEnvArray);
    if (node == NULL) {
        LEAVE(cpsTkLamAlphaEnvArray);
        return NULL;
    }

    bool changed = false;
    LamAlphaEnvArray *result = newLamAlphaEnvArray();
    int save = PROTECT(result);

    // Iterate over all elements
    for (Index i = 0; i < node->size; i++) {
        struct LamAlphaEnv * element = peeknLamAlphaEnvArray(node, i);
        struct LamAlphaEnv * new_element = cpsTkLamAlphaEnv(element, k);
        PROTECT(new_element);
        changed = changed || (new_element != element);
        pushLamAlphaEnvArray(result, new_element);
    }

    if (changed) {
        UNPROTECT(save);
        LEAVE(cpsTkLamAlphaEnvArray);
        return result;
    }

    UNPROTECT(save);
    LEAVE(cpsTkLamAlphaEnvArray);
    return node;
}

LamExp *cpsTk(LamExp *node, CpsKont *k) {
    return cpsTkLamExp(node, k);
}
