/*
 * CEKF - VM supporting amb
 * Copyright (C) 2022-2023  Bill Hails
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
#include <stdio.h>
#include <stdbool.h>

#include "common.h"
#include "ast.h"
#include "debug_ast.h"
#include "parser.h"
#include "analysis.h"
#include "exp.h"
#include "memory.h"
#include "step.h"
#include "debug.h"

#ifdef DEBUG_RUN_TESTS
#if DEBUG_RUN_TESTS == 1

/**
 * these test examples were generated by giving ../tools/makeTree.py each of
 * the scheme files in ../scm then pasting the output here and formatting
 * with `indent --linux`
 */

Exp *makeTestExpAmb() {
    /* back.scm */
    return newExp(EXP_TYPE_LET,
              EXP_VAL_LET(newExpLet
                  (newAexpVar("x"),
                   newExp(CEXP_TYPE_AMB,
                      CEXP_VAL_AMB(newCexpAmb
                               (newExp
                            (AEXP_TYPE_FALSE,
                             AEXP_VAL_NONE()),
                            newExp(AEXP_TYPE_TRUE,
                                   AEXP_VAL_NONE())))),
                   newExp(CEXP_TYPE_COND,
                      CEXP_VAL_COND(newCexpCond
                            (newExp
                             (AEXP_TYPE_VAR,
                              AEXP_VAL_VAR(newAexpVar
                                       ("x"))),
                             newExp(AEXP_TYPE_INT,
                                AEXP_VAL_INT(5)),
                             newExp(CEXP_TYPE_BACK,
                                CEXP_VAL_NONE())))))));
}

Exp *makeTestExpCallCC() {
    /* callcc.scm */
    return newExp(EXP_TYPE_LET,
              EXP_VAL_LET(newExpLet
                  (newAexpVar("x"),
                   newExp(CEXP_TYPE_CALLCC,
                      CEXP_VAL_CALLCC(newExp
                              (AEXP_TYPE_LAM,
                               AEXP_VAL_LAM(newAexpLam
                                    (newAexpVarList
                                     (NULL,
                                      newAexpVar
                                      ("ret")),
                                     newExp
                                     (EXP_TYPE_LET,
                                      EXP_VAL_LET
                                      (newExpLet
                                       (newAexpVar
                                        ("y"),
                                        newExp
                                        (CEXP_TYPE_APPLY,
                                         CEXP_VAL_APPLY
                                         (newCexpApply
                                          (newExp
                                           (AEXP_TYPE_VAR,
                                        AEXP_VAL_VAR
                                        (newAexpVar
                                         ("ret"))),
                                           newAexpList
                                           (NULL,
                                        newExp
                                        (AEXP_TYPE_INT,
                                         AEXP_VAL_INT
                                         (5)))))),
                                        newExp
                                        (CEXP_TYPE_COND,
                                         CEXP_VAL_COND
                                         (newCexpCond
                                          (newExp
                                           (AEXP_TYPE_VAR,
                                        AEXP_VAL_VAR
                                        (newAexpVar
                                         ("y"))),
                                           newExp
                                           (AEXP_TYPE_INT,
                                        AEXP_VAL_INT
                                        (6)),
                                           newExp
                                           (AEXP_TYPE_INT,
                                        AEXP_VAL_INT
                                        (7))))))))))))),
                   newExp(AEXP_TYPE_VAR,
                      AEXP_VAL_VAR(newAexpVar("x"))))));
}

Exp *makeTestExpFib(int depth) {
    /* fib.scm */
    return newExp(CEXP_TYPE_LETREC,
              CEXP_VAL_LETREC(newCexpLetRec
                      (newLetRecBindings
                       (NULL, newAexpVar("fib"),
                    newExp(AEXP_TYPE_LAM,
                           AEXP_VAL_LAM(newAexpLam
                                (newAexpVarList
                                 (NULL, newAexpVar("n")),
                                 newExp(CEXP_TYPE_COND,
                                    CEXP_VAL_COND
                                    (newCexpCond
                                     (newExp
                                      (AEXP_TYPE_PRIM,
                                       AEXP_VAL_PRIM
                                       (newAexpPrimApp
                                    (AEXP_PRIM_LT,
                                     newExp
                                     (AEXP_TYPE_VAR,
                                      AEXP_VAL_VAR
                                      (newAexpVar
                                       ("n"))),
                                     newExp
                                     (AEXP_TYPE_INT,
                                      AEXP_VAL_INT
                                      (2))))),
                                      newExp
                                      (AEXP_TYPE_INT,
                                       AEXP_VAL_INT(1)),
                                      newExp
                                      (EXP_TYPE_LET,
                                       EXP_VAL_LET
                                       (newExpLet
                                    (newAexpVar
                                     ("fib1"),
                                     newExp
                                     (CEXP_TYPE_APPLY,
                                      CEXP_VAL_APPLY
                                      (newCexpApply
                                       (newExp
                                        (AEXP_TYPE_VAR,
                                         AEXP_VAL_VAR
                                         (newAexpVar
                                          ("fib"))),
                                        newAexpList
                                        (NULL,
                                         newExp
                                         (AEXP_TYPE_PRIM,
                                          AEXP_VAL_PRIM
                                          (newAexpPrimApp
                                           (AEXP_PRIM_SUB,
                                        newExp
                                        (AEXP_TYPE_VAR,
                                         AEXP_VAL_VAR
                                         (newAexpVar
                                          ("n"))),
                                        newExp
                                        (AEXP_TYPE_INT,
                                         AEXP_VAL_INT
                                         (1))))))))),
                                     newExp
                                     (EXP_TYPE_LET,
                                      EXP_VAL_LET
                                      (newExpLet
                                       (newAexpVar
                                        ("fib2"),
                                        newExp
                                        (CEXP_TYPE_APPLY,
                                         CEXP_VAL_APPLY
                                         (newCexpApply
                                          (newExp
                                           (AEXP_TYPE_VAR,
                                        AEXP_VAL_VAR
                                        (newAexpVar
                                         ("fib"))),
                                           newAexpList
                                           (NULL,
                                        newExp
                                        (AEXP_TYPE_PRIM,
                                         AEXP_VAL_PRIM
                                         (newAexpPrimApp
                                          (AEXP_PRIM_SUB,
                                           newExp
                                           (AEXP_TYPE_VAR,
                                            AEXP_VAL_VAR
                                            (newAexpVar
                                             ("n"))),
                                           newExp
                                           (AEXP_TYPE_INT,
                                            AEXP_VAL_INT
                                            (2))))))))),
                                        newExp
                                        (AEXP_TYPE_PRIM,
                                         AEXP_VAL_PRIM
                                         (newAexpPrimApp
                                          (AEXP_PRIM_ADD,
                                           newExp
                                           (AEXP_TYPE_VAR,
                                        AEXP_VAL_VAR
                                        (newAexpVar
                                         ("fib1"))),
                                           newExp
                                           (AEXP_TYPE_VAR,
                                        AEXP_VAL_VAR
                                        (newAexpVar
                                         ("fib2"))))))))))))))))))),
                       newExp(CEXP_TYPE_APPLY,
                          CEXP_VAL_APPLY(newCexpApply
                                 (newExp
                                  (AEXP_TYPE_VAR,
                                   AEXP_VAL_VAR(newAexpVar
                                        ("fib"))),
                                  newAexpList(NULL,
                                      newExp
                                      (AEXP_TYPE_INT,
                                       AEXP_VAL_INT
                                       (depth)))))))));

}

int main(int argc, char *argv[]) {
    disableGC();
    Exp *exp = makeTestExpFib(35);
    PROTECT(exp);
    enableGC();
    analizeExp(exp, NULL, 0);
    printExp(exp);
    printf("\n");
    run(exp);
}

#else /* testing parser */

// extern int yydebug;

extern AstNest *result;

int main(int argc, char *argv[]) {
    disableGC();
    // yydebug = 1;
    yyparse();
    printAstNest(result);
}

#endif

#else

int main(int argc, char *argv[]) {
}

#endif
