/*
 * CEKF - VM supporting amb
 * Copyright (C) 2022-2025  Bill Hails
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * Plain lambda structures generated by lambda conversion.
 * Generated from src/lambda.yaml by tools/generate.py
 */

#include "common.h"
#include "memory.h"
#include "minlam.h"
#include "symbol.h"

#include "cps_kont.h"
#include "cps_kont_impl.h"
#include "minlam_cps.h"
#include "minlam_cpsTrampoline.h"
#include "minlam_functions.h"

#ifdef DEBUG_LAMBDA_CPSTK
#include "debugging_on.h"
#else
#include "debugging_off.h"
#endif

// Forward declarations
static MinExp *cpsTkMinPrimApp(MinPrimApp *node, CpsKont *k);
static MinExp *cpsTkMinSequence(MinExprList *node, CpsKont *k);
static MinExp *cpsTkMinApply(MinExp *node, CpsKont *k);
static MinExp *cpsTkMakeVec(MinExprList *node, CpsKont *k);
static MinExp *cpsTkMinIff(MinIff *node, CpsKont *k);
static MinExp *cpsTkMinCond(MinCond *node, CpsKont *k);
static MinExp *cpsTkMinMatch(MinMatch *node, CpsKont *k);
static MinExp *cpsTkMinLetRec(MinLetRec *node, CpsKont *k);
static MinExp *cpsTkMinAmb(MinAmb *node, CpsKont *k);
static MinExp *cpsTkMinExp(MinExp *node, CpsKont *k);
static CpsWork *bridgeMinExpResult(MinExp *result);

static MinExp *packArgsExp(ParserInfo PI, MinExprList *args) {
    return newMinExp_Args(PI, args);
}

static MinExprList *unpackArgsExp(MinExp *argsExp) {
    return getMinExp_Args(argsExp);
}

static int cpsTsKDepthCurrent = 0;
static int cpsTsKDepthMax = 0;
static int tkS1DepthCurrent = 0;
static int tkS1DepthMax = 0;
static int cpsTsKS1CombinedMax = 0;

static void updateCpsDepthStats(void) {
    if (cpsTsKDepthCurrent > cpsTsKDepthMax) {
        cpsTsKDepthMax = cpsTsKDepthCurrent;
        if ((cpsTsKDepthMax % 100) == 0) {
            eprintf("[cpsTk depth] cpsTs_k max=%d\n", cpsTsKDepthMax);
        }
    }
    if (tkS1DepthCurrent > tkS1DepthMax) {
        tkS1DepthMax = tkS1DepthCurrent;
        if ((tkS1DepthMax % 100) == 0) {
            eprintf("[cpsTk depth] TkS1Kont max=%d\n", tkS1DepthMax);
        }
    }
    int combined = cpsTsKDepthCurrent + tkS1DepthCurrent;
    if (combined > cpsTsKS1CombinedMax) {
        cpsTsKS1CombinedMax = combined;
        if ((cpsTsKS1CombinedMax % 100) == 0) {
            eprintf("[cpsTk depth] cpsTs_k+TkS1 combined max=%d\n",
                    cpsTsKS1CombinedMax);
        }
    }
}

// utilities
static MinExp *INVOKE(CpsKont *k, MinExp *arg) {
    CpsWork *work = k->wrapper(arg, k->env);
    return runCpsWorkToResult(work);
}

bool isAexpr(MinExp *exp) {
    switch (exp->type) {
    case MINEXP_TYPE_VAR:
    case MINEXP_TYPE_CHARACTER:
    case MINEXP_TYPE_LAM:
    case MINEXP_TYPE_STDINT:
    case MINEXP_TYPE_BIGINTEGER:
        return true;
    default:
        return false;
    }
}

MinExp *makeVar(ParserInfo PI, char *prefix) {
    return newMinExp_Var(PI, genSymDollar(prefix));
}

MinExprList *appendMinArg(MinExprList *args, MinExp *exp) {
    if (args == NULL)
        return newMinExprList(CPI(exp), exp, NULL);
    MinExprList *next = appendMinArg(args->next, exp);
    int save = PROTECT(next);
    MinExprList *this = newMinExprList(CPI(args), args->exp, next);
    UNPROTECT(save);
    return this;
}

SymbolList *appendMinVar(ParserInfo PI, SymbolList *args, HashSymbol *var) {
    if (args == NULL)
        return newSymbolList(PI, var, NULL);
    SymbolList *next = appendMinVar(PI, args->next, var);
    int save = PROTECT(next);
    SymbolList *this = newSymbolList(CPI(args), args->symbol, next);
    UNPROTECT(save);
    return this;
}

/*
    fn Ts_k {
        ([], k) { k([]) }
        (h @ t, k) {
            T_k(h, fn (hd) {
                Ts_k(t, fn (tl) {
                    k(hd @ tl)
                })
            })
        }
    }
 */
MinExp *cpsTs_k(MinExp *exp, CpsKont *k) {
    ENTER(cpsTs_k);
    CpsWork *start = makeCpsWork_Tsk(exp, k);
    int save = PROTECT(start);
    MinExp *result = runCpsWorkToResult(start);
    UNPROTECT(save);
    LEAVE(cpsTs_k);
    return result;
}

CpsWork *TkS1Kont(MinExp *hd, TkS1KontEnv *env) {
    ENTER(TkS1Kont);
    tkS1DepthCurrent++;
    updateCpsDepthStats();
    CpsKont *k2 = makeKont_TkS2(env->k, hd);
    int save = PROTECT(k2);
    MinExp *args = packArgsExp(CPI(hd), env->t);
    PROTECT(args);
    CpsWork *next =
        makeCpsWork_Tsk(args, k2); // Ts_k(t, fn (tl) { ...k...hd... })
    LEAVE(TkS1Kont);
    UNPROTECT(save);
    tkS1DepthCurrent--;
    return next;
}

CpsWork *TkS2Kont(MinExp *tl, TkS2KontEnv *env) {
    ENTER(TkS2Kont);
    MinExp *args = makeMinExp_Args(CPI(env->hd), env->hd, unpackArgsExp(tl));
    int save = PROTECT(args);
    CpsWork *next = makeCpsWork_Invoke(env->k, args);
    UNPROTECT(save);
    LEAVE(TkS2Kont);
    return next;
}

/*
    fn kToC(k) {
        let rv = gensym("$rv");
        in E.lambda([rv], k(rv))
    }
*/
static MinExp *kToC(ParserInfo PI, CpsKont *k) {
    MinExp *rv = makeVar(PI, "rv");
    int save = PROTECT(rv);
    MinExp *body = INVOKE(k, rv);
    PROTECT(body);
    SymbolList *args = newSymbolList(PI, getMinExp_Var(rv), NULL);
    PROTECT(args);
    MinExp *cont = makeMinExp_Lam(PI, args, body);
    UNPROTECT(save);
    return cont;
}

// Visitor implementations

/*
    (E.primapp(p, e1, e2)) {
        T_k(e1, fn (s1) {
            T_k(e2, fn (s2) {
                k(E.primapp(p, s1, s2))
            })
        })
    }
*/
static MinExp *cpsTkMinPrimApp(MinPrimApp *node, CpsKont *k) {
    ENTER(cpsTkMinPrimApp);
    CpsKont *k1 = makeKont_TkPrimApp1(k, node->exp2, node->type);
    int save = PROTECT(k1);
    MinExp *result = cpsTk(node->exp1, k1);
    UNPROTECT(save);
    LEAVE(cpsTkMinPrimApp);
    return result;
}

CpsWork *TkPrimApp1Kont(MinExp *s1, TkPrimApp1KontEnv *env) {
    ENTER(TkPrimApp1Kont);
    CpsKont *k = makeKont_TkPrimApp2(env->k, s1, env->p);
    int save = PROTECT(k);
    MinExp *result = cpsTk(env->e2, k);
    UNPROTECT(save);
    LEAVE(TkPrimApp1Kont);
    return bridgeMinExpResult(result);
}

CpsWork *TkPrimApp2Kont(MinExp *s2, TkPrimApp2KontEnv *env) {
    ENTER(TkPrimApp2Kont);
    MinExp *primapp = makeMinExp_Prim(CPI(env->s1), env->p, env->s1, s2);
    int save = PROTECT(primapp);
    MinExp *result = INVOKE(env->k, primapp);
    UNPROTECT(save);
    LEAVE(TkPrimApp2Kont);
    return bridgeMinExpResult(result);
}

/*
    (E.sequence([expr])) { T_k(expr, k) }
    (E.sequence(expr @ exprs)) {
        T_k(expr, fn (ignored) {
            T_k(E.sequence(exprs), k)
        })
    }
*/
static MinExp *cpsTkMinSequence(MinExprList *node, CpsKont *k) {
    ENTER(cpsTkMinSequence);
#ifdef SAFETY_CHECKS
    if (node == NULL) {
        cant_happen("NULL node in cpsTkMinSequence");
    }
#endif
    MinExp *result = NULL;
    int save = PROTECT(NULL);
    if (node->next == NULL) {
        result = cpsTk(node->exp, k);
    } else {
        CpsKont *k1 = makeKont_TkSequence(k, node->next);
        PROTECT(k1);
        result = cpsTk(node->exp, k1);
    }
    UNPROTECT(save);
    LEAVE(cpsTkMinSequence);
    return result;
}

CpsWork *TkSequenceKont(MinExp *ignored, TkSequenceKontEnv *env) {
    ENTER(TkSequenceKont);
    MinExp *sequence = newMinExp_Sequence(CPI(ignored), env->exprs);
    int save = PROTECT(sequence);
    MinExp *result = cpsTk(sequence, env->k);
    UNPROTECT(save);
    LEAVE(TkSequenceKont);
    return bridgeMinExpResult(result);
}

/*
    (E.apply(_, _)) {
        let
            c = kToC(k)
        in
            T_c(e, c)
    }
*/
static MinExp *cpsTkMinApply(MinExp *node, CpsKont *k) {
    ENTER(cpsTkMinApply);
    if (node == NULL) {
        LEAVE(cpsTkMinApply);
        return NULL;
    }

    MinExp *c = kToC(CPI(node), k);
    int save = PROTECT(c);
    MinExp *result = cpsTc(node, c);
    UNPROTECT(save);
    LEAVE(cpsTkMinApply);
    return result;
}

/*
    (E.make_vec(size, args)) {
        Ts_k(args, fn (sargs) {
            k(E.make_vec(size, sargs))
        })
    }
*/
static MinExp *cpsTkMakeVec(MinExprList *node, CpsKont *k) {
    ENTER(cpsTkMakeVec);
    CpsKont *k1 = makeKont_TkMakeVec(k);
    int save = PROTECT(k1);
    MinExp *args = packArgsExp(CPI(node), node);
    PROTECT(args);
    MinExp *result = cpsTs_k(args, k1);
    UNPROTECT(save);
    LEAVE(cpsTkMakeVec);
    return result;
}

CpsWork *TkMakeVecKont(MinExp *sargs, TkMakeVecKontEnv *env) {
    ENTER(TkMakeVecKont);
    MinExp *make_vec = newMinExp_MakeVec(CPI(sargs), unpackArgsExp(sargs));
    int save = PROTECT(make_vec);
    MinExp *result = INVOKE(env->k, make_vec);
    UNPROTECT(save);
    LEAVE(TkMakeVecKont);
    return bridgeMinExpResult(result);
}

/*
    (E.if_expr(exprc, exprt, exprf)) {
        let
            c = kToC(k);
        in
            T_k(exprc, fn(aexp) {
                E.if_expr(aexp, T_c(exprt, c), T_c(exprf, c))
            })
    }
*/
static MinExp *cpsTkMinIff(MinIff *node, CpsKont *k) {
    ENTER(cpsTkMinIff);
    if (node == NULL) {
        LEAVE(cpsTkMinIff);
        return NULL;
    }
    MinExp *c = kToC(CPI(node), k);
    int save = PROTECT(c);
    CpsKont *k2 = makeKont_TkIff(c, node->consequent, node->alternative);
    PROTECT(k2);
    MinExp *result = cpsTk(node->condition, k2);
    UNPROTECT(save);
    LEAVE(cpsTkMinIff);
    return result;
}

CpsWork *TkIffKont(MinExp *aexp, TkIffKontEnv *env) {
    ENTER(TkIffKont);
    CpsWork *next =
        makeCpsWork_TkIffAfterCondition(aexp, env->exprt, env->exprf, env->c);
    LEAVE(TkIffKont);
    return next;
}

/*
    (E.cond_expr(test, branches)) {
        let
            c = kToC(k);
        in
            T_k(test, fn (atest) {
                E.cond_expr(atest, list.map(fn {(#(val, result)) {
                    #(val, T_c(result, c))
                }}, branches))
            })
    }
*/
static MinExp *cpsTkMinCond(MinCond *node, CpsKont *k) {
    ENTER(cpsTkMinCond);
    if (node == NULL) {
        LEAVE(cpsTkMinCond);
        return NULL;
    }
    MinExp *c = kToC(CPI(node), k);
    int save = PROTECT(c);
    CpsKont *k2 = makeKont_TkCond(c, node->cases);
    PROTECT(k2);
    MinExp *result = cpsTk(node->value, k2);
    UNPROTECT(save);
    LEAVE(cpsTkMinCond);
    return result;
}

CpsWork *TkCondKont(MinExp *atest, TkCondKontEnv *env) {
    ENTER(TkCondKont);
    MinCondCases *cases = NULL;
    int save = PROTECT(NULL);
    switch (env->branches->type) {
    case MINCONDCASES_TYPE_INTEGERS: {
        CpsWork *mapWork = makeCpsWork_TkMapIntCondCases(
            getMinCondCases_Integers(env->branches), env->c, NULL);
        PROTECT(mapWork);
        CpsPayload *payload = runCpsWorkToPayload(mapWork);
        PROTECT(payload);
        MinIntCondCases *int_cases = getCpsPayload_IntCondCases(payload);
        PROTECT(int_cases);
        cases = newMinCondCases_Integers(CPI(atest), int_cases);
        PROTECT(cases);
    } break;
    case MINCONDCASES_TYPE_CHARACTERS: {
        CpsWork *mapWork = makeCpsWork_TkMapCharCondCases(
            getMinCondCases_Characters(env->branches), env->c, NULL);
        PROTECT(mapWork);
        CpsPayload *payload = runCpsWorkToPayload(mapWork);
        PROTECT(payload);
        MinCharCondCases *char_cases = getCpsPayload_CharCondCases(payload);
        PROTECT(char_cases);
        cases = newMinCondCases_Characters(CPI(atest), char_cases);
        PROTECT(cases);
    } break;
    default:
        cant_happen("Unknown MinCondCases type %s in TkCondKont",
                    minCondCasesTypeName(env->branches->type));
    }
    MinExp *result = makeMinExp_Cond(CPI(atest), atest, cases);
    LEAVE(TkCondKont);
    UNPROTECT(save);
    return bridgeMinExpResult(result);
}

/*
    (E.match_cases(test, cases)) {
        let
            c = kToC(k);
        in
            T_k(test, fn (atest) {
                E.match_cases(atest, list.map(fn {(#(indices, result)) {
                    #(indices, T_c(result, c))
                }}, cases))
            })
    }
*/
static MinExp *cpsTkMinMatch(MinMatch *node, CpsKont *k) {
    ENTER(cpsTkMinMatch);
    MinExp *c = kToC(CPI(node), k);
    int save = PROTECT(c);
    CpsKont *k2 = makeKont_TkMatch(c, node->cases);
    PROTECT(k2);
    MinExp *result = cpsTk(node->index, k2);
    UNPROTECT(save);
    LEAVE(cpsTkMinMatch);
    return result;
}

CpsWork *TkMatchKont(MinExp *atest, TkMatchKontEnv *env) {
    ENTER(TkMatchKont);
    CpsWork *mapWork = makeCpsWork_TkMapMatchCases(env->cases, env->c, NULL);
    int save = PROTECT(mapWork);
    CpsPayload *payload = runCpsWorkToPayload(mapWork);
    PROTECT(payload);
    MinMatchList *cases = getCpsPayload_MatchCases(payload);
    PROTECT(cases);
    MinExp *result = makeMinExp_Match(CPI(atest), atest, cases);
    UNPROTECT(save);
    LEAVE(TkMatchKont);
    return bridgeMinExpResult(result);
}

void cpsUnzipMinBindings(MinBindings *bindings, SymbolList **vars,
                         MinExprList **exps) {
    if (bindings == NULL) {
        *vars = NULL;
        *exps = NULL;
        return;
    }
    cpsUnzipMinBindings(bindings->next, vars, exps);
    *vars = newSymbolList(CPI(bindings), bindings->var, *vars);
    PROTECT(*vars);
    *exps = newMinExprList(CPI(bindings), bindings->val, *exps);
    PROTECT(*exps);
}

MinExp *cpsNestLets(MinBindings *bindings, MinExp *body) {
    if (bindings == NULL) {
        return body;
    }
    MinExp *rest = cpsNestLets(bindings->next, body);
    int save = PROTECT(rest);
    SymbolList *farg = newSymbolList(CPI(bindings), bindings->var, NULL);
    PROTECT(farg);
    MinExp *lambda = makeMinExp_Lam(CPI(bindings), farg, rest);
    PROTECT(lambda);
    MinExprList *aarg = newMinExprList(CPI(bindings), bindings->val, NULL);
    PROTECT(aarg);
    MinExp *apply = makeMinExp_Apply(CPI(bindings), lambda, aarg);
    UNPROTECT(save);
    return apply;
}

MinBindings *mapMOverBindings(MinBindings *bindings) {
    if (bindings == NULL)
        return NULL;
    MinBindings *next = mapMOverBindings(bindings->next);
    int save = PROTECT(next);
    MinExp *val = cpsM(bindings->val);
    PROTECT(val);
    MinBindings *this = newMinBindings(CPI(bindings), bindings->var, val, next);
    this->arity = bindings->arity;
    UNPROTECT(save);
    return this;
}

/*
    (E.letrec_expr(bindings, expr)) {
        let
            #(vars, aexps) = list.unzip(bindings);
        in
            E.letrec_expr(list.zip(vars, list.map(M, aexps)), T_k(expr, k))
    }
*/
static MinExp *cpsTkMinLetRec(MinLetRec *node, CpsKont *k) {
    ENTER(cpsTkMinLetRec);
    MinBindings *bindings = mapMOverBindings(node->bindings);
    int save = PROTECT(bindings);
    MinExp *body = cpsTkMinExp(node->body, k);
    PROTECT(body);
    MinExp *result = makeMinExp_LetRec(CPI(node), bindings, body);
    UNPROTECT(save);
    LEAVE(cpsTkMinLetRec);
    return result;
}

/*
    (E.amb_expr(expr1, expr2)) {
        let
            c = kToC(k);
        in
            E.amb_expr(T_c(expr1, c), T_c(expr2, c))
    }
*/
static MinExp *cpsTkMinAmb(MinAmb *node, CpsKont *k) {
    MinExp *c = kToC(CPI(node), k);
    int save = PROTECT(c);
    MinExp *exp1 = cpsTc(node->left, c);
    PROTECT(exp1);
    MinExp *exp2 = cpsTc(node->right, c);
    PROTECT(exp2);
    MinExp *result = makeMinExp_Amb(CPI(node), exp1, exp2);
    UNPROTECT(save);
    return result;
}

/*
    (E.callCC_expr(e)) {
        let
            c = kToC(k);
        in
            T_c(E.callCC_expr(e), c)
    }
*/
static MinExp *cpsTkCallCC(MinExp *node, CpsKont *k) {
    ENTER(cpsTkCallCC);
    MinExp *c = kToC(CPI(node), k);
    int save = PROTECT(c);
    MinExp *result = cpsTc(node, c);
    UNPROTECT(save);
    LEAVE(cpsTkCallCC);
    return result;
}

static MinExp *cpsTkMinExp(MinExp *node, CpsKont *k) {
    if (node == NULL)
        return NULL;

    if (isAexpr(node)) {
        MinExp *expr = cpsM(node);
        int save = PROTECT(expr);
        MinExp *result = INVOKE(k, expr);
        UNPROTECT(save);
        return result;
    }

    switch (node->type) {
    case MINEXP_TYPE_BACK:
        return node;
    case MINEXP_TYPE_AMB:
        return cpsTkMinAmb(getMinExp_Amb(node), k);
    case MINEXP_TYPE_APPLY:
        return cpsTkMinApply(node, k);
    case MINEXP_TYPE_CALLCC:
        return cpsTkCallCC(getMinExp_CallCC(node), k);
    case MINEXP_TYPE_COND:
        return cpsTkMinCond(getMinExp_Cond(node), k);
    case MINEXP_TYPE_IFF:
        return cpsTkMinIff(getMinExp_Iff(node), k);
    case MINEXP_TYPE_LETREC:
        return cpsTkMinLetRec(getMinExp_LetRec(node), k);
    case MINEXP_TYPE_MAKEVEC:
        return cpsTkMakeVec(getMinExp_MakeVec(node), k);
    case MINEXP_TYPE_MATCH:
        return cpsTkMinMatch(getMinExp_Match(node), k);
    case MINEXP_TYPE_PRIM:
        return cpsTkMinPrimApp(getMinExp_Prim(node), k);
    case MINEXP_TYPE_SEQUENCE:
        return cpsTkMinSequence(getMinExp_Sequence(node), k);
    default:
        cant_happen("unrecognized MinExp type %s [%s %d]",
                    minExpTypeName(node->type), CPI(node).fileName,
                    CPI(node).lineNo);
    }
}

MinExp *cpsTk(MinExp *node, CpsKont *k) { return cpsTkMinExp(node, k); }

static CpsWork *bridgeMinExpResult(MinExp *result) {
    int save = PROTECT(result);
    CpsWork *next = newCpsWork_Result(result);
    UNPROTECT(save);
    return next;
}

static CpsWork *unimplementedTkStep(CpsWork *work) {
    cant_happen("unsupported Tk-step for %s: current CpsWork result currency "
                "is MinExp, "
                "but this tag family requires non-MinExp intermediate values",
                cpsWorkTypeName(work->type));
    return NULL;
}

static MinIntCondCases *reverseMinIntCondCasesList(MinIntCondCases *list) {
    MinIntCondCases *result = NULL;
    int save = PROTECT(result);
    while (list != NULL) {
        MinIntCondCases *node =
            newMinIntCondCases(CPI(list), list->constant, list->body, result);
        result = node;
        REPLACE_PROTECT(save, result);
        list = list->next;
    }
    UNPROTECT(save);
    return result;
}

static MinCharCondCases *reverseMinCharCondCasesList(MinCharCondCases *list) {
    MinCharCondCases *result = NULL;
    int save = PROTECT(result);
    while (list != NULL) {
        MinCharCondCases *node =
            newMinCharCondCases(CPI(list), list->constant, list->body, result);
        result = node;
        REPLACE_PROTECT(save, result);
        list = list->next;
    }
    UNPROTECT(save);
    return result;
}

static MinMatchList *reverseMinMatchList(MinMatchList *list) {
    MinMatchList *result = NULL;
    int save = PROTECT(result);
    while (list != NULL) {
        MinMatchList *node =
            newMinMatchList(CPI(list), list->matches, list->body, result);
        result = node;
        REPLACE_PROTECT(save, result);
        list = list->next;
    }
    UNPROTECT(save);
    return result;
}

CpsWork *cpsStepTk(CpsWork *work) {
    switch (work->type) {
    case CPSWORK_TYPE_TK: {
        CpsTkThunk *tk = getCpsWork_Tk(work);
        MinExp *node = tk->exp;
        CpsKont *k = tk->kont;

        if (isAexpr(node)) {
            MinExp *expr = cpsM(node);
            int save = PROTECT(expr);
            CpsWork *next = makeCpsWork_Invoke(k, expr);
            UNPROTECT(save);
            return next;
        }

        switch (node->type) {
        case MINEXP_TYPE_BACK:
            return bridgeMinExpResult(node);

        case MINEXP_TYPE_PRIM: {
            MinPrimApp *prim = getMinExp_Prim(node);
            CpsKont *k1 = makeKont_TkPrimApp1(k, prim->exp2, prim->type);
            int save = PROTECT(k1);
            CpsWork *next = makeCpsWork_Tk(prim->exp1, k1);
            UNPROTECT(save);
            return next;
        }

        case MINEXP_TYPE_SEQUENCE: {
            MinExprList *seq = getMinExp_Sequence(node);
#ifdef SAFETY_CHECKS
            if (seq == NULL) {
                cant_happen("NULL sequence in cpsStepTk");
            }
#endif
            if (seq->next == NULL) {
                return makeCpsWork_Tk(seq->exp, k);
            }
            CpsKont *k1 = makeKont_TkSequence(k, seq->next);
            int save = PROTECT(k1);
            CpsWork *next = makeCpsWork_Tk(seq->exp, k1);
            UNPROTECT(save);
            return next;
        }

        case MINEXP_TYPE_MAKEVEC: {
            CpsKont *k1 = makeKont_TkMakeVec(k);
            int save = PROTECT(k1);
            MinExprList *vecArgs = getMinExp_MakeVec(node);
            MinExp *args = packArgsExp(CPI(node), vecArgs);
            PROTECT(args);
            CpsWork *next = makeCpsWork_Tsk(args, k1);
            UNPROTECT(save);
            return next;
        }

        case MINEXP_TYPE_IFF: {
            MinIff *iff = getMinExp_Iff(node);
            MinExp *c = kToC(CPI(node), k);
            int save = PROTECT(c);
            CpsKont *k2 = makeKont_TkIff(c, iff->consequent, iff->alternative);
            PROTECT(k2);
            CpsWork *next = makeCpsWork_Tk(iff->condition, k2);
            UNPROTECT(save);
            return next;
        }

        case MINEXP_TYPE_COND: {
            MinCond *cond = getMinExp_Cond(node);
            MinExp *c = kToC(CPI(node), k);
            int save = PROTECT(c);
            CpsKont *k2 = makeKont_TkCond(c, cond->cases);
            PROTECT(k2);
            CpsWork *next = makeCpsWork_Tk(cond->value, k2);
            UNPROTECT(save);
            return next;
        }

        case MINEXP_TYPE_MATCH: {
            MinMatch *match = getMinExp_Match(node);
            MinExp *c = kToC(CPI(node), k);
            int save = PROTECT(c);
            CpsKont *k2 = makeKont_TkMatch(c, match->cases);
            PROTECT(k2);
            CpsWork *next = makeCpsWork_Tk(match->index, k2);
            UNPROTECT(save);
            return next;
        }

        case MINEXP_TYPE_APPLY:
        case MINEXP_TYPE_CALLCC: {
            MinExp *c = kToC(CPI(node), k);
            int save = PROTECT(c);
            CpsWork *next = makeCpsWork_Tc(node, c);
            UNPROTECT(save);
            return next;
        }

        case MINEXP_TYPE_LETREC: {
            MinLetRec *letrec = getMinExp_LetRec(node);
            MinBindings *bindings = mapMOverBindings(letrec->bindings);
            int save = PROTECT(bindings);
            MinExp *body = cpsTkMinExp(letrec->body, k);
            PROTECT(body);
            CpsWork *next = makeCpsWork_TkLetRecAfterBody(bindings, body);
            UNPROTECT(save);
            return next;
        }

        case MINEXP_TYPE_AMB: {
            MinAmb *amb = getMinExp_Amb(node);
            MinExp *c = kToC(CPI(node), k);
            int save = PROTECT(c);
            CpsWork *next =
                makeCpsWork_TkAmbAfterLeft(amb->left, amb->right, c);
            UNPROTECT(save);
            return next;
        }

        default:
            cant_happen("unrecognized MinExp type %s in cpsStepTk",
                        minExpTypeName(node->type));
            return NULL;
        }
    }
    case CPSWORK_TYPE_TSK: {
        CpsTskThunk *tsk = getCpsWork_Tsk(work);
        if (unpackArgsExp(tsk->args) == NULL) {
            return makeCpsWork_Invoke(tsk->kont, tsk->args);
        }
        CpsKont *k1 = makeKont_TkS1(unpackArgsExp(tsk->args)->next, tsk->kont);
        int save = PROTECT(k1);
        CpsWork *next = makeCpsWork_Tk(unpackArgsExp(tsk->args)->exp, k1);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TKIFFAFTERCONDITION: {
        TkIffAfterConditionThunk *th = getCpsWork_TkIffAfterCondition(work);
        MinExp *consequent = cpsTc(th->exprt, th->c);
        int save = PROTECT(consequent);
        CpsWork *next = makeCpsWork_TkIffAfterConsequent(th->aexp, th->exprf,
                                                         th->c, consequent);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TKIFFAFTERCONSEQUENT: {
        TkIffAfterConsequentThunk *th = getCpsWork_TkIffAfterConsequent(work);
        MinExp *alternative = cpsTc(th->exprf, th->c);
        int save = PROTECT(alternative);
        CpsWork *next =
            makeCpsWork_TkIffBuild(th->aexp, th->consequent, alternative);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TKIFFBUILD: {
        TkIffBuildThunk *th = getCpsWork_TkIffBuild(work);
        MinExp *result = makeMinExp_Iff(CPI(th->aexp), th->aexp, th->consequent,
                                        th->alternative);
        return bridgeMinExpResult(result);
    }

    case CPSWORK_TYPE_TKAMBAFTERLEFT: {
        TkAmbAfterLeftThunk *th = getCpsWork_TkAmbAfterLeft(work);
        MinExp *leftVal = cpsTc(th->left, th->c);
        int save = PROTECT(leftVal);
        MinExp *rightVal = cpsTc(th->right, th->c);
        PROTECT(rightVal);
        CpsWork *next = makeCpsWork_TkAmbBuild(leftVal, rightVal);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TKAMBBUILD: {
        TkAmbBuildThunk *th = getCpsWork_TkAmbBuild(work);
        MinExp *result =
            makeMinExp_Amb(CPI(th->leftVal), th->leftVal, th->rightVal);
        return bridgeMinExpResult(result);
    }

    case CPSWORK_TYPE_TKLETRECAFTERBODY: {
        TkLetRecAfterBodyThunk *th = getCpsWork_TkLetRecAfterBody(work);
        MinExp *result =
            makeMinExp_LetRec(CPI(th->body), th->bindings, th->body);
        return bridgeMinExpResult(result);
    }

    case CPSWORK_TYPE_TKMAPINTCONDCASES: {
        TkMapIntCondCasesThunk *th = getCpsWork_TkMapIntCondCases(work);
        if (th->cases == NULL) {
            MinIntCondCases *mapped = reverseMinIntCondCasesList(th->acc);
            int save = PROTECT(mapped);
            CpsPayload *payload = newCpsPayload_IntCondCases(mapped);
            PROTECT(payload);
            CpsWork *next = makeCpsWork_PayloadResult(payload);
            UNPROTECT(save);
            return next;
        }

        MinExp *body = cpsTc(th->cases->body, th->c);
        int save = PROTECT(body);
        CpsWork *next = makeCpsWork_TkMapIntCondCasesAfterBody(
            th->cases->constant, body, th->cases->next, th->c, th->acc);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TKMAPINTCONDCASESAFTERBODY: {
        TkMapIntCondCasesAfterBodyThunk *th =
            getCpsWork_TkMapIntCondCasesAfterBody(work);
        MinIntCondCases *node =
            newMinIntCondCases(CPI(th->body), th->constant, th->body, th->acc);
        int save = PROTECT(node);
        CpsWork *next =
            makeCpsWork_TkMapIntCondCases(th->remaining, th->c, node);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TKMAPCHARCONDCASES: {
        TkMapCharCondCasesThunk *th = getCpsWork_TkMapCharCondCases(work);
        if (th->cases == NULL) {
            MinCharCondCases *mapped = reverseMinCharCondCasesList(th->acc);
            int save = PROTECT(mapped);
            CpsPayload *payload = newCpsPayload_CharCondCases(mapped);
            PROTECT(payload);
            CpsWork *next = makeCpsWork_PayloadResult(payload);
            UNPROTECT(save);
            return next;
        }

        MinExp *body = cpsTc(th->cases->body, th->c);
        int save = PROTECT(body);
        CpsWork *next = makeCpsWork_TkMapCharCondCasesAfterBody(
            th->cases->constant, body, th->cases->next, th->c, th->acc);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TKMAPCHARCONDCASESAFTERBODY: {
        TkMapCharCondCasesAfterBodyThunk *th =
            getCpsWork_TkMapCharCondCasesAfterBody(work);
        MinCharCondCases *node =
            newMinCharCondCases(CPI(th->body), th->constant, th->body, th->acc);
        int save = PROTECT(node);
        CpsWork *next =
            makeCpsWork_TkMapCharCondCases(th->remaining, th->c, node);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TKMAPMATCHCASES: {
        TkMapMatchCasesThunk *th = getCpsWork_TkMapMatchCases(work);
        if (th->cases == NULL) {
            MinMatchList *mapped = reverseMinMatchList(th->acc);
            int save = PROTECT(mapped);
            CpsPayload *payload = newCpsPayload_MatchCases(mapped);
            PROTECT(payload);
            CpsWork *next = makeCpsWork_PayloadResult(payload);
            UNPROTECT(save);
            return next;
        }

        MinExp *body = cpsTc(th->cases->body, th->c);
        int save = PROTECT(body);
        CpsWork *next = makeCpsWork_TkMapMatchCasesAfterBody(
            th->cases->matches, body, th->cases->next, th->c, th->acc);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TKMAPMATCHCASESAFTERBODY: {
        TkMapMatchCasesAfterBodyThunk *th =
            getCpsWork_TkMapMatchCasesAfterBody(work);
        MinMatchList *node =
            newMinMatchList(CPI(th->body), th->matches, th->body, th->acc);
        int save = PROTECT(node);
        CpsWork *next = makeCpsWork_TkMapMatchCases(th->remaining, th->c, node);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_CPSMAPBINDINGS:
    case CPSWORK_TYPE_CPSMAPBINDINGSAFTERVAL:
        return unimplementedTkStep(work);

    case CPSWORK_TYPE_CPSMAPBINDINGSPAYLOAD: {
        CpsMapBindingsPayloadThunk *th = getCpsWork_CpsMapBindingsPayload(work);
        MinBindings *remaining = th->bindings;
        MinBindings *mappedHead = NULL;
        MinBindings *mappedTail = NULL;
        int mappedSave = PROTECT(mappedHead);

        while (remaining != NULL) {
            MinExp *mappedVal = cpsM(remaining->val);
            int save = PROTECT(mappedVal);
            MinBindings *mappedNode =
                newMinBindings(CPI(remaining), remaining->var, mappedVal, NULL);
            mappedNode->arity = remaining->arity;

            if (mappedHead == NULL) {
                mappedHead = mappedNode;
                mappedTail = mappedNode;
                REPLACE_PROTECT(mappedSave, mappedHead);
            } else {
                mappedTail->next = mappedNode;
                mappedTail = mappedNode;
            }

            remaining = remaining->next;
            UNPROTECT(save);
        }

        CpsPayload *payload = newCpsPayload_Bindings(mappedHead);
        int save = PROTECT(payload);
        CpsWork *next = makeCpsWork_PayloadResult(payload);
        UNPROTECT(mappedSave);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_PAYLOADRESULT:
        return work;

    default:
        cant_happen("unhandled Tk-tag %s in cpsStepTk",
                    cpsWorkTypeName(work->type));
        return NULL;
    }
}
