/*
 * CEKF - VM supporting amb
 * Copyright (C) 2022-2025  Bill Hails
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * Plain lambda structures generated by lambda conversion.
 * Generated from src/lambda.yaml by tools/generate.py
 */

#include "common.h"
#include "memory.h"
#include "minlam.h"
#include "symbol.h"

#include "cps_kont.h"
#include "cps_kont_impl.h"
#include "minlam_cps.h"
#include "minlam_cpsTrampoline.h"
#include "minlam_functions.h"

#ifdef DEBUG_LAMBDA_CPSTC
#include "debugging_on.h"
#else
#include "debugging_off.h"
#endif

// Forward declarations
static MinExp *cpsTcMinPrimApp(MinPrimApp *node, MinExp *c);
static MinExp *cpsTcMinSequence(MinExprList *node, MinExp *c);
static MinExp *cpsTcMinApply(MinApply *node, MinExp *c);
static MinExp *cpsTcMakeVec(MinExprList *node, MinExp *c);
static MinExp *cpsTcMinIff(MinIff *node, MinExp *c);
static MinExp *cpsTcMinCond(MinCond *node, MinExp *c);
static MinExp *cpsTcMinMatch(MinMatch *node, MinExp *c);
static MinExp *cpsTcMinLetRec(MinLetRec *node, MinExp *c);
static MinExp *cpsTcMinAmb(MinAmb *node, MinExp *c);
static MinExp *cpsTcMinExp(MinExp *node, MinExp *c);

/*
    fn M {
        (E.lambda(vars, body)) {
            let c = gensym("$k");
            in E.lambda(vars @@ [c], T_c(body, c))
        }
        (x) { x }
    }
*/
MinExp *cpsM(MinExp *node) {
    ENTER(cpsM);
    if (node == NULL) {
        LEAVE(cpsM);
        return NULL;
    }

    switch (node->type) {
    case MINEXP_TYPE_LAM: {
        MinExp *c = makeVar(CPI(node), "k");
        int save = PROTECT(c);
        SymbolList *args = appendMinVar(CPI(node), getMinExp_Lam(node)->args,
                                        getMinExp_Var(c));
        PROTECT(args);
        MinExp *body = cpsTc(getMinExp_Lam(node)->exp, c);
        PROTECT(body);
        MinExp *result = makeMinExp_Lam(CPI(node), args, body);
        UNPROTECT(save);
        LEAVE(cpsM);
        return result;
    }
    default:
        LEAVE(cpsM);
        return node;
    }
}

// Visitor implementations

/*
    (E.primapp(p, e1, e2)) {
        T_k(e1, fn (s1) {
            T_k(e2, fn (s2) {
                E.apply(c, [E.primapp(p, s1, s2)])
            })
        })
    }
*/
static MinExp *cpsTcMinPrimApp(MinPrimApp *node, MinExp *c) {
    ENTER(cpsTcMinPrimApp);
    CpsKont *k = makeKont_TcPrimApp1(c, node->exp2, node->type);
    int save = PROTECT(k);
    MinExp *result = cpsTk(node->exp1, k);
    UNPROTECT(save);
    LEAVE(cpsTcMinPrimApp);
    return result;
}

CpsWork *TcPrimApp1Kont(MinExp *s1, TcPrimApp1KontEnv *env) {
    CpsKont *k = makeKont_TcPrimApp2(env->c, s1, env->p);
    int save = PROTECT(k);
    MinExp *result = cpsTk(env->e2, k);
    PROTECT(result);
    CpsWork *next = newCpsWork_Result(result);
    UNPROTECT(save);
    return next;
}

CpsWork *TcPrimApp2Kont(MinExp *s2, TcPrimApp2KontEnv *env) {
    ENTER(TcPrimApp2Kont);
    MinExp *primapp = makeMinExp_Prim(CPI(env->s1), env->p, env->s1, s2);
    int save = PROTECT(primapp);
    MinExprList *args = newMinExprList(CPI(primapp), primapp, NULL);
    PROTECT(args);
    MinExp *result = makeMinExp_Apply(CPI(primapp), env->c, args);
    PROTECT(result);
    CpsWork *next = newCpsWork_Result(result);
    UNPROTECT(save);
    LEAVE(TcPrimApp2Kont);
    return next;
}

/*
    (E.sequence([expr])) { T_c(expr, c) }
    (E.sequence(expr @ exprs)) {
        T_k(expr, fn (ignored) {
            T_c(E.sequence(exprs), c)
        })
    }
*/
static MinExp *cpsTcMinSequence(MinExprList *node, MinExp *c) {
    ENTER(cpsTcMinSequence);
#ifdef SAFETY_CHECKS
    if (node == NULL) {
        cant_happen("NULL node in cpsTcMinSequence");
    }
#endif
    MinExp *result = NULL;
    int save = PROTECT(NULL);
    if (node->next == NULL) {
        result = cpsTcMinExp(node->exp, c);
    } else {
        CpsKont *kont = makeKont_TcSequence(c, node->next);
        PROTECT(kont);
        result = cpsTk(node->exp, kont);
    }
    UNPROTECT(save);
    LEAVE(cpsTcMinSequence);
    return result;
}

CpsWork *TcSequenceKont(MinExp *ignored, TcSequenceKontEnv *env) {
    ENTER(TcSequenceKont);
    MinExp *sequence = newMinExp_Sequence(CPI(ignored), env->exprs);
    int save = PROTECT(sequence);
    MinExp *result = cpsTcMinExp(sequence, env->c);
    PROTECT(result);
    CpsWork *next = newCpsWork_Result(result);
    UNPROTECT(save);
    LEAVE(TcSequenceKont);
    return next;
}

/*
    (E.apply(f, es)) {
        T_k(f, fn(sf) {
            Ts_k(es, fn (ses) {E.apply(sf, ses @@ [c])})
        })
    }
*/
static MinExp *cpsTcMinApply(MinApply *node, MinExp *c) {
    ENTER(cpsTcMinApply);
    if (node == NULL) {
        LEAVE(cpsTcMinApply);
        return NULL;
    }
    CpsKont *kont1 = makeKont_TcApply1(node->args, c);
    int save = PROTECT(kont1);
    MinExp *result = cpsTk(node->function, kont1);
    UNPROTECT(save);
    LEAVE(cpsTcMinApply);
    return result;
}

CpsWork *TcApply1Kont(MinExp *sf, TcApply1KontEnv *env) {
    ENTER(T_c_apply_1Kont);
    CpsKont *kont2 = makeKont_TcApply2(sf, env->c);
    int save = PROTECT(kont2);
    MinExp *args = newMinExp_Args(CPI(env->c), env->es);
    PROTECT(args);
    MinExp *result = cpsTs_k(args, kont2);
    PROTECT(result);
    CpsWork *next = newCpsWork_Result(result);
    UNPROTECT(save);
    LEAVE(T_c_apply_1Kont);
    return next;
}

CpsWork *TcApply2Kont(MinExp *ses, TcApply2KontEnv *env) {
    ENTER(TcApply2Kont);
    MinExprList *args = appendMinArg(getMinExp_Args(ses), env->c);
    int save = PROTECT(args);
    MinExp *result = makeMinExp_Apply(CPI(env->sf), env->sf, args);
    PROTECT(result);
    CpsWork *next = newCpsWork_Result(result);
    UNPROTECT(save);
    LEAVE(TcApply2Kont);
    return next;
}

/*
    (E.make_vec(size, args)) {
        Ts_k(args, fn (sargs) {
            E.apply(c, [E.make_vec(size, sargs)])
        })
    }
*/
static MinExp *cpsTcMakeVec(MinExprList *node, MinExp *c) {
    ENTER(cpsTcMakeVec);
    CpsKont *kont = makeKont_TcMakeVec(c);
    int save = PROTECT(kont);
    MinExp *args = newMinExp_Args(node == NULL ? NULLPI : CPI(node), node);
    PROTECT(args);
    MinExp *result = cpsTs_k(args, kont);
    UNPROTECT(save);
    LEAVE(cpsTcMakeVec);
    return result;
}

CpsWork *TcMakeVecKont(MinExp *sargs, TcMakeVecKontEnv *env) {
    ENTER(TcMakeVecKont);
    MinExp *make_vec = newMinExp_MakeVec(CPI(sargs), getMinExp_Args(sargs));
    int save = PROTECT(make_vec);
    MinExprList *args = newMinExprList(CPI(sargs), make_vec, NULL);
    PROTECT(args);
    MinExp *result = makeMinExp_Apply(CPI(sargs), env->c, args);
    PROTECT(result);
    CpsWork *next = newCpsWork_Result(result);
    UNPROTECT(save);
    LEAVE(TcMakeVecKont);
    return next;
}

/*
    (E.if_expr(exprc, exprt, exprf)) {
        let
            sk = genstring("$k");
            vsk = E.var(sk);
        in
            E.apply(E.lambda([sk], T_k(exprc, fn (aexp) {
                E.if_expr(aexp, T_c(exprt,vsk), T_c(exprf,vsk))
            })), [c])
    }
*/
static MinExp *cpsTcMinIff(MinIff *node, MinExp *c) {
    ENTER(cpsTcMinIff);
    MinExp *sk = makeVar(CPI(node), "k");
    int save = PROTECT(sk);
    CpsKont *k = makeKont_TcIff(sk, node->consequent, node->alternative);
    PROTECT(k);
    MinExp *body = cpsTk(node->condition, k);
    PROTECT(body);
    SymbolList *args = newSymbolList(CPI(node), getMinExp_Var(sk), NULL);
    PROTECT(args);
    MinExp *lambda = makeMinExp_Lam(CPI(node), args, body);
    PROTECT(lambda);
    MinExprList *arglist = newMinExprList(CPI(node), c, NULL);
    PROTECT(arglist);
    MinExp *result = makeMinExp_Apply(CPI(node), lambda, arglist);
    UNPROTECT(save);
    LEAVE(cpsTcMinIff);
    return result;
}

CpsWork *TcIffKont(MinExp *aexp, TcIffKontEnv *env) {
    ENTER(TcIffKont);
    CpsWork *next =
        makeCpsWork_TcIffAfterCondition(aexp, env->exprt, env->exprf, env->sk);
    LEAVE(TcIffKont);
    return next;
}

/*
    (E.cond_expr(test, branches)) {
        let
            sk = gensym("$k");
        in
            E.apply(E.lambda([sk], T_k(test, fn (atest) {
                E.cond_expr(atest, list.map(fn {(#(val, result)) {
                    #(val, T_c(result, sk))
                }}, branches))
            })), [c])
    }
*/
static MinExp *cpsTcMinCond(MinCond *node, MinExp *c) {
    ENTER(cpsTcMinCond);
    MinExp *sk = makeVar(CPI(node), "k");
    int save = PROTECT(sk);
    CpsKont *k = makeKont_TcCond(sk, node->cases);
    PROTECT(k);
    SymbolList *args = newSymbolList(CPI(node), getMinExp_Var(sk), NULL);
    PROTECT(args);
    MinExp *body = cpsTk(node->value, k);
    PROTECT(body);
    MinExp *lambda = makeMinExp_Lam(CPI(node), args, body);
    PROTECT(lambda);
    MinExprList *arglist = newMinExprList(CPI(node), c, NULL);
    PROTECT(arglist);
    MinExp *result = makeMinExp_Apply(CPI(node), lambda, arglist);
    UNPROTECT(save);
    LEAVE(cpsTcMinCond);
    return result;
}

CpsWork *TcCondKont(MinExp *atest, TcCondKontEnv *env) {
    ENTER(TcCondKont);
    MinExp *result = NULL;
    MinCondCases *cases = NULL;
    int save = PROTECT(NULL);
    switch (env->branches->type) {
    case MINCONDCASES_TYPE_INTEGERS: {
        CpsWork *mapWork = makeCpsWork_TcMapIntCondCases(
            getMinCondCases_Integers(env->branches), env->sk, NULL);
        PROTECT(mapWork);
        CpsPayload *payload = runCpsWorkToPayload(mapWork);
        PROTECT(payload);
        cases = newMinCondCases_Integers(CPI(env->branches),
                                         getCpsPayload_IntCondCases(payload));
        PROTECT(cases);
    } break;
    case MINCONDCASES_TYPE_CHARACTERS: {
        CpsWork *mapWork = makeCpsWork_TcMapCharCondCases(
            getMinCondCases_Characters(env->branches), env->sk, NULL);
        PROTECT(mapWork);
        CpsPayload *payload = runCpsWorkToPayload(mapWork);
        PROTECT(payload);
        cases = newMinCondCases_Characters(
            CPI(env->branches), getCpsPayload_CharCondCases(payload));
        PROTECT(cases);
    } break;
    }
    result = makeMinExp_Cond(CPI(env->branches), atest, cases);
    PROTECT(result);
    CpsWork *next = newCpsWork_Result(result);
    UNPROTECT(save);
    LEAVE(TcCondKont);
    return next;
}

/*
    (E.match_cases(test, cases)) {
        let
            sk = gensym("$k");
        in
            E.apply(E.lambda([sk], T_k(test, fn (atest) {
                E.match_cases(atest, list.map(fn {(#(indices, result)) {
                    #(indices, T_c(result, sk))
                }}, cases))
            })), [c])
    }
*/
static MinExp *cpsTcMinMatch(MinMatch *node, MinExp *c) {
    ENTER(cpsTcMinMatch);
    MinExp *sk = makeVar(CPI(node), "k");
    int save = PROTECT(sk);
    CpsKont *k = makeKont_TcMatch(sk, node->cases);
    PROTECT(k);
    SymbolList *args = newSymbolList(CPI(node), getMinExp_Var(sk), NULL);
    PROTECT(args);
    MinExp *body = cpsTk(node->index, k);
    PROTECT(body);
    MinExp *lambda = makeMinExp_Lam(CPI(node), args, body);
    PROTECT(lambda);
    MinExprList *arglist = newMinExprList(CPI(node), c, NULL);
    PROTECT(arglist);
    MinExp *result = makeMinExp_Apply(CPI(node), lambda, arglist);
    UNPROTECT(save);
    LEAVE(cpsTcMinMatch);
    return result;
}

CpsWork *TcMatchKont(MinExp *atest, TcMatchKontEnv *env) {
    ENTER(TcMatchKont);
    CpsWork *mapWork = makeCpsWork_TcMapMatchCases(env->cases, env->sk, NULL);
    int save = PROTECT(mapWork);
    CpsPayload *payload = runCpsWorkToPayload(mapWork);
    PROTECT(payload);
    MinMatchList *cases = getCpsPayload_MatchCases(payload);
    PROTECT(cases);
    MinExp *result = makeMinExp_Match(CPI(env->cases), atest, cases);
    PROTECT(result);
    CpsWork *next = newCpsWork_Result(result);
    UNPROTECT(save);
    LEAVE(TcMatchKont);
    return next;
}

/*
    (E.letrec_expr(bindings, expr)) {
        let
            #(vars, aexps) = list.unzip(bindings);
        in
            E.letrec_expr(list.zip(vars, list.map(M, aexps)), T_c(expr, c))
    }
*/
static MinExp *cpsTcMinLetRec(MinLetRec *node, MinExp *c) {
    ENTER(cpsTcMinLetRec);
    MinBindings *bindings = mapMOverBindings(node->bindings);
    int save = PROTECT(bindings);
    MinExp *body = cpsTc(node->body, c);
    PROTECT(body);
    MinExp *result = makeMinExp_LetRec(CPI(node), bindings, body);
    UNPROTECT(save);
    LEAVE(cpsTcMinLetRec);
    return result;
}

/*
    (E.amb_expr(expr1, expr2)) {
        let
            k = gensym("$k");
        in
            E.apply(E.lambda([k], E.amb_expr(T_c(expr1, k), T_c(expr2, k))),
   [c])
    }
*/
static MinExp *cpsTcMinAmb(MinAmb *node, MinExp *c) {
    ENTER(cpsTcMinAmb);
    if (node == NULL) {
        LEAVE(cpsTcMinAmb);
        return NULL;
    }

    MinExp *k = makeVar(CPI(node), "k");
    int save = PROTECT(k);
    MinExp *e1 = cpsTc(node->left, k);
    PROTECT(e1);
    MinExp *e2 = cpsTc(node->right, k);
    PROTECT(e2);
    MinExp *lamAmb = makeMinExp_Amb(CPI(node), e1, e2);
    PROTECT(lamAmb);
    SymbolList *fargs = newSymbolList(CPI(node), getMinExp_Var(k), NULL);
    PROTECT(fargs);
    MinExp *lambda = makeMinExp_Lam(CPI(node), fargs, lamAmb);
    PROTECT(lambda);
    MinExprList *aargs = newMinExprList(CPI(node), c, NULL);
    PROTECT(aargs);
    MinExp *result = makeMinExp_Apply(CPI(node), lambda, aargs);
    LEAVE(cpsTcMinAmb);
    UNPROTECT(save);
    return result;
}

/*
    (lambda (f cc)
        (f (lambda (x i) (cc x))
           cc))
*/
static MinExp *makeCallCC(ParserInfo PI) {
    MinExp *f = makeVar(PI, "f");
    int save = PROTECT(f);
    MinExp *cc = makeVar(PI, "cc");
    PROTECT(cc);
    MinExp *x = makeVar(PI, "x");
    PROTECT(x);
    MinExp *i = makeVar(PI, "i");
    PROTECT(i);
    MinExprList *args = newMinExprList(PI, x, NULL); // (x)
    PROTECT(args);
    MinExp *apply = makeMinExp_Apply(PI, cc, args); // (cc x)
    PROTECT(apply);
    SymbolList *vars = newSymbolList(PI, getMinExp_Var(i), NULL); // (i)
    PROTECT(vars);
    vars = newSymbolList(PI, getMinExp_Var(x), vars); // (x i)
    PROTECT(vars);
    MinExp *lambda = makeMinExp_Lam(PI, vars, apply); // (lambda (x i) (cc x))
    PROTECT(lambda);
    args = newMinExprList(PI, lambda, NULL); // ((lambda (x i) (cc x)))
    PROTECT(args);
    args = newMinExprList(PI, cc, args); // ((lambda (x i) (cc x)) cc)
    PROTECT(args);
    apply = makeMinExp_Apply(PI, f, args); // (f (lambda (x i) (cc x)) cc)
    PROTECT(apply);
    vars = newSymbolList(PI, getMinExp_Var(cc), NULL); // (cc)
    PROTECT(vars);
    vars = newSymbolList(PI, getMinExp_Var(f), vars); // (f cc)
    PROTECT(vars);
    lambda = makeMinExp_Lam(
        PI, vars, apply); // (lambda (f cc) (f (lambda (x i) (cc x)) cc))
    UNPROTECT(save);
    return lambda;
}

/*
    (E.callCC_expr(e)) {
        T_k(e, fn (sf) {
            E.apply(
                E.parse("(lambda (f cc) (f (lambda (x i) (cc x)) cc))"),
                [sf, c]
            )
        })
    }
*/
static MinExp *cpsTcCallCC(MinExp *e, MinExp *c) {
    ENTER(cpsTcCallCC);
    CpsKont *k = makeKont_TcCallCC(c);
    int save = PROTECT(k);
    MinExp *result = cpsTk(e, k);
    UNPROTECT(save);
    LEAVE(cpsTcCallCC);
    return result;
}

CpsWork *TcCallCCKont(MinExp *sf, TcCallCCKontEnv *env) {
    ENTER(TcCallCCKont);
    MinExp *callCC = makeCallCC(CPI(sf));
    int save = PROTECT(callCC);
    MinExprList *args = newMinExprList(CPI(env->c), env->c, NULL);
    PROTECT(args);
    args = newMinExprList(CPI(env->c), sf, args);
    PROTECT(args);
    MinExp *result = makeMinExp_Apply(CPI(env->c), callCC, args);
    PROTECT(result);
    CpsWork *next = newCpsWork_Result(result);
    UNPROTECT(save);
    LEAVE(TcCallCCKont);
    return next;
}

static MinExp *cpsTcMinExp(MinExp *node, MinExp *c) {
    if (node == NULL)
        return NULL;

    if (isAexpr(node)) {
        MinExp *exp = cpsM(node);
        int save = PROTECT(exp);
        MinExprList *arglist = newMinExprList(CPI(node), exp, NULL);
        PROTECT(arglist);
        MinExp *result = makeMinExp_Apply(CPI(node), c, arglist);
        UNPROTECT(save);
        return result;
    }

    switch (node->type) {
    case MINEXP_TYPE_BACK:
        return node;
    case MINEXP_TYPE_AMB:
        return cpsTcMinAmb(getMinExp_Amb(node), c);
    case MINEXP_TYPE_APPLY:
        return cpsTcMinApply(getMinExp_Apply(node), c);
    case MINEXP_TYPE_CALLCC:
        return cpsTcCallCC(getMinExp_CallCC(node), c);
    case MINEXP_TYPE_COND:
        return cpsTcMinCond(getMinExp_Cond(node), c);
    case MINEXP_TYPE_IFF:
        return cpsTcMinIff(getMinExp_Iff(node), c);
    case MINEXP_TYPE_LETREC:
        return cpsTcMinLetRec(getMinExp_LetRec(node), c);
    case MINEXP_TYPE_MAKEVEC:
        return cpsTcMakeVec(getMinExp_MakeVec(node), c);
    case MINEXP_TYPE_MATCH:
        return cpsTcMinMatch(getMinExp_Match(node), c);
    case MINEXP_TYPE_PRIM:
        return cpsTcMinPrimApp(getMinExp_Prim(node), c);
    case MINEXP_TYPE_SEQUENCE:
        return cpsTcMinSequence(getMinExp_Sequence(node), c);
    default:
        cant_happen("unrecognized MinExp type %s", minExpTypeName(node->type));
    }
}

MinExp *cpsTc(MinExp *node, MinExp *c) {
    ENTER(cpsTc);
    MinExp *result = cpsTcMinExp(node, c);
    LEAVE(cpsTc);
    return result;
}

static MinIntCondCases *reverseMinIntCondCasesList(MinIntCondCases *list) {
    int save = PROTECT(list); // claim a stack slot
    MinIntCondCases *result = NULL;
    while (list != NULL) {
        MinIntCondCases *node =
            newMinIntCondCases(CPI(list), list->constant, list->body, result);
        result = node;
        REPLACE_PROTECT(save, result);
        list = list->next;
    }
    UNPROTECT(save);
    return result;
}

static MinCharCondCases *reverseMinCharCondCasesList(MinCharCondCases *list) {
    int save = PROTECT(list); // claim a stack slot
    MinCharCondCases *result = NULL;
    while (list != NULL) {
        MinCharCondCases *node =
            newMinCharCondCases(CPI(list), list->constant, list->body, result);
        result = node;
        REPLACE_PROTECT(save, result);
        list = list->next;
    }
    UNPROTECT(save);
    return result;
}

static MinMatchList *reverseMinMatchList(MinMatchList *list) {
    int save = PROTECT(list); // claim a stack slot
    MinMatchList *result = NULL;
    while (list != NULL) {
        MinMatchList *node =
            newMinMatchList(CPI(list), list->matches, list->body, result);
        result = node;
        REPLACE_PROTECT(save, result);
        list = list->next;
    }
    UNPROTECT(save);
    return result;
}

CpsWork *cpsStepTc(CpsWork *work) {
    switch (work->type) {
    case CPSWORK_TYPE_TC: {
        CpsTcThunk *tc = getCpsWork_Tc(work);
        MinExp *node = tc->exp;
        MinExp *c = tc->cont;

        if (node == NULL) {
            return newCpsWork_Result(NULL);
        }

        if (isAexpr(node)) {
            MinExp *exp = cpsM(node);
            int save = PROTECT(exp);
            MinExprList *arglist = newMinExprList(CPI(node), exp, NULL);
            PROTECT(arglist);
            MinExp *result = makeMinExp_Apply(CPI(node), c, arglist);
            PROTECT(result);
            CpsWork *next = newCpsWork_Result(result);
            UNPROTECT(save);
            return next;
        }

        switch (node->type) {
        case MINEXP_TYPE_BACK:
            return newCpsWork_Result(node);

        case MINEXP_TYPE_PRIM: {
            MinPrimApp *prim = getMinExp_Prim(node);
            CpsKont *k = makeKont_TcPrimApp1(c, prim->exp2, prim->type);
            int save = PROTECT(k);
            CpsWork *next = makeCpsWork_Tk(prim->exp1, k);
            UNPROTECT(save);
            return next;
        }

        case MINEXP_TYPE_SEQUENCE: {
            MinExprList *seq = getMinExp_Sequence(node);
#ifdef SAFETY_CHECKS
            if (seq == NULL) {
                cant_happen("NULL sequence in cpsStepTc");
            }
#endif
            if (seq->next == NULL) {
                return makeCpsWork_Tc(seq->exp, c);
            }
            CpsKont *kont = makeKont_TcSequence(c, seq->next);
            int save = PROTECT(kont);
            CpsWork *next = makeCpsWork_Tk(seq->exp, kont);
            UNPROTECT(save);
            return next;
        }

        case MINEXP_TYPE_APPLY: {
            MinApply *apply = getMinExp_Apply(node);
            CpsKont *kont1 = makeKont_TcApply1(apply->args, c);
            int save = PROTECT(kont1);
            CpsWork *next = makeCpsWork_Tk(apply->function, kont1);
            UNPROTECT(save);
            return next;
        }

        case MINEXP_TYPE_CALLCC: {
            CpsKont *k = makeKont_TcCallCC(c);
            int save = PROTECT(k);
            CpsWork *next = makeCpsWork_Tk(getMinExp_CallCC(node), k);
            UNPROTECT(save);
            return next;
        }

        case MINEXP_TYPE_MAKEVEC: {
            MinExprList *vecArgs = getMinExp_MakeVec(node);
            CpsKont *kont = makeKont_TcMakeVec(c);
            int save = PROTECT(kont);
            MinExp *args = newMinExp_Args(
                vecArgs == NULL ? NULLPI : CPI(vecArgs), vecArgs);
            PROTECT(args);
            CpsWork *next = makeCpsWork_Tsk(args, kont);
            UNPROTECT(save);
            return next;
        }

        case MINEXP_TYPE_AMB: {
            MinAmb *amb = getMinExp_Amb(node);
            MinExp *kVar = makeVar(CPI(node), "k");
            int save = PROTECT(kVar);
            CpsWork *next =
                makeCpsWork_TcAmbAfterLeft(amb->left, amb->right, kVar, c);
            UNPROTECT(save);
            return next;
        }

        default: {
            MinExp *result = cpsTc(node, c);
            int save = PROTECT(result);
            CpsWork *work = newCpsWork_Result(result);
            UNPROTECT(save);
            return work;
        }
        }
    }

    case CPSWORK_TYPE_TCIFFAFTERCONDITION: {
        TcIffAfterConditionThunk *th = getCpsWork_TcIffAfterCondition(work);
        int save = PROTECT(th);
        CpsWork *tcWork = makeCpsWork_Tc(th->exprt, th->sk);
        PROTECT(tcWork);
        MinExp *thenExp = runCpsWorkToResult(tcWork);
        PROTECT(thenExp);
        CpsWork *next =
            makeCpsWork_TcIffAfterThen(th->aexp, th->exprf, th->sk, thenExp);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TCIFFAFTERTHEN: {
        TcIffAfterThenThunk *th = getCpsWork_TcIffAfterThen(work);
        int save = PROTECT(th);
        CpsWork *tcWork = makeCpsWork_Tc(th->exprf, th->sk);
        PROTECT(tcWork);
        MinExp *elseExp = runCpsWorkToResult(tcWork);
        PROTECT(elseExp);
        CpsWork *next = makeCpsWork_TcIffBuild(th->aexp, th->thenExp, elseExp);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TCIFFBUILD: {
        TcIffBuildThunk *th = getCpsWork_TcIffBuild(work);
        int save = PROTECT(th);
        MinExp *result =
            makeMinExp_Iff(CPI(th->aexp), th->aexp, th->thenExp, th->elseExp);
        PROTECT(result);
        CpsWork *next = newCpsWork_Result(result);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TCAMBAFTERLEFT: {
        TcAmbAfterLeftThunk *th = getCpsWork_TcAmbAfterLeft(work);
        int save = PROTECT(th);
        CpsWork *leftWork = makeCpsWork_Tc(th->left, th->k);
        PROTECT(leftWork);
        MinExp *leftVal = runCpsWorkToResult(leftWork);
        PROTECT(leftVal);
        CpsWork *rightWork = makeCpsWork_Tc(th->right, th->k);
        PROTECT(rightWork);
        MinExp *rightVal = runCpsWorkToResult(rightWork);
        PROTECT(rightVal);
        CpsWork *next = makeCpsWork_TcAmbBuild(th->k, th->c, leftVal, rightVal);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TCAMBBUILD: {
        TcAmbBuildThunk *th = getCpsWork_TcAmbBuild(work);
        int save = PROTECT(th);
        MinExp *lamAmb =
            makeMinExp_Amb(CPI(th->leftVal), th->leftVal, th->rightVal);
        PROTECT(lamAmb);
        SymbolList *fargs =
            newSymbolList(CPI(th->k), getMinExp_Var(th->k), NULL);
        PROTECT(fargs);
        MinExp *lambda = makeMinExp_Lam(CPI(th->k), fargs, lamAmb);
        PROTECT(lambda);
        MinExprList *aargs = newMinExprList(CPI(th->k), th->c, NULL);
        PROTECT(aargs);
        MinExp *result = makeMinExp_Apply(CPI(th->k), lambda, aargs);
        PROTECT(result);
        CpsWork *next = newCpsWork_Result(result);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TCLETRECAFTERBODY: {
        TcLetRecAfterBodyThunk *th = getCpsWork_TcLetRecAfterBody(work);
        int save = PROTECT(th);
        MinExp *result =
            makeMinExp_LetRec(CPI(th->body), th->bindings, th->body);
        PROTECT(result);
        CpsWork *next = newCpsWork_Result(result);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_MLAMAFTERBODY: {
        MLamAfterBodyThunk *th = getCpsWork_MLamAfterBody(work);
        int save = PROTECT(th);
        MinExp *result = makeMinExp_Lam(CPI(th->body), th->args, th->body);
        PROTECT(result);
        CpsWork *next = newCpsWork_Result(result);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TCMAPINTCONDCASES: {
        TcMapIntCondCasesThunk *th = getCpsWork_TcMapIntCondCases(work);
        int save = PROTECT(th);
        if (th->cases == NULL) {
            MinIntCondCases *mapped = reverseMinIntCondCasesList(th->acc);
            PROTECT(mapped);
            CpsPayload *payload = newCpsPayload_IntCondCases(mapped);
            PROTECT(payload);
            CpsWork *next = makeCpsWork_PayloadResult(payload);
            UNPROTECT(save);
            return next;
        }

        CpsWork *tcWork = makeCpsWork_Tc(th->cases->body, th->sk);
        PROTECT(tcWork);
        MinExp *body = runCpsWorkToResult(tcWork);
        PROTECT(body);
        CpsWork *next = makeCpsWork_TcMapIntCondCasesAfterBody(
            th->cases->constant, body, th->cases->next, th->sk, th->acc);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TCMAPINTCONDCASESAFTERBODY: {
        TcMapIntCondCasesAfterBodyThunk *th =
            getCpsWork_TcMapIntCondCasesAfterBody(work);
        int save = PROTECT(th);
        MinIntCondCases *node =
            newMinIntCondCases(CPI(th->body), th->constant, th->body, th->acc);
        PROTECT(node);
        CpsWork *next =
            makeCpsWork_TcMapIntCondCases(th->remaining, th->sk, node);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TCMAPCHARCONDCASES: {
        TcMapCharCondCasesThunk *th = getCpsWork_TcMapCharCondCases(work);
        int save = PROTECT(th);
        if (th->cases == NULL) {
            MinCharCondCases *mapped = reverseMinCharCondCasesList(th->acc);
            PROTECT(mapped);
            CpsPayload *payload = newCpsPayload_CharCondCases(mapped);
            PROTECT(payload);
            CpsWork *next = makeCpsWork_PayloadResult(payload);
            UNPROTECT(save);
            return next;
        }

        CpsWork *tcWork = makeCpsWork_Tc(th->cases->body, th->sk);
        PROTECT(tcWork);
        MinExp *body = runCpsWorkToResult(tcWork);
        PROTECT(body);
        CpsWork *next = makeCpsWork_TcMapCharCondCasesAfterBody(
            th->cases->constant, body, th->cases->next, th->sk, th->acc);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TCMAPCHARCONDCASESAFTERBODY: {
        TcMapCharCondCasesAfterBodyThunk *th =
            getCpsWork_TcMapCharCondCasesAfterBody(work);
        int save = PROTECT(th);
        MinCharCondCases *node =
            newMinCharCondCases(CPI(th->body), th->constant, th->body, th->acc);
        PROTECT(node);
        CpsWork *next =
            makeCpsWork_TcMapCharCondCases(th->remaining, th->sk, node);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TCMAPMATCHCASES: {
        TcMapMatchCasesThunk *th = getCpsWork_TcMapMatchCases(work);
        int save = PROTECT(th);
        if (th->cases == NULL) {
            MinMatchList *mapped = reverseMinMatchList(th->acc);
            PROTECT(mapped);
            CpsPayload *payload = newCpsPayload_MatchCases(mapped);
            PROTECT(payload);
            CpsWork *next = makeCpsWork_PayloadResult(payload);
            UNPROTECT(save);
            return next;
        }

        CpsWork *tcWork = makeCpsWork_Tc(th->cases->body, th->sk);
        PROTECT(tcWork);
        MinExp *body = runCpsWorkToResult(tcWork);
        PROTECT(body);
        CpsWork *next = makeCpsWork_TcMapMatchCasesAfterBody(
            th->cases->matches, body, th->cases->next, th->sk, th->acc);
        UNPROTECT(save);
        return next;
    }

    case CPSWORK_TYPE_TCMAPMATCHCASESAFTERBODY: {
        TcMapMatchCasesAfterBodyThunk *th =
            getCpsWork_TcMapMatchCasesAfterBody(work);
        int save = PROTECT(th);
        MinMatchList *node =
            newMinMatchList(CPI(th->body), th->matches, th->body, th->acc);
        PROTECT(node);
        CpsWork *next =
            makeCpsWork_TcMapMatchCases(th->remaining, th->sk, node);
        UNPROTECT(save);
        return next;
    }

    default:
        cant_happen("unhandled Tc-tag %s in cpsStepTc",
                    cpsWorkTypeName(work->type));
        return NULL;
    }
}