name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install sqlite
      run: make install-sqlite3

    - name: Build executable
      run: make MODE=testing

    - name: Run tests
      run: make test MODE=testing
